// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(AchievementData, 1);
impl<'a> AchievementData<'a> {
    string_field!(field_0, 0);
}


define_row!(AchievementRow);
impl AchievementRow {
    string_field!(name, 1);
    string_field!(description, 2);
    u32_field!(item, 7);
    u32_field!(icon, 11);
    i32_field!(key, 14);
    array_field!(data, 5, 8, AchievementData);
    u16_field!(title, 6);
    u16_field!(order, 23);
    u8_field!(achievement_category, 0);
    u8_field!(achievement_target, 3);
    u8_field!(unknown_0, 4);
    u8_field!(points, 5);
    u8_field!(unknown_1, 8);
    u8_field!(unknown_2, 9);
    u8_field!(unknown_3, 10);
    u8_field!(unknown_4, 12);
    u8_field!(type_, 13);
    u8_field!(unknown_5, 24);
    u8_field!(achievement_hide_condition, 25);
}

define_sheet!(AchievementSheet, AchievementRow, "Achievement", language_support);
