// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AchievementTargetRow);
impl AchievementTargetRow {
    u32_field!(value, 0);
    u8_field!(type_, 1);
}

define_sheet!(AchievementTargetSheet, AchievementTargetRow, "AchievementTarget");
