// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AchievementCategoryRow);
impl AchievementCategoryRow {
    string_field!(name, 0);
    u8_field!(achievement_kind, 1);
    u8_field!(order, 4);
    bool_field!(show_complete, 2);
    bool_field!(hide_category, 3);
}

define_sheet!(AchievementCategorySheet, AchievementCategoryRow, "AchievementCategory");
