// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AchievementKindRow);
impl AchievementKindRow {
    string_field!(name, 0);
    u8_field!(order, 1);
}

define_sheet!(AchievementKindSheet, AchievementKindRow, "AchievementKind");
