// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AchievementHideConditionRow);
impl AchievementHideConditionRow {
    bool_field!(hide_achievement, 0);
    bool_field!(hide_name, 1);
    bool_field!(hide_conditions, 2);
}

define_sheet!(AchievementHideConditionSheet, AchievementHideConditionRow, "AchievementHideCondition", no_language_support);
