// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ActivityFeedImagesRow);
impl ActivityFeedImagesRow {
    string_field!(expansion_image, 0);
    string_field!(activity_feed_ja, 1);
    string_field!(activity_feed_en, 2);
    string_field!(activity_feed_de, 3);
    string_field!(activity_feed_fr, 4);
}

define_sheet!(ActivityFeedImagesSheet, ActivityFeedImagesRow, "ActivityFeedImages", no_language_support);
