// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ActionParamRow);
impl ActionParamRow {
    i16_field!(name, 0);
    i16_field!(unknown_0, 1);
}

define_sheet!(ActionParamSheet, ActionParamRow, "ActionParam");
