// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ActionRow);
impl ActionRow {
    string_field!(name, 0);
    u32_field!(unlock_link, 49);
    u16_field!(icon, 2);
    u16_field!(vfx, 6);
    u16_field!(action_timeline_hit, 8);
    u16_field!(primary_cost_value, 33);
    u16_field!(secondary_cost_value, 35);
    u16_field!(action_combo, 36);
    u16_field!(cast_100_ms, 38);
    u16_field!(recast_100_ms, 40);
    u16_field!(action_proc_status, 46);
    u16_field!(status_gain_self, 48);
    u16_field!(omen, 54);
    u16_field!(omen_alt, 55);
    i16_field!(animation_end, 7);
    u8_field!(action_category, 3);
    u8_field!(unknown_1, 4);
    u8_field!(animation_start, 5);
    u8_field!(unknown_2, 9);
    u8_field!(behaviour_type, 11);
    u8_field!(class_job_level, 12);
    u8_field!(cast_type, 28);
    u8_field!(effect_range, 29);
    u8_field!(x_axis_modifier, 30);
    u8_field!(primary_cost_type, 32);
    u8_field!(secondary_cost_type, 34);
    u8_field!(extra_cast_time_100_ms, 39);
    u8_field!(cooldown_group, 41);
    u8_field!(additional_cooldown_group, 42);
    u8_field!(max_charges, 43);
    u8_field!(aspect, 45);
    u8_field!(unknown_4, 47);
    u8_field!(class_job_category, 50);
    // 0 &#x3D; no effect on auto attacks, 1 &#x3D; typical cast (unsheathe weapon, but don&#x27;t touch autos), 2 &#x3D; typical weaponskill (unsheathe, start autos if action target is primary target), 3 &#x3D; sleep-like effect (unsheathe, stop autos), 4 &#x3D; typical point-blank aoe (unsheathe, start autos if primary target is within action range), 5 &#x3D; ??? (doesn&#x27;t touch weapon state), 6 &#x3D; typical channeled action (unsheathe, stop autos, do not auto-face target), 7 &#x3D; force sheathe and stop autos, 8 &#x3D; ??? (unused)
    u8_field!(auto_attack_behaviour, 51);
    // set for eg crafting actions, when different jobs have different rows, but they need to be considered interchangeable
    u8_field!(equivalence_group, 65);
    u8_field!(unknown_70, 70);
    i8_field!(class_job, 10);
    i8_field!(range, 15);
    // 0 &#x3D; can not target dead, 1 &#x3D; can only target dead players (+ some other conditions), 2 &#x3D; ???
    i8_field!(dead_target_behaviour, 25);
    i8_field!(attack_type, 44);
    bool_field!(unknown_8, 1);
    bool_field!(is_role_action, 13);
    bool_field!(unknown_28, 14);
    bool_field!(can_target_self, 16);
    bool_field!(can_target_party, 17);
    bool_field!(can_target_alliance, 18);
    bool_field!(can_target_hostile, 19);
    bool_field!(can_target_ally, 20);
    bool_field!(unknown_10, 21);
    bool_field!(target_area, 22);
    bool_field!(can_target_own_pet, 23);
    bool_field!(can_target_party_pet, 24);
    bool_field!(requires_line_of_sight, 26);
    bool_field!(need_to_face_target, 27);
    bool_field!(unknown_14, 31);
    bool_field!(preserves_combo, 37);
    bool_field!(unknown_15, 52);
    bool_field!(affects_position, 53);
    bool_field!(is_pv_p, 56);
    bool_field!(unknown_16, 57);
    bool_field!(log_cast_message, 58);
    bool_field!(unknown_18, 59);
    bool_field!(log_miss_message, 60);
    bool_field!(log_action_message, 61);
    bool_field!(unknown_21, 62);
    bool_field!(unknown_22, 63);
    bool_field!(unknown_23, 64);
    bool_field!(can_use_while_mounted, 66);
    bool_field!(unknown_25, 67);
    bool_field!(is_player_action, 68);
    bool_field!(unknown_27, 69);
}

define_sheet!(ActionSheet, ActionRow, "Action", language_support);
