// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ActionTimelineReplaceRow);
impl ActionTimelineReplaceRow {
    u16_field!(old, 0);
    u16_field!(new, 1);
}

define_sheet!(ActionTimelineReplaceSheet, ActionTimelineReplaceRow, "ActionTimelineReplace");
