// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AddonHudSizeRow);
impl AddonHudSizeRow {
    u16_field!(unknown_0, 2);
    u16_field!(unknown_1, 3);
    i16_field!(unknown_2, 0);
    i16_field!(unknown_3, 1);
}

define_sheet!(AddonHudSizeSheet, AddonHudSizeRow, "AddonHudSize");
