// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AdventureExPhaseRow);
impl AdventureExPhaseRow {
    u32_field!(quest, 0);
    u32_field!(adventure_begin, 1);
    u32_field!(adventure_end, 2);
    u32_field!(all_vistas_completed_screen_image, 3);
    u8_field!(expansion, 4);
}

define_sheet!(AdventureExPhaseSheet, AdventureExPhaseRow, "AdventureExPhase");
