// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AirshipExplorationLevelRow);
impl AirshipExplorationLevelRow {
    u32_field!(exp_to_next, 1);
    u16_field!(capacity, 0);
}

define_sheet!(AirshipExplorationLevelSheet, AirshipExplorationLevelRow, "AirshipExplorationLevel", no_language_support);
