// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AirshipExplorationPartRow);
impl AirshipExplorationPartRow {
    u16_field!(class, 8);
    i16_field!(surveillance, 3);
    i16_field!(retrieval, 4);
    i16_field!(speed, 5);
    i16_field!(range, 6);
    i16_field!(favor, 7);
    u8_field!(slot, 0);
    u8_field!(rank, 1);
    u8_field!(components, 2);
    u8_field!(repair_materials, 9);
}

define_sheet!(AirshipExplorationPartSheet, AirshipExplorationPartRow, "AirshipExplorationPart");
