// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AnimaWeapon5PatternGroupRow);
impl AnimaWeapon5PatternGroupRow {
    string_field!(name, 0);
}

define_sheet!(AnimaWeapon5PatternGroupSheet, AnimaWeapon5PatternGroupRow, "AnimaWeapon5PatternGroup", language_support);
