// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(AnimaWeapon5Parameter, 1);
impl<'a> AnimaWeapon5Parameter<'a> {
    i32_field!(field_0, 0);
}


define_row!(AnimaWeapon5Row);
impl AnimaWeapon5Row {
    i32_field!(item, 0);
    u8_field!(unknown_0, 1);
    u8_field!(secondary_stat_total, 2);
    array_field!(parameter, 3, 5, AnimaWeapon5Parameter);
}

define_sheet!(AnimaWeapon5Sheet, AnimaWeapon5Row, "AnimaWeapon5", no_language_support);
