// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(AnimaWeaponItemItem, 1);
impl<'a> AnimaWeaponItemItem<'a> {
    u32_field!(field_0, 0);
}


define_row!(AnimaWeaponItemRow);
impl AnimaWeaponItemRow {
    array_field!(item, 0, 14, AnimaWeaponItemItem);
}

define_sheet!(AnimaWeaponItemSheet, AnimaWeaponItemRow, "AnimaWeaponItem", no_language_support);
