// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AnimaWeapon5SpiritTalkRow);
impl AnimaWeapon5SpiritTalkRow {
    i32_field!(dialogue, 0);
}

define_sheet!(AnimaWeapon5SpiritTalkSheet, AnimaWeapon5SpiritTalkRow, "AnimaWeapon5SpiritTalk", no_language_support);
