// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AOZContentBriefingObjectRow);
impl AOZContentBriefingObjectRow {
    u32_field!(icon, 0);
    u16_field!(unknown_0, 1);
}

define_sheet!(AOZContentBriefingObjectSheet, AOZContentBriefingObjectRow, "AOZContentBriefingObject");
