// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AOZBossRow);
impl AOZBossRow {
    u16_field!(boss, 0);
    u16_field!(position, 1);
}

define_sheet!(AOZBossSheet, AOZBossRow, "AOZBoss");
