// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AOZReportRow);
impl AOZReportRow {
    u32_field!(unknown_0, 0);
    u8_field!(reward, 1);
    i8_field!(order, 2);
}

define_sheet!(AOZReportSheet, AOZReportRow, "AOZReport");
