// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AozActionRow);
impl AozActionRow {
    u32_field!(action, 0);
    u8_field!(rank, 1);
}

define_sheet!(AozActionSheet, AozActionRow, "AozAction", no_language_support);
