// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AOZContentBriefingBNpcRow);
impl AOZContentBriefingBNpcRow {
    u32_field!(b_npc_name, 0);
    u32_field!(target_small, 1);
    u32_field!(target_large, 2);
    u8_field!(endurance, 3);
    u8_field!(fire, 4);
    u8_field!(ice, 5);
    u8_field!(wind, 6);
    u8_field!(earth, 7);
    u8_field!(thunder, 8);
    u8_field!(water, 9);
    u8_field!(slashing, 10);
    u8_field!(piercing, 11);
    u8_field!(blunt, 12);
    u8_field!(magic, 13);
    bool_field!(hide_stats, 14);
    bool_field!(slow_vuln, 15);
    bool_field!(petrification_vuln, 16);
    bool_field!(paralysis_vuln, 17);
    bool_field!(interruption_vuln, 18);
    bool_field!(blind_vuln, 19);
    bool_field!(stun_vuln, 20);
    bool_field!(sleep_vuln, 21);
    bool_field!(bind_vuln, 22);
    bool_field!(heavy_vuln, 23);
    bool_field!(flat_or_death_vuln, 24);
}

define_sheet!(AOZContentBriefingBNpcSheet, AOZContentBriefingBNpcRow, "AOZContentBriefingBNpc");
