// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(AquariumFishRow);
impl AquariumFishRow {
    u32_field!(item, 2);
    u16_field!(unknown_0, 3);
    u8_field!(aquarium_water, 0);
    u8_field!(size, 1);
}

define_sheet!(AquariumFishSheet, AquariumFishRow, "AquariumFish");
