// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(ArrayEventHandlerData, 1);
impl<'a> ArrayEventHandlerData<'a> {
    u32_field!(field_0, 0);
}


define_row!(ArrayEventHandlerRow);
impl ArrayEventHandlerRow {
    array_field!(data, 0, 16, ArrayEventHandlerData);
}

define_sheet!(ArrayEventHandlerSheet, ArrayEventHandlerRow, "ArrayEventHandler", no_language_support);
