// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BNpcAnnounceIconRow);
impl BNpcAnnounceIconRow {
    u32_field!(icon, 0);
}

define_sheet!(BNpcAnnounceIconSheet, BNpcAnnounceIconRow, "BNpcAnnounceIcon");
