// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BNpcCustomizeRow);
impl BNpcCustomizeRow {
    u8_field!(race, 0);
    u8_field!(gender, 1);
    u8_field!(body_type, 2);
    u8_field!(height, 3);
    u8_field!(tribe, 4);
    u8_field!(face, 5);
    u8_field!(hair_style, 6);
    u8_field!(hair_highlight, 7);
    u8_field!(skin_color, 8);
    u8_field!(eye_heterochromia, 9);
    u8_field!(hair_color, 10);
    u8_field!(hair_highlight_color, 11);
    u8_field!(facial_feature, 12);
    u8_field!(facial_feature_color, 13);
    u8_field!(eyebrows, 14);
    u8_field!(eye_color, 15);
    u8_field!(eye_shape, 16);
    u8_field!(nose, 17);
    u8_field!(jaw, 18);
    u8_field!(mouth, 19);
    u8_field!(lip_color, 20);
    u8_field!(bust_or_tone_1, 21);
    u8_field!(extra_feature_1, 22);
    u8_field!(extra_feature_2_or_bust, 23);
    u8_field!(face_paint, 24);
    u8_field!(face_paint_color, 25);
}

define_sheet!(BNpcCustomizeSheet, BNpcCustomizeRow, "BNpcCustomize");
