// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BNpcBaseRow);
impl BNpcBaseRow {
    f32_field!(scale, 0);
    i32_field!(array_event_handler, 1);
    u16_field!(behavior, 2);
    u16_field!(model_chara, 3);
    u16_field!(b_npc_customize, 4);
    u16_field!(npc_equip, 5);
    u16_field!(special, 6);
    u16_field!(unknown_9, 7);
    u8_field!(battalion, 8);
    u8_field!(link_race, 9);
    u8_field!(rank, 10);
    u8_field!(se_pack, 11);
    u8_field!(unknown_0, 12);
    u8_field!(b_npc_parts, 13);
    u8_field!(unknown_1, 14);
    u8_field!(unknown_2, 15);
    u8_field!(unknown_3, 16);
    u8_field!(unknown_10, 17);
    u8_field!(unknown_4, 18);
    bool_field!(is_omnidirectional, 19);
    bool_field!(unknown_6, 20);
    bool_field!(is_target_line, 21);
    bool_field!(is_display_level, 22);
    bool_field!(unknown_7, 23);
    bool_field!(unknown_70, 24);
    bool_field!(unknown_8, 25);
}

define_sheet!(BNpcBaseSheet, BNpcBaseRow, "BNpcBase");
