// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BNpcStateRow);
impl BNpcStateRow {
    f32_field!(scale, 11);
    i32_field!(loop_timeline, 13);
    u16_field!(idle, 4);
    u8_field!(slot, 0);
    u8_field!(unknown_0, 3);
    u8_field!(attribute_0, 5);
    u8_field!(attribute_1, 7);
    u8_field!(attribute_2, 9);
    u8_field!(unknown_1, 12);
    i8_field!(over_ray, 1);
    i8_field!(unknown_2, 2);
    bool_field!(attribute_flag_0, 6);
    bool_field!(attribute_flag_1, 8);
    bool_field!(attribute_flag_2, 10);
    bool_field!(unknown_3, 14);
}

define_sheet!(BNpcStateSheet, BNpcStateRow, "BNpcState");
