// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BannerPresetRow);
impl BannerPresetRow {
    f32_field!(camera_position_x, 0);
    f32_field!(camera_position_y, 1);
    f32_field!(camera_position_z, 2);
    f32_field!(camera_target_x, 3);
    f32_field!(camera_target_y, 4);
    f32_field!(camera_target_z, 5);
    f32_field!(animation_progress, 6);
    f32_field!(head_direction_x, 7);
    f32_field!(head_direction_y, 8);
    f32_field!(eye_direction_x, 9);
    f32_field!(eye_direction_y, 10);
    i32_field!(expression, 11);
    u16_field!(banner_timeline, 12);
    i16_field!(image_rotation, 13);
    i16_field!(directional_lighting_vertical_angle, 14);
    i16_field!(directional_lighting_horizontal_angle, 15);
    u8_field!(camera_zoom, 16);
    u8_field!(banner_design_preset, 17);
    u8_field!(directional_lighting_color_red, 18);
    u8_field!(directional_lighting_color_green, 19);
    u8_field!(directional_lighting_color_blue, 20);
    u8_field!(directional_lighting_brightness, 21);
    u8_field!(ambient_lighting_color_red, 22);
    u8_field!(ambient_lighting_color_green, 23);
    u8_field!(ambient_lighting_color_blue, 24);
    u8_field!(ambient_lighting_brightness, 25);
}

define_sheet!(BannerPresetSheet, BannerPresetRow, "BannerPreset");
