// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BannerFacialRow);
impl BannerFacialRow {
    u16_field!(emote, 0);
    u16_field!(unlock_condition, 1);
    u16_field!(unknown_70_1, 2);
    u16_field!(unknown_70_2, 3);
    u16_field!(unknown_0, 4);
    u8_field!(sort_key, 5);
}

define_sheet!(BannerFacialSheet, BannerFacialRow, "BannerFacial");
