// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BannerDesignPresetRow);
impl BannerDesignPresetRow {
    string_field!(name, 0);
    u16_field!(background, 1);
    u16_field!(frame, 2);
    u16_field!(decoration, 3);
    u16_field!(sort_key, 4);
}

define_sheet!(BannerDesignPresetSheet, BannerDesignPresetRow, "BannerDesignPreset");
