// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BannerTimelineRow);
impl BannerTimelineRow {
    string_field!(name, 10);
    u32_field!(additional_data, 1);
    i32_field!(icon, 9);
    u16_field!(unlock_condition, 4);
    u16_field!(unknown_70_1, 5);
    u16_field!(unknown_70_2, 6);
    u16_field!(unknown_0, 7);
    u16_field!(sort_key, 8);
    u8_field!(type_, 0);
    u8_field!(accept_class_job_category, 2);
    u8_field!(category, 3);
}

define_sheet!(BannerTimelineSheet, BannerTimelineRow, "BannerTimeline", language_support);
