// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BehaviorPathRow);
impl BehaviorPathRow {
    f32_field!(speed, 5);
    bool_field!(is_turn_transition, 0);
    bool_field!(is_fade_out, 1);
    bool_field!(is_fade_in, 2);
    bool_field!(is_walking, 3);
    bool_field!(unknown_0, 4);
}

define_sheet!(BehaviorPathSheet, BehaviorPathRow, "BehaviorPath");
