// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BGMSwitchRow);
impl BGMSwitchRow {
    u32_field!(quest, 1);
    u16_field!(bgm, 3);
    u8_field!(bgm_system_define, 0);
    u8_field!(unknown_0, 2);
}

define_sheet!(BGMSwitchSheet, BGMSwitchRow, "BGMSwitch");
