// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BGMFadeRow);
impl BGMFadeRow {
    i32_field!(scene_out, 0);
    i32_field!(scene_in, 1);
    i32_field!(bgm_fade_type, 2);
}

define_sheet!(BGMFadeSheet, BGMFadeRow, "BGMFade", no_language_support);
