// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BoosterRow);
impl BoosterRow {
    u32_field!(unknown_0, 1);
    u16_field!(unknown_1, 3);
    u8_field!(unknown_2, 0);
    u8_field!(unknown_3, 2);
    bool_field!(unknown_70, 4);
}

define_sheet!(BoosterSheet, BoosterRow, "Booster", no_language_support);
