// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BuddySkillRow);
impl BuddySkillRow {
    u16_field!(defender, 2);
    u16_field!(attacker, 3);
    u16_field!(healer, 4);
    u8_field!(buddy_level, 0);
    bool_field!(is_active, 1);
}

define_sheet!(BuddySkillSheet, BuddySkillRow, "BuddySkill");
