// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(BuddyItemRow);
impl BuddyItemRow {
    u16_field!(item, 0);
    u8_field!(status, 1);
    bool_field!(use_field, 2);
    bool_field!(use_training, 3);
    bool_field!(unknown_0, 4);
}

define_sheet!(BuddyItemSheet, BuddyItemRow, "BuddyItem");
