// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CabinetRow);
impl CabinetRow {
    u32_field!(item, 0);
    u16_field!(order, 1);
    u8_field!(category, 2);
    u8_field!(sub_category, 3);
}

define_sheet!(CabinetSheet, CabinetRow, "Cabinet");
