// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(CharaMakeTypeCharaMakeStruct, 10);
impl<'a> CharaMakeTypeCharaMakeStruct<'a> {
    u32_field!(menu, 3);
    u32_field!(sub_menu_mask, 143);
    u32_field!(customize, 171);
    array_field!(sub_menu_param, 3, 100, CharaMakeTypeCharaMakeStruct);
    array_field!(unknown_0, 103, 6, CharaMakeTypeCharaMakeStruct);
    u8_field!(init_val, 31);
    u8_field!(sub_menu_type, 59);
    u8_field!(sub_menu_num, 87);
    u8_field!(look_at, 115);
    array_field!(sub_menu_graphic, 113, 10, CharaMakeTypeCharaMakeStruct);
}

define_subrow!(CharaMakeTypeCharaMakeStructSubMenuParam, 1);
impl<'a> CharaMakeTypeCharaMakeStructSubMenuParam<'a> {
    u32_field!(field_0, 3);
}

define_subrow!(CharaMakeTypeCharaMakeStructUnknown0, 1);
impl<'a> CharaMakeTypeCharaMakeStructUnknown0<'a> {
    u32_field!(field_0, 3);
}

define_subrow!(CharaMakeTypeCharaMakeStructSubMenuGraphic, 1);
impl<'a> CharaMakeTypeCharaMakeStructSubMenuGraphic<'a> {
    u32_field!(field_0, 3);
}

define_subrow!(CharaMakeTypeVoiceStruct, 1);
impl<'a> CharaMakeTypeVoiceStruct<'a> {
    u32_field!(field_0, 3);
}

define_subrow!(CharaMakeTypeFacialFeatureOption, 7);
impl<'a> CharaMakeTypeFacialFeatureOption<'a> {
    u32_field!(option_1, 3);
    u32_field!(option_2, 143);
    u32_field!(option_3, 171);
    u32_field!(option_4, 199);
    u32_field!(option_5, 227);
    u32_field!(option_6, 255);
    u32_field!(option_7, 283);
}

define_subrow!(CharaMakeTypeEquipment, 7);
impl<'a> CharaMakeTypeEquipment<'a> {
    u32_field!(helmet, 3);
    u32_field!(top, 143);
    u32_field!(gloves, 171);
    u32_field!(legs, 199);
    u32_field!(shoes, 227);
    u32_field!(weapon, 255);
    u32_field!(sub_weapon, 283);
}


define_row!(CharaMakeTypeRow);
impl CharaMakeTypeRow {
    array_field!(chara_make_struct, 0, 28, CharaMakeTypeCharaMakeStruct);
    array_field!(voice_struct, 3444, 12, CharaMakeTypeVoiceStruct);
    array_field!(facial_feature_option, 3456, 8, CharaMakeTypeFacialFeatureOption);
    array_field!(equipment, 3512, 3, CharaMakeTypeEquipment);
    i32_field!(race, 0);
    i32_field!(tribe, 1);
    i8_field!(gender, 2);
}

define_sheet!(CharaMakeTypeSheet, CharaMakeTypeRow, "CharaMakeType");
