// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CharaCardPlayStyleRow);
impl CharaCardPlayStyleRow {
    string_field!(name, 2);
    i32_field!(icon, 0);
    u8_field!(sort_key, 1);
}

define_sheet!(CharaCardPlayStyleSheet, CharaCardPlayStyleRow, "CharaCardPlayStyle", language_support);
