// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CharaMakeNameRow);
impl CharaMakeNameRow {
    string_field!(hyur_midlander_male, 0);
    string_field!(hyur_midlander_female, 1);
    string_field!(hyur_midlander_last_name, 2);
    string_field!(hyur_highlander_male, 3);
    string_field!(hyur_highlander_female, 4);
    string_field!(hyur_highlander_last_name, 5);
    string_field!(elezen_male, 6);
    string_field!(elezen_female, 7);
    string_field!(elezen_wildwood_last_name, 8);
    string_field!(elezen_duskwight_last_name, 9);
    string_field!(miqote_sun_male, 10);
    string_field!(miqote_sun_female, 11);
    string_field!(miqote_sun_male_last_name, 12);
    string_field!(miqote_sun_female_last_name, 13);
    string_field!(miqote_moon_male, 14);
    string_field!(miqote_moon_female, 15);
    string_field!(miqote_moon_lastname, 16);
    string_field!(lalafell_plainsfolk_first_name_start, 17);
    string_field!(lalafell_plainsfolk_last_name_start, 18);
    string_field!(lalafell_plainsfolk_end_of_names, 19);
    string_field!(lalafell_dunesfolk_male, 20);
    string_field!(lalafell_dunesfolk_male_last_name, 21);
    string_field!(lalafell_dunesfolk_female, 22);
    string_field!(lalafell_dunesfolk_female_last_name, 23);
    string_field!(roegadyn_sea_wolf_male, 24);
    string_field!(roegadyn_sea_wolf_male_last_name, 25);
    string_field!(roegadyn_sea_wolf_female, 26);
    string_field!(roegadyn_sea_wolf_female_last_name, 27);
    string_field!(roegadyn_hellsguard_first_name, 28);
    string_field!(roegadyn_hellsguard_male_last_name, 29);
    string_field!(roegadyn_hellsguard_female_last_name, 30);
    string_field!(au_ra_raen_male, 31);
    string_field!(au_ra_raen_female, 32);
    string_field!(au_ra_raen_last_name, 33);
    string_field!(au_ra_xaela_male, 34);
    string_field!(au_ra_xaela_female, 35);
    string_field!(au_ra_xaela_last_name, 36);
    string_field!(hrothgar_hellions_first_name, 37);
    string_field!(hrothgar_hellions_last_name, 38);
    string_field!(hrothgar_lost_first_name, 39);
    string_field!(hrothgar_lost_last_name, 40);
    string_field!(unknown_0, 41);
    string_field!(unknown_1, 42);
    string_field!(unknown_2, 43);
    string_field!(viera_first_name, 44);
    string_field!(viera_rava_last_name, 45);
    string_field!(viera_veena_last_name, 46);
    string_field!(unknown_70_1, 47);
    string_field!(unknown_70_2, 48);
    string_field!(unknown_70_3, 49);
}

define_sheet!(CharaMakeNameSheet, CharaMakeNameRow, "CharaMakeName");
