// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CharaCardDesignCategoryRow);
impl CharaCardDesignCategoryRow {
    string_field!(name, 1);
    u8_field!(sort_key, 0);
}

define_sheet!(CharaCardDesignCategorySheet, CharaCardDesignCategoryRow, "CharaCardDesignCategory", language_support);
