// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CharaMakeClassEquipRow);
impl CharaMakeClassEquipRow {
    u64_field!(helmet, 0);
    u64_field!(top, 1);
    u64_field!(glove, 2);
    u64_field!(down, 3);
    u64_field!(shoes, 4);
    u64_field!(weapon, 5);
    u64_field!(sub_weapon, 6);
    i32_field!(class, 7);
}

define_sheet!(CharaMakeClassEquipSheet, CharaMakeClassEquipRow, "CharaMakeClassEquip");
