// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CharaMakeCustomizeRow);
impl CharaMakeCustomizeRow {
    u32_field!(icon, 0);
    u32_field!(hint, 1);
    u32_field!(hint_item, 2);
    u16_field!(unlock_link, 3);
    u8_field!(feature_id, 4);
    u8_field!(unknown_0, 5);
    bool_field!(is_purchasable, 6);
}

define_sheet!(CharaMakeCustomizeSheet, CharaMakeCustomizeRow, "CharaMakeCustomize");
