// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ChocoboRaceTerritoryRow);
impl ChocoboRaceTerritoryRow {
    i32_field!(icon, 1);
    u16_field!(name, 0);
}

define_sheet!(ChocoboRaceTerritorySheet, ChocoboRaceTerritoryRow, "ChocoboRaceTerritory", no_language_support);
