// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(ChocoboTaxiStandTargetLocations, 1);
impl<'a> ChocoboTaxiStandTargetLocations<'a> {
    string_field!(field_0, 0);
}


define_row!(ChocoboTaxiStandRow);
impl ChocoboTaxiStandRow {
    string_field!(place_name, 0);
    array_field!(target_locations, 1, 8, ChocoboTaxiStandTargetLocations);
}

define_sheet!(ChocoboTaxiStandSheet, ChocoboTaxiStandRow, "ChocoboTaxiStand");
