// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ChocoboRaceWeatherRow);
impl ChocoboRaceWeatherRow {
    i32_field!(weather_type_1, 0);
    i32_field!(weather_type_2, 1);
}

define_sheet!(ChocoboRaceWeatherSheet, ChocoboRaceWeatherRow, "ChocoboRaceWeather", no_language_support);
