// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ChocoboRaceAbilityRow);
impl ChocoboRaceAbilityRow {
    string_field!(name, 0);
    string_field!(description, 1);
    u32_field!(icon, 2);
    u8_field!(value, 4);
    i8_field!(chocobo_race_ability_type, 3);
}

define_sheet!(ChocoboRaceAbilitySheet, ChocoboRaceAbilityRow, "ChocoboRaceAbility", language_support);
