// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ChocoboRaceItemRow);
impl ChocoboRaceItemRow {
    string_field!(name, 0);
    string_field!(description, 1);
    u32_field!(icon, 2);
}

define_sheet!(ChocoboRaceItemSheet, ChocoboRaceItemRow, "ChocoboRaceItem");
