// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ChocoboTaxiRow);
impl ChocoboTaxiRow {
    u32_field!(location, 0);
    u16_field!(fare, 1);
    u16_field!(unknown_0, 2);
    // In minutes.
    u8_field!(time_required, 3);
    bool_field!(unknown_1, 4);
}

define_sheet!(ChocoboTaxiSheet, ChocoboTaxiRow, "ChocoboTaxi");
