// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ChocoboRaceStatusRow);
impl ChocoboRaceStatusRow {
    i32_field!(status, 0);
    u16_field!(unknown_0, 1);
}

define_sheet!(ChocoboRaceStatusSheet, ChocoboRaceStatusRow, "ChocoboRaceStatus");
