// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ClassJobRow);
impl ClassJobRow {
    string_field!(name, 0);
    string_field!(abbreviation, 1);
    string_field!(name_female, 2);
    bool_field!(can_queue_for_duty, 50);
    string_field!(name_english, 30);
    u32_field!(item_soul_crystal, 41);
    u32_field!(unlock_quest, 42);
    u32_field!(relic_quest, 43);
    u32_field!(prerequisite, 44);
    i32_field!(unknown_70_1, 23);
    i32_field!(unknown_70_2, 24);
    i32_field!(unknown_9, 25);
    i32_field!(item_starting_weapon_main_hand, 31);
    i32_field!(item_starting_weapon_off_hand, 32);
    u16_field!(modifier_hit_points, 9);
    u16_field!(modifier_mana_points, 10);
    u16_field!(modifier_strength, 11);
    u16_field!(modifier_vitality, 12);
    u16_field!(modifier_dexterity, 13);
    u16_field!(modifier_intelligence, 14);
    u16_field!(modifier_mind, 15);
    u16_field!(modifier_piety, 16);
    u16_field!(unknown_2, 17);
    u16_field!(unknown_3, 18);
    u16_field!(unknown_4, 19);
    u16_field!(unknown_5, 20);
    u16_field!(unknown_6, 21);
    u16_field!(unknown_7, 22);
    u16_field!(limit_break_1, 37);
    u16_field!(limit_break_2, 38);
    u16_field!(limit_break_3, 39);
    u8_field!(class_job_category, 3);
    u8_field!(unknown_8, 6);
    u8_field!(job_index, 7);
    u8_field!(pv_p_base_param_value, 26);
    u8_field!(pv_p_action_sort_row, 27);
    u8_field!(pv_p_initial_select_action_trait, 28);
    u8_field!(class_job_parent, 29);
    u8_field!(role, 33);
    u8_field!(starting_town, 34);
    u8_field!(primary_stat, 36);
    u8_field!(ui_priority, 40);
    u8_field!(starting_level, 45);
    u8_field!(party_bonus, 46);
    // 1 &#x3D; Tank
    // 2 &#x3D; Pure Healer
    // 3 &#x3D; Melee
    // 4 &#x3D; Physical Ranged
    // 5 &#x3D; Magical Ranged
    // 6 &#x3D; Barrier Healer
    u8_field!(job_type, 47);
    i8_field!(exp_array_index, 4);
    i8_field!(battle_class_index, 5);
    i8_field!(doh_dol_job_index, 8);
    i8_field!(monster_note, 35);
    bool_field!(is_limited_job, 48);
    bool_field!(unknown_10, 49);
}

define_sheet!(ClassJobSheet, ClassJobRow, "ClassJob", language_support);
