// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CollectablesRefineRow);
impl CollectablesRefineRow {
    u16_field!(collectability_low, 0);
    u16_field!(collectability_mid, 1);
    u16_field!(collectability_high, 2);
}

define_sheet!(CollectablesRefineSheet, CollectablesRefineRow, "CollectablesRefine");
