// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(CollectablesShopShopItems, 1);
impl<'a> CollectablesShopShopItems<'a> {
    string_field!(field_0, 0);
}


define_row!(CollectablesShopRow);
impl CollectablesShopRow {
    string_field!(name, 0);
    u32_field!(quest, 1);
    array_field!(shop_items, 2, 11, CollectablesShopShopItems);
    u8_field!(reward_type, 2);
}

define_sheet!(CollectablesShopSheet, CollectablesShopRow, "CollectablesShop", language_support);
