// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CollectablesShopRewardScripRow);
impl CollectablesShopRewardScripRow {
    u16_field!(currency, 0);
    u16_field!(low_reward, 1);
    u16_field!(mid_reward, 2);
    u16_field!(high_reward, 3);
    u16_field!(exp_ratio_low, 4);
    u16_field!(exp_ratio_mid, 5);
    u16_field!(exp_ratio_high, 6);
}

define_sheet!(CollectablesShopRewardScripSheet, CollectablesShopRewardScripRow, "CollectablesShopRewardScrip", no_language_support);
