// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ColorFilterRow);
impl ColorFilterRow {
    string_field!(unknown_0, 0);
    f32_field!(unknown_1, 2);
    f32_field!(unknown_2, 3);
    f32_field!(unknown_3, 5);
    f32_field!(unknown_4, 6);
    f32_field!(unknown_5, 7);
    f32_field!(unknown_6, 8);
    f32_field!(unknown_7, 9);
    f32_field!(unknown_8, 10);
    f32_field!(unknown_9, 11);
    f32_field!(unknown_10, 12);
    f32_field!(unknown_11, 13);
    f32_field!(unknown_12, 14);
    f32_field!(unknown_13, 15);
    u8_field!(unknown_14, 1);
    bool_field!(unknown_15, 4);
}

define_sheet!(ColorFilterSheet, ColorFilterRow, "ColorFilter");
