// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ColosseumMatchRankRow);
impl ColosseumMatchRankRow {
    string_field!(unknown_0, 0);
}

define_sheet!(ColosseumMatchRankSheet, ColosseumMatchRankRow, "ColosseumMatchRank", language_support);
