// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CompanyCraftSupplyItemRow);
impl CompanyCraftSupplyItemRow {
    u32_field!(item, 0);
}

define_sheet!(CompanyCraftSupplyItemSheet, CompanyCraftSupplyItemRow, "CompanyCraftSupplyItem");
