// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(CompanyCraftProcessSupplyItem, 1);
impl<'a> CompanyCraftProcessSupplyItem<'a> {
    u16_field!(field_0, 0);
}

define_subrow!(CompanyCraftProcessSetQuantity, 1);
impl<'a> CompanyCraftProcessSetQuantity<'a> {
    u16_field!(field_0, 0);
}

define_subrow!(CompanyCraftProcessSetsRequired, 1);
impl<'a> CompanyCraftProcessSetsRequired<'a> {
    u16_field!(field_0, 0);
}


define_row!(CompanyCraftProcessRow);
impl CompanyCraftProcessRow {
    array_field!(supply_item, 0, 12, CompanyCraftProcessSupplyItem);
    array_field!(set_quantity, 12, 12, CompanyCraftProcessSetQuantity);
    array_field!(sets_required, 24, 12, CompanyCraftProcessSetsRequired);
}

define_sheet!(CompanyCraftProcessSheet, CompanyCraftProcessRow, "CompanyCraftProcess", no_language_support);
