// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CompanyLeveRuleRow);
impl CompanyLeveRuleRow {
    string_field!(type_, 0);
    u16_field!(objective, 1);
    u16_field!(help, 2);
}

define_sheet!(CompanyLeveRuleSheet, CompanyLeveRuleRow, "CompanyLeveRule");
