// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ConditionRow);
impl ConditionRow {
    u32_field!(log_message, 2);
    u8_field!(permission, 1);
    // The lower this number is, the higher the priority. Used to determine which conditions LogMessage should be printed.
    u8_field!(log_message_priority, 3);
    // Allows this Condition to be set by a packet received from the server.
    bool_field!(is_networked, 0);
}

define_sheet!(ConditionSheet, ConditionRow, "Condition", no_language_support);
