// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ContentRouletteRoleBonusRow);
impl ContentRouletteRoleBonusRow {
    u32_field!(item_reward_type, 0);
    u32_field!(unknown_0, 1);
    u16_field!(unknown_1, 2);
    u16_field!(unknown_2, 3);
    u16_field!(unknown_3, 4);
    u16_field!(unknown_4, 5);
    u16_field!(unknown_5, 6);
    u16_field!(unknown_6, 7);
    u8_field!(reward_amount, 8);
    u8_field!(unknown_7, 9);
    u8_field!(unknown_8, 10);
    u8_field!(unknown_9, 11);
}

define_sheet!(ContentRouletteRoleBonusSheet, ContentRouletteRoleBonusRow, "ContentRouletteRoleBonus");
