// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ContentTodoRow);
impl ContentTodoRow {
    u32_field!(unknown_0, 0);
    u8_field!(text, 1);
    u8_field!(unknown_2, 2);
    u8_field!(unknown_3, 3);
    bool_field!(unknown_4, 4);
}

define_sheet!(ContentTodoSheet, ContentTodoRow, "ContentTodo");
