// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ContentGaugeRow);
impl ContentGaugeRow {
    string_field!(name, 0);
    string_field!(text_string, 1);
    i16_field!(unknown_0, 2);
    i16_field!(unknown_1, 3);
    i16_field!(unknown_2, 4);
    u8_field!(unknown_3, 5);
    u8_field!(color, 6);
    u8_field!(unknown_4, 7);
    u8_field!(unknown_5, 8);
    i8_field!(unknown_6, 9);
    i8_field!(unknown_7, 10);
    bool_field!(unknown_8, 11);
}

define_sheet!(ContentGaugeSheet, ContentGaugeRow, "ContentGauge");
