// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ContentTourismConstructRow);
impl ContentTourismConstructRow {
    u32_field!(unknown_0, 0);
    u32_field!(unknown_1, 1);
    u32_field!(unknown_2, 2);
    u32_field!(unknown_3, 3);
    u32_field!(unknown_4, 4);
    u32_field!(unknown_5, 5);
    u32_field!(unknown_6, 6);
    u32_field!(unknown_7, 7);
    u32_field!(unknown_8, 8);
    u32_field!(unknown_9, 9);
    u32_field!(unknown_10, 10);
    u32_field!(unknown_11, 11);
    u32_field!(unknown_12, 12);
    u8_field!(unknown_13, 13);
}

define_sheet!(ContentTourismConstructSheet, ContentTourismConstructRow, "ContentTourismConstruct");
