// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ContentNpcRow);
impl ContentNpcRow {
    bool_field!(unknown_0, 0);
    bool_field!(unknown_1, 1);
}

define_sheet!(ContentNpcSheet, ContentNpcRow, "ContentNpc", no_language_support);
