// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ContentsTutorialPageRow);
impl ContentsTutorialPageRow {
    string_field!(description, 1);
    i32_field!(image, 0);
}

define_sheet!(ContentsTutorialPageSheet, ContentsTutorialPageRow, "ContentsTutorialPage", language_support);
