// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ContentRouletteRow);
impl ContentRouletteRow {
    string_field!(name, 0);
    string_field!(category, 1);
    string_field!(unknown_0, 2);
    string_field!(description, 3);
    string_field!(duty_type, 4);
    // This would show Addon#102618, but the row is empty.
    u32_field!(unknown_1, 5);
    u32_field!(image, 6);
    u32_field!(unknown_2, 7);
    u32_field!(unknown_3, 8);
    i32_field!(unknown_6, 9);
    u16_field!(item_level_required, 10);
    u16_field!(item_level_sync, 11);
    u16_field!(reward_tome_a, 12);
    u16_field!(reward_tome_b, 13);
    u16_field!(reward_tome_c, 14);
    u16_field!(unknown_5, 15);
    u16_field!(instance_content, 16);
    u8_field!(required_ex_version, 17);
    u8_field!(open_rule, 18);
    u8_field!(required_level, 19);
    u8_field!(synced_from_level, 20);
    u8_field!(content_roulette_role_bonus, 21);
    u8_field!(sort_key, 22);
    u8_field!(class_job_category, 23);
    u8_field!(content_member_type, 24);
    u8_field!(unknown_9, 25);
    u8_field!(queue_max_players, 26);
    u8_field!(content_type, 27);
    u8_field!(unknown_12, 28);
    // In minutes.
    u8_field!(time_limit, 29);
    // In minutes. If 0, only TimeLimit is displayed.
    u8_field!(time_limit_max, 30);
    u8_field!(loot_mode_type, 31);
    u8_field!(unknown_15, 32);
    // Index in PlayerState.PenaltyTimestamps
    u8_field!(penalty_timestamp_array_index, 33);
    // Index in PlayerState.ContentRouletteCompletion
    i8_field!(completion_array_index, 34);
    bool_field!(is_gold_saucer, 35);
    bool_field!(is_in_duty_finder, 36);
    bool_field!(is_pv_p, 37);
    // Displays Addon#2828.
    bool_field!(applies_highest_average_duty_item_level, 38);
    bool_field!(unknown_18, 39);
    bool_field!(allow_consumable_items, 40);
    bool_field!(allow_phoenix_down, 41);
    bool_field!(allow_replacement, 42);
    bool_field!(rated_match, 43);
    bool_field!(rated, 44);
    // This would show Addon#10833, but the row does not exist.
    bool_field!(unknown_22, 45);
    bool_field!(unknown_23, 46);
    bool_field!(unknown_24, 47);
    bool_field!(is_registration_allowed_from_any_data_center, 48);
}

define_sheet!(ContentRouletteSheet, ContentRouletteRow, "ContentRoulette");
