// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ContentDirectorBattleTalkRow);
impl ContentDirectorBattleTalkRow {
    u32_field!(unknown_0, 3);
    u32_field!(unknown_1, 4);
    u16_field!(text, 0);
    u8_field!(unknown_3, 1);
    u8_field!(unknown_4, 2);
}

define_sheet!(ContentDirectorBattleTalkSheet, ContentDirectorBattleTalkRow, "ContentDirectorBattleTalk");
