// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ContentTalkRow);
impl ContentTalkRow {
    string_field!(text, 0);
    u8_field!(content_talk_param, 1);
}

define_sheet!(ContentTalkSheet, ContentTalkRow, "ContentTalk");
