// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ContentRouletteOpenRuleRow);
impl ContentRouletteOpenRuleRow {
    u32_field!(type_, 0);
    bool_field!(has_duty_requirements, 1);
}

define_sheet!(ContentRouletteOpenRuleSheet, ContentRouletteOpenRuleRow, "ContentRouletteOpenRule");
