// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ContentsNoteRow);
impl ContentsNoteRow {
    string_field!(name, 0);
    string_field!(description, 1);
    u32_field!(req_unlock, 2);
    i32_field!(icon, 3);
    i32_field!(required_amount, 4);
    i32_field!(exp_multiplier, 5);
    i32_field!(gil_rward, 6);
    i32_field!(exp_cap, 7);
    u16_field!(level_unlock, 8);
    u16_field!(how_to, 9);
    u8_field!(content_type, 10);
    u8_field!(menu_order, 11);
    u8_field!(reward_0, 12);
    u8_field!(reward_1, 13);
}

define_sheet!(ContentsNoteSheet, ContentsNoteRow, "ContentsNote");
