// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(CraftLeveItem, 1);
impl<'a> CraftLeveItem<'a> {
    i32_field!(field_0, 0);
}

define_subrow!(CraftLeveItemCount, 1);
impl<'a> CraftLeveItemCount<'a> {
    i32_field!(field_0, 0);
}


define_row!(CraftLeveRow);
impl CraftLeveRow {
    i32_field!(leve, 0);
    i32_field!(craft_leve_talk, 1);
    array_field!(item, 2, 4, CraftLeveItem);
    array_field!(item_count, 6, 4, CraftLeveItemCount);
    u8_field!(repeats, 10);
}

define_sheet!(CraftLeveSheet, CraftLeveRow, "CraftLeve");
