// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CraftActionRow);
impl CraftActionRow {
    string_field!(name, 0);
    string_field!(description, 1);
    u32_field!(quest_requirement, 2);
    i32_field!(crp, 3);
    i32_field!(bsm, 4);
    i32_field!(arm, 5);
    i32_field!(gsm, 6);
    i32_field!(ltw, 7);
    i32_field!(wvr, 8);
    i32_field!(alc, 9);
    i32_field!(cul, 10);
    u16_field!(animation_start, 11);
    u16_field!(animation_end, 12);
    u16_field!(icon, 13);
    u16_field!(required_status, 14);
    u8_field!(class_job_category, 15);
    u8_field!(class_job_level, 16);
    u8_field!(cost, 17);
    i8_field!(class_job, 18);
    bool_field!(specialist, 19);
}

define_sheet!(CraftActionSheet, CraftActionRow, "CraftAction");
