// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CraftTypeRow);
impl CraftTypeRow {
    string_field!(name, 0);
    u8_field!(main_physical, 1);
    u8_field!(sub_physical, 2);
}

define_sheet!(CraftTypeSheet, CraftTypeRow, "CraftType");
