// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CreditListRow);
impl CreditListRow {
    u32_field!(icon, 1);
    u32_field!(font, 2);
    u32_field!(cast, 5);
    u16_field!(scale, 0);
    u8_field!(unknown_0, 3);
    u8_field!(unknown_1, 4);
}

define_sheet!(CreditListSheet, CreditListRow, "CreditList", no_language_support);
