// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CreditFontRow);
impl CreditFontRow {
    u8_field!(unknown_0, 0);
    u8_field!(unknown_1, 1);
    u8_field!(unknown_2, 2);
    u8_field!(unknown_3, 3);
    u8_field!(unknown_4, 4);
    u8_field!(unknown_5, 5);
    u8_field!(unknown_6, 6);
    u8_field!(unknown_7, 7);
    i8_field!(unknown_8, 8);
}

define_sheet!(CreditFontSheet, CreditFontRow, "CreditFont", no_language_support);
