// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CSBonusSeasonRow);
impl CSBonusSeasonRow {
    u32_field!(item, 5);
    u16_field!(unknown_1, 1);
    u16_field!(unknown_2, 2);
    u16_field!(category_0, 6);
    u16_field!(category_1, 7);
    u16_field!(category_2, 8);
    u16_field!(category_3, 9);
    u8_field!(text_0, 10);
    u8_field!(text_1, 11);
    u8_field!(unknown_12, 12);
    bool_field!(unknown_3, 3);
    bool_field!(unknown_4, 4);
    bool_field!(unknown_0, 0);
}

define_sheet!(CSBonusSeasonSheet, CSBonusSeasonRow, "CSBonusSeason", no_language_support);
