// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CSBonusSeasonRow);
impl CSBonusSeasonRow {
    u32_field!(item, 0);
    u16_field!(unknown_1, 1);
    u16_field!(unknown_2, 2);
    u16_field!(category_0, 3);
    u16_field!(category_1, 4);
    u16_field!(category_2, 5);
    u16_field!(category_3, 6);
    u8_field!(text_0, 7);
    u8_field!(text_1, 8);
    u8_field!(unknown_12, 9);
    bool_field!(unknown_3, 10);
    bool_field!(unknown_4, 11);
    bool_field!(unknown_0, 12);
}

define_sheet!(CSBonusSeasonSheet, CSBonusSeasonRow, "CSBonusSeason");
