// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CSBonusContentIdentifierRow);
impl CSBonusContentIdentifierRow {
    u32_field!(content, 0);
    u32_field!(unlock_quest_0, 1);
    u32_field!(unlock_quest_1, 2);
    u32_field!(unlock_quest_2, 3);
    u32_field!(unknown_6, 4);
    u32_field!(map, 5);
    u8_field!(content_link_type, 6);
    bool_field!(unknown_2, 7);
}

define_sheet!(CSBonusContentIdentifierSheet, CSBonusContentIdentifierRow, "CSBonusContentIdentifier");
