// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CustomTalkNestHandlersRow);
impl CustomTalkNestHandlersRow {
    u32_field!(nest_handler, 0);
}

define_sheet!(CustomTalkNestHandlersSheet, CustomTalkNestHandlersRow, "CustomTalkNestHandlers", no_language_support);
