// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CutSceneIncompQuestRow);
impl CutSceneIncompQuestRow {
    u32_field!(quest, 0);
}

define_sheet!(CutSceneIncompQuestSheet, CutSceneIncompQuestRow, "CutSceneIncompQuest", no_language_support);
