// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(CuttingGrassRow);
impl CuttingGrassRow {
    string_field!(unknown_0, 0);
    u32_field!(unknown_1, 1);
    u32_field!(unknown_2, 3);
    u32_field!(unknown_3, 4);
    u32_field!(unknown_4, 5);
    u32_field!(unknown_5, 6);
    u32_field!(unknown_6, 7);
    u32_field!(unknown_7, 8);
    u32_field!(unknown_8, 9);
    u32_field!(unknown_9, 10);
    i32_field!(unknown_10, 2);
}

define_sheet!(CuttingGrassSheet, CuttingGrassRow, "CuttingGrass");
