// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(DailySupplyItemItem, 1);
impl<'a> DailySupplyItemItem<'a> {
    i32_field!(field_0, 0);
}

define_element!(DailySupplyItemQuantity, 1);
impl<'a> DailySupplyItemQuantity<'a> {
    i32_field!(field_0, 0);
}

define_element!(DailySupplyItemRecipeLevel, 1);
impl<'a> DailySupplyItemRecipeLevel<'a> {
    i32_field!(field_0, 0);
}


define_row!(DailySupplyItemRow);
impl DailySupplyItemRow {
    array_field!(item, 0, 8, DailySupplyItemItem);
    array_field!(quantity, 8, 8, DailySupplyItemQuantity);
    array_field!(recipe_level, 16, 8, DailySupplyItemRecipeLevel);
}

define_sheet!(DailySupplyItemSheet, DailySupplyItemRow, "DailySupplyItem", no_language_support);
