// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DawnContentRow);
impl DawnContentRow {
    u32_field!(content, 0);
    u32_field!(exp_below_ex_max_lvl, 1);
    u32_field!(exp_above_ex_max_lvl, 2);
    u32_field!(unknown_0, 3);
    u32_field!(unknown_1, 4);
    u32_field!(unknown_2, 5);
    u32_field!(unknown_3, 6);
    u32_field!(unknown_4, 7);
    u32_field!(unknown_5, 8);
    u32_field!(unknown_6, 9);
    u32_field!(unknown_7, 10);
    u32_field!(unknown_8, 11);
    u32_field!(unknown_9, 12);
    u32_field!(unknown_10, 13);
    u16_field!(unknown_15, 14);
    u8_field!(unknown_11, 15);
    bool_field!(unknown_12, 16);
    bool_field!(unknown_16, 17);
    bool_field!(unknown_13, 18);
    bool_field!(unknown_14, 19);
}

define_sheet!(DawnContentSheet, DawnContentRow, "DawnContent");
