// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DawnMemberRow);
impl DawnMemberRow {
    u8_field!(unknown_0, 0);
    u8_field!(unknown_1, 1);
}

define_sheet!(DawnMemberSheet, DawnMemberRow, "DawnMember");
