// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DawnMemberUIParamRow);
impl DawnMemberUIParamRow {
    string_field!(unknown_0, 1);
    string_field!(class_plural, 3);
    u32_field!(voice_line, 2);
    string_field!(class_singular, 0);
}

define_sheet!(DawnMemberUIParamSheet, DawnMemberUIParamRow, "DawnMemberUIParam");
