// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DeepDungeonDemicloneRow);
impl DeepDungeonDemicloneRow {
    string_field!(singular, 1);
    string_field!(plural, 3);
    string_field!(title_case, 9);
    string_field!(description, 10);
    i8_field!(unknown_4, 2);
    i8_field!(unknown_5, 4);
    i8_field!(unknown_6, 5);
    i8_field!(unknown_7, 6);
    i8_field!(unknown_8, 7);
    i8_field!(unknown_9, 8);
    u32_field!(icon, 0);
}

define_sheet!(DeepDungeonDemicloneSheet, DeepDungeonDemicloneRow, "DeepDungeonDemiclone");
