// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DeepDungeonFloorEffectUIRow);
impl DeepDungeonFloorEffectUIRow {
    string_field!(name, 1);
    string_field!(description, 2);
    u32_field!(icon, 0);
}

define_sheet!(DeepDungeonFloorEffectUISheet, DeepDungeonFloorEffectUIRow, "DeepDungeonFloorEffectUI");
