// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(DeepDungeonRoomLevel, 1);
impl<'a> DeepDungeonRoomLevel<'a> {
    u32_field!(field_0, 0);
}


define_row!(DeepDungeonRoomRow);
impl DeepDungeonRoomRow {
    array_field!(level, 0, 5, DeepDungeonRoomLevel);
}

define_sheet!(DeepDungeonRoomSheet, DeepDungeonRoomRow, "DeepDungeonRoom", no_language_support);
