// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(DeepDungeonPomanderSlot, 1);
impl<'a> DeepDungeonPomanderSlot<'a> {
    u8_field!(field_0, 0);
}

define_element!(DeepDungeonMagiciteSlot, 1);
impl<'a> DeepDungeonMagiciteSlot<'a> {
    u8_field!(field_0, 0);
}


define_row!(DeepDungeonRow);
impl DeepDungeonRow {
    array_field!(pomander_slot, 0, 16, DeepDungeonPomanderSlot);
    u32_field!(unknown_2, 21);
    u32_field!(unknown_3, 25);
    u32_field!(unknown_4, 29);
    u32_field!(unknown_5, 33);
    u32_field!(unknown_6, 22);
    u32_field!(unknown_7, 26);
    u32_field!(unknown_8, 30);
    u32_field!(unknown_9, 34);
    u8_field!(unknown_10, 19);
    u8_field!(unknown_11, 23);
    u8_field!(unknown_12, 27);
    u8_field!(unknown_13, 31);
    array_field!(magicite_slot, 28, 4, DeepDungeonMagiciteSlot);
    string_field!(name, 35);
    u32_field!(unknown_14, 36);
    u8_field!(aetherpool_arm, 0);
    u8_field!(aetherpool_armor, 1);
    u8_field!(deep_dungeon_type, 18);
}

define_sheet!(DeepDungeonSheet, DeepDungeonRow, "DeepDungeon", language_support);
