// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DeliveryQuestRow);
impl DeliveryQuestRow {
    i32_field!(quest, 0);
}

define_sheet!(DeliveryQuestSheet, DeliveryQuestRow, "DeliveryQuest");
