// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DescriptionStandAloneTransientRow);
impl DescriptionStandAloneTransientRow {
    string_field!(unknown_0, 0);
    string_field!(unknown_1, 1);
    u32_field!(unknown_2, 2);
}

define_sheet!(DescriptionStandAloneTransientSheet, DescriptionStandAloneTransientRow, "DescriptionStandAloneTransient");
