// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DescriptionRow);
impl DescriptionRow {
    string_field!(text_long, 0);
    string_field!(text_short, 1);
    string_field!(text_commentary, 2);
    u32_field!(quest, 3);
    u32_field!(section, 4);
    u8_field!(unknown_0, 5);
    bool_field!(unknown_1, 6);
}

define_sheet!(DescriptionSheet, DescriptionRow, "Description");
