// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DirectorTypeRow);
impl DirectorTypeRow {
    string_field!(unknown_0, 5);
    u32_field!(unknown_1, 2);
    u32_field!(unknown_2, 4);
    bool_field!(unknown_3, 0);
    bool_field!(unknown_4, 1);
    bool_field!(unknown_5, 3);
}

define_sheet!(DirectorTypeSheet, DirectorTypeRow, "DirectorType", no_language_support);
