// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DisposalShopRow);
impl DisposalShopRow {
    string_field!(shop_name, 0);
    i32_field!(unknown_0, 1);
    u16_field!(unknown_1, 9);
    i32_field!(unknown_2, 2);
    u16_field!(unknown_3, 10);
    i32_field!(unknown_4, 3);
    u16_field!(unknown_5, 11);
    i32_field!(unknown_6, 4);
    u16_field!(unknown_7, 12);
    i32_field!(unknown_8, 5);
    u16_field!(unknown_9, 13);
    i32_field!(unknown_10, 6);
    u16_field!(unknown_11, 14);
    i32_field!(unknown_12, 7);
    u16_field!(unknown_13, 15);
    i32_field!(unknown_14, 8);
    u16_field!(unknown_15, 16);
    bool_field!(unknown_16, 17);
}

define_sheet!(DisposalShopSheet, DisposalShopRow, "DisposalShop");
