// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DisposalShopItemRow);
impl DisposalShopItemRow {
    u32_field!(quantity_received, 0);
    i32_field!(item_disposed, 1);
    i32_field!(item_received, 2);
    u16_field!(unknown_0, 3);
    bool_field!(unknown_1, 4);
    bool_field!(unknown_2, 5);
}

define_sheet!(DisposalShopItemSheet, DisposalShopItemRow, "DisposalShopItem");
