// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DpsChallengeTransientRow);
impl DpsChallengeTransientRow {
    u16_field!(instance_content, 0);
}

define_sheet!(DpsChallengeTransientSheet, DpsChallengeTransientRow, "DpsChallengeTransient");
