// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DpsChallengeRow);
impl DpsChallengeRow {
    string_field!(name, 6);
    string_field!(description, 7);
    u32_field!(icon, 4);
    u16_field!(player_level, 0);
    u16_field!(unknown_0, 2);
    u16_field!(place_name, 3);
    u16_field!(order, 5);
    bool_field!(unknown_1, 1);
}

define_sheet!(DpsChallengeSheet, DpsChallengeRow, "DpsChallenge");
