// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DynamicEventRow);
impl DynamicEventRow {
    string_field!(name, 0);
    string_field!(description, 1);
    u32_field!(lgb_event_object, 2);
    u32_field!(lgb_map_range, 3);
    u32_field!(quest, 4);
    u32_field!(announce, 5);
    u32_field!(unknown_0, 6);
    u32_field!(unknown_1, 7);
    i16_field!(unknown_6, 8);
    i16_field!(unknown_7, 9);
    i16_field!(unknown_2, 10);
    u8_field!(event_type, 11);
    u8_field!(enemy_type, 12);
    u8_field!(max_participants, 13);
    u8_field!(unknown_4, 14);
    u8_field!(unknown_5, 15);
    u8_field!(single_battle, 16);
    bool_field!(unknown_8, 17);
}

define_sheet!(DynamicEventSheet, DynamicEventRow, "DynamicEvent");
