// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(DynamicEventUITypeRow);
impl DynamicEventUITypeRow {
    u32_field!(unknown_0, 4);
    u32_field!(unknown_1, 9);
    u32_field!(unknown_2, 14);
    u32_field!(unknown_3, 5);
    u32_field!(unknown_4, 10);
    u32_field!(unknown_5, 15);
    u32_field!(unknown_6, 6);
    u32_field!(unknown_7, 11);
    u32_field!(unknown_8, 16);
    u32_field!(unknown_9, 7);
    u32_field!(unknown_10, 12);
    u32_field!(unknown_11, 17);
    u32_field!(unknown_12, 8);
    u32_field!(unknown_13, 13);
    u32_field!(unknown_14, 18);
    u32_field!(unknown_15, 0);
    u32_field!(unknown_16, 1);
    u32_field!(unknown_17, 2);
    bool_field!(unknown_18, 3);
}

define_sheet!(DynamicEventUITypeSheet, DynamicEventUITypeRow, "DynamicEventUIType");
