// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(EObjRow);
impl EObjRow {
    f32_field!(event_high_addition, 15);
    u32_field!(data, 9);
    u16_field!(sgb_path, 11);
    u8_field!(pop_type, 8);
    u8_field!(invisibility, 10);
    u8_field!(unknown_0, 17);
    bool_field!(unknown_1, 0);
    bool_field!(unknown_2, 1);
    bool_field!(unknown_3, 2);
    bool_field!(unknown_4, 3);
    bool_field!(unknown_5, 4);
    bool_field!(unknown_6, 5);
    bool_field!(unknown_7, 6);
    bool_field!(unknown_8, 7);
    bool_field!(eye_collision, 12);
    bool_field!(director_control, 13);
    bool_field!(target, 14);
    bool_field!(unknown_9, 16);
    bool_field!(added_in_53, 18);
    bool_field!(unknown_10, 19);
}

define_sheet!(EObjSheet, EObjRow, "EObj");
