// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(EmjVoiceNpcVoLines, 1);
impl<'a> EmjVoiceNpcVoLines<'a> {
    u32_field!(field_0, 0);
}


define_row!(EmjVoiceNpcRow);
impl EmjVoiceNpcRow {
    array_field!(vo_lines, 0, 25, EmjVoiceNpcVoLines);
    string_field!(name, 27);
    string_field!(name_japanese, 28);
    u16_field!(unlock_link, 0);
    u16_field!(emj_costume, 1);
}

define_sheet!(EmjVoiceNpcSheet, EmjVoiceNpcRow, "EmjVoiceNpc", language_support);
