// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(EquipSlotCategoryRow);
impl EquipSlotCategoryRow {
    i8_field!(main_hand, 0);
    i8_field!(off_hand, 1);
    i8_field!(head, 2);
    i8_field!(body, 3);
    i8_field!(gloves, 4);
    i8_field!(waist, 5);
    i8_field!(legs, 6);
    i8_field!(feet, 7);
    i8_field!(ears, 8);
    i8_field!(neck, 9);
    i8_field!(wrists, 10);
    i8_field!(finger_l, 11);
    i8_field!(finger_r, 12);
    i8_field!(soul_crystal, 13);
}

define_sheet!(EquipSlotCategorySheet, EquipSlotCategoryRow, "EquipSlotCategory");
