// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(EurekaSphereElementAdjustRow);
impl EurekaSphereElementAdjustRow {
    u16_field!(power_modifier, 0);
}

define_sheet!(EurekaSphereElementAdjustSheet, EurekaSphereElementAdjustRow, "EurekaSphereElementAdjust", no_language_support);
