// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(EurekaAetherItemRow);
impl EurekaAetherItemRow {
    string_field!(singular, 0);
    string_field!(plural, 1);
    string_field!(name, 2);
    i8_field!(adjective, 3);
    i8_field!(possessive_pronoun, 4);
    i8_field!(starts_with_vowel, 5);
    i8_field!(unknown_0, 6);
    i8_field!(pronoun, 7);
    i8_field!(article, 8);
}

define_sheet!(EurekaAetherItemSheet, EurekaAetherItemRow, "EurekaAetherItem");
