// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(EurekaMagiciteItemRow);
impl EurekaMagiciteItemRow {
    u32_field!(item, 0);
    u8_field!(eureka_magicite_item_type, 1);
    u8_field!(class_job_category, 2);
}

define_sheet!(EurekaMagiciteItemSheet, EurekaMagiciteItemRow, "EurekaMagiciteItem");
