// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(EurekaAethernetRow);
impl EurekaAethernetRow {
    u16_field!(location, 0);
}

define_sheet!(EurekaAethernetSheet, EurekaAethernetRow, "EurekaAethernet", no_language_support);
