// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(EurekaMagiaActionRow);
impl EurekaMagiaActionRow {
    u32_field!(action, 0);
    u8_field!(max_uses, 1);
}

define_sheet!(EurekaMagiaActionSheet, EurekaMagiaActionRow, "EurekaMagiaAction", no_language_support);
