// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(EurekaStoryProgressRow);
impl EurekaStoryProgressRow {
    u8_field!(unknown_0, 0);
}

define_sheet!(EurekaStoryProgressSheet, EurekaStoryProgressRow, "EurekaStoryProgress", no_language_support);
