// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(EventItemTimelineRow);
impl EventItemTimelineRow {
    u32_field!(action_timeline, 0);
}

define_sheet!(EventItemTimelineSheet, EventItemTimelineRow, "EventItemTimeline", no_language_support);
