// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(EventSystemDefineRow);
impl EventSystemDefineRow {
    string_field!(text, 0);
    u32_field!(define_value, 1);
}

define_sheet!(EventSystemDefineSheet, EventSystemDefineRow, "EventSystemDefine", no_language_support);
