// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(EventIconPriorityPairRow);
impl EventIconPriorityPairRow {
    u32_field!(icon, 0);
}

define_sheet!(EventIconPriorityPairSheet, EventIconPriorityPairRow, "EventIconPriorityPair", no_language_support);
