// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(EventMountGimmickPathMoveRow);
impl EventMountGimmickPathMoveRow {
    i32_field!(unknown_0, 0);
    i32_field!(unknown_1, 1);
    i32_field!(unknown_3, 2);
    u16_field!(unknown_2, 3);
    u16_field!(unknown_4, 4);
    u16_field!(unknown_5, 5);
    bool_field!(unknown_6, 6);
    bool_field!(unknown_7, 7);
    bool_field!(unknown_8, 8);
}

define_sheet!(EventMountGimmickPathMoveSheet, EventMountGimmickPathMoveRow, "EventMountGimmickPathMove");
