// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ExportedSGRow);
impl ExportedSGRow {
    string_field!(sgb_path, 0);
}

define_sheet!(ExportedSGSheet, ExportedSGRow, "ExportedSG", no_language_support);
