// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ExportedGatheringPointRow);
impl ExportedGatheringPointRow {
    f32_field!(x, 0);
    f32_field!(y, 1);
    u16_field!(radius, 2);
    u8_field!(gathering_type, 3);
    u8_field!(gathering_point_type, 4);
}

define_sheet!(ExportedGatheringPointSheet, ExportedGatheringPointRow, "ExportedGatheringPoint");
