// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(FateTokenTypeRow);
impl FateTokenTypeRow {
    u32_field!(currency, 0);
}

define_sheet!(FateTokenTypeSheet, FateTokenTypeRow, "FateTokenType");
