// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(FateShopSpecialShop, 1);
impl<'a> FateShopSpecialShop<'a> {
    u32_field!(field_0, 0);
}

define_element!(FateShopDefaultTalk, 1);
impl<'a> FateShopDefaultTalk<'a> {
    u32_field!(field_0, 0);
}


define_row!(FateShopRow);
impl FateShopRow {
    array_field!(special_shop, 0, 3, FateShopSpecialShop);
    array_field!(default_talk, 3, 9, FateShopDefaultTalk);
}

define_sheet!(FateShopSheet, FateShopRow, "FateShop", no_language_support);
