// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(FateEventEventParameters, 7);
impl<'a> FateEventEventParameters<'a> {
    u32_field!(gesture, 8);
    i32_field!(lip_sync, 16);
    i32_field!(facial, 24);
    i32_field!(shape, 32);
    u8_field!(turn, 0);
    u8_field!(widget_type, 48);
    bool_field!(is_auto_shake, 40);
}

define_subrow!(FateEventText, 1);
impl<'a> FateEventText<'a> {
    u32_field!(field_0, 8);
}


define_row!(FateEventRow);
impl FateEventRow {
    array_field!(event_parameters, 0, 8, FateEventEventParameters);
    array_field!(text, 56, 8, FateEventText);
}

define_sheet!(FateEventSheet, FateEventRow, "FateEvent", language_support);
