// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(FCProfileRow);
impl FCProfileRow {
    string_field!(name, 1);
    u8_field!(priority, 0);
}

define_sheet!(FCProfileSheet, FCProfileRow, "FCProfile", language_support);
