// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(FGSStageUIRow);
impl FGSStageUIRow {
    i32_field!(unknown_0, 3);
    i32_field!(unknown_1, 4);
    i32_field!(unknown_2, 5);
    i32_field!(unknown_3, 6);
    i32_field!(unknown_4, 7);
    u16_field!(unknown_5, 0);
    u16_field!(unknown_6, 1);
    u16_field!(unknown_7, 2);
}

define_sheet!(FGSStageUISheet, FGSStageUIRow, "FGSStageUI");
