// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(FittingShopItemSetItem, 1);
impl<'a> FittingShopItemSetItem<'a> {
    i32_field!(field_0, 0);
}


define_row!(FittingShopItemSetRow);
impl FittingShopItemSetRow {
    array_field!(item, 0, 6, FittingShopItemSetItem);
    string_field!(name, 6);
}

define_sheet!(FittingShopItemSetSheet, FittingShopItemSetRow, "FittingShopItemSet", language_support);
