// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(FittingShopCategoryRow);
impl FittingShopCategoryRow {
    string_field!(unknown_0, 1);
    u8_field!(unknown_1, 0);
}

define_sheet!(FittingShopCategorySheet, FittingShopCategoryRow, "FittingShopCategory", language_support);
