// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(Frontline02Row);
impl Frontline02Row {
    u32_field!(unknown_0, 0);
    u32_field!(unknown_1, 1);
    u32_field!(unknown_2, 2);
    u32_field!(unknown_3, 3);
    u32_field!(unknown_4, 4);
    u32_field!(unknown_5, 5);
    u32_field!(unknown_6, 6);
    u32_field!(unknown_7, 7);
    u32_field!(unknown_8, 8);
    u16_field!(unknown_9, 9);
    u16_field!(unknown_10, 10);
    u16_field!(unknown_11, 11);
    u16_field!(unknown_12, 12);
    u16_field!(unknown_13, 13);
    u16_field!(unknown_14, 14);
    u16_field!(unknown_15, 15);
    u16_field!(unknown_16, 16);
    u16_field!(unknown_17, 17);
    u16_field!(unknown_18, 18);
    u16_field!(unknown_19, 19);
    u16_field!(unknown_20, 20);
    u16_field!(unknown_21, 21);
    u16_field!(unknown_22, 22);
    u16_field!(unknown_23, 23);
    u16_field!(unknown_24, 24);
    u16_field!(unknown_25, 25);
    u16_field!(unknown_26, 26);
    u16_field!(unknown_27, 27);
    u16_field!(unknown_28, 28);
    u16_field!(unknown_29, 29);
}

define_sheet!(Frontline02Sheet, Frontline02Row, "Frontline02");
