// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(Frontline03OvooData, 7);
impl<'a> Frontline03OvooData<'a> {
    u32_field!(empty_icon, 0);
    u32_field!(maelstrom_icon, 1);
    u32_field!(twin_adder_icon, 2);
    u32_field!(immortal_flames_icon, 3);
    u8_field!(unknown_0, 4);
    u8_field!(unknown_1, 5);
    u8_field!(unknown_2, 6);
}


define_row!(Frontline03Row);
impl Frontline03Row {
    array_field!(ovoo_data, 0, 3, Frontline03OvooData);
}

define_sheet!(Frontline03Sheet, Frontline03Row, "Frontline03");
