// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(FurnitureCatalogItemListRow);
impl FurnitureCatalogItemListRow {
    i32_field!(item, 1);
    u16_field!(category, 0);
    u16_field!(patch, 2);
}

define_sheet!(FurnitureCatalogItemListSheet, FurnitureCatalogItemListRow, "FurnitureCatalogItemList", no_language_support);
