// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GFateClimbing2ContentRow);
impl GFateClimbing2ContentRow {
    u32_field!(public_content_text_data, 0);
}

define_sheet!(GFateClimbing2ContentSheet, GFateClimbing2ContentRow, "GFateClimbing2Content");
