// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GFateClimbing2Row);
impl GFateClimbing2Row {
    u32_field!(content_entry, 0);
}

define_sheet!(GFateClimbing2Sheet, GFateClimbing2Row, "GFateClimbing2");
