// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(GatheringRarePopTimeTableStartTime, 1);
impl<'a> GatheringRarePopTimeTableStartTime<'a> {
    u16_field!(field_0, 0);
}

define_element!(GatheringRarePopTimeTableDuration, 1);
impl<'a> GatheringRarePopTimeTableDuration<'a> {
    u16_field!(field_0, 0);
}


define_row!(GatheringRarePopTimeTableRow);
impl GatheringRarePopTimeTableRow {
    array_field!(start_time, 0, 3, GatheringRarePopTimeTableStartTime);
    array_field!(duration, 3, 3, GatheringRarePopTimeTableDuration);
}

define_sheet!(GatheringRarePopTimeTableSheet, GatheringRarePopTimeTableRow, "GatheringRarePopTimeTable", no_language_support);
