// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GatheringPointBonusRow);
impl GatheringPointBonusRow {
    u32_field!(condition_value, 0);
    u32_field!(unknown_0, 1);
    u16_field!(unknown_1, 2);
    u16_field!(bonus_value, 3);
    u16_field!(unknown_2, 4);
    u8_field!(condition, 5);
    u8_field!(bonus_type, 6);
    bool_field!(unknown_3, 7);
}

define_sheet!(GatheringPointBonusSheet, GatheringPointBonusRow, "GatheringPointBonus");
