// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GathererCrafterLvAdjustTableRow);
impl GathererCrafterLvAdjustTableRow {
    u16_field!(recipe_level, 0);
    u16_field!(unknown_1, 1);
    u16_field!(crafter_level, 2);
    u16_field!(gatherer_level, 3);
    u16_field!(fisher_level, 4);
}

define_sheet!(GathererCrafterLvAdjustTableSheet, GathererCrafterLvAdjustTableRow, "GathererCrafterLvAdjustTable", no_language_support);
