// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GatheringPointNameRow);
impl GatheringPointNameRow {
    string_field!(singular, 0);
    string_field!(plural, 1);
    i8_field!(adjective, 2);
    i8_field!(possessive_pronoun, 3);
    i8_field!(starts_with_vowel, 4);
    i8_field!(unknown_0, 5);
    i8_field!(pronoun, 6);
    i8_field!(article, 7);
}

define_sheet!(GatheringPointNameSheet, GatheringPointNameRow, "GatheringPointName");
