// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GatheringLeveBNpcEntryRow);
impl GatheringLeveBNpcEntryRow {
    u32_field!(unknown_0, 0);
    i32_field!(unknown_1, 1);
    u16_field!(unknown_2, 2);
    u32_field!(unknown_3, 3);
    i32_field!(unknown_4, 4);
    u16_field!(unknown_5, 5);
    u32_field!(unknown_6, 6);
    i32_field!(unknown_7, 7);
    u16_field!(unknown_8, 8);
    u32_field!(unknown_9, 9);
    i32_field!(unknown_10, 10);
    u16_field!(unknown_11, 11);
}

define_sheet!(GatheringLeveBNpcEntrySheet, GatheringLeveBNpcEntryRow, "GatheringLeveBNpcEntry");
