// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GatheringNotebookItemRow);
impl GatheringNotebookItemRow {
    i32_field!(unknown_0, 0);
}

define_sheet!(GatheringNotebookItemSheet, GatheringNotebookItemRow, "GatheringNotebookItem");
