// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GatheringItemLevelConvertTableRow);
impl GatheringItemLevelConvertTableRow {
    u8_field!(gathering_item_level, 0);
    u8_field!(stars, 1);
}

define_sheet!(GatheringItemLevelConvertTableSheet, GatheringItemLevelConvertTableRow, "GatheringItemLevelConvertTable");
