// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GcArmyEquipPresetRow);
impl GcArmyEquipPresetRow {
    i32_field!(main_hand, 0);
    i32_field!(off_hand, 1);
    i32_field!(head, 2);
    i32_field!(body, 3);
    i32_field!(gloves, 4);
    i32_field!(legs, 5);
    i32_field!(feet, 6);
}

define_sheet!(GcArmyEquipPresetSheet, GcArmyEquipPresetRow, "GcArmyEquipPreset");
