// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GcArmyTrainingRow);
impl GcArmyTrainingRow {
    string_field!(name, 0);
    string_field!(description, 1);
    u32_field!(experience, 2);
    i8_field!(physical_bonus, 3);
    i8_field!(mental_bonus, 4);
    i8_field!(tactical_bonus, 5);
}

define_sheet!(GcArmyTrainingSheet, GcArmyTrainingRow, "GcArmyTraining");
