// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GCRankLimsaFemaleTextRow);
impl GCRankLimsaFemaleTextRow {
    string_field!(singular, 0);
    string_field!(plural, 2);
    string_field!(name_rank, 8);
    string_field!(unknown_0, 9);
    i8_field!(adjective, 1);
    i8_field!(possessive_pronoun, 3);
    i8_field!(starts_with_vowel, 4);
    i8_field!(unknown_1, 5);
    i8_field!(pronoun, 6);
    i8_field!(article, 7);
}

define_sheet!(GCRankLimsaFemaleTextSheet, GCRankLimsaFemaleTextRow, "GCRankLimsaFemaleText", language_support);
