// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GCScripShopCategoryRow);
impl GCScripShopCategoryRow {
    i8_field!(grand_company, 0);
    i8_field!(tier, 1);
    i8_field!(sub_category, 2);
}

define_sheet!(GCScripShopCategorySheet, GCScripShopCategoryRow, "GCScripShopCategory", no_language_support);
