// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(GFATEGFATEParams, 5);
impl<'a> GFATEGFATEParams<'a> {
    u32_field!(lgb_pop_range, 0);
    u32_field!(icon, 1);
    bool_field!(unknown_0, 2);
    bool_field!(unknown_1, 3);
    bool_field!(unknown_2, 4);
}


define_row!(GFATERow);
impl GFATERow {
    array_field!(gfate_params, 0, 15, GFATEGFATEParams);
    u32_field!(unknown_0, 22);
    u32_field!(unknown_1, 38);
    bool_field!(unknown_2, 54);
    bool_field!(unknown_3, 70);
    bool_field!(unknown_4, 86);
    u32_field!(unknown_5, 2);
    u32_field!(unknown_6, 6);
    u16_field!(unknown_7, 3);
    u16_field!(unknown_8, 4);
    u16_field!(unknown_9, 5);
    u8_field!(unknown_10, 0);
    u8_field!(unknown_11, 1);
}

define_sheet!(GFATESheet, GFATERow, "GFATE", no_language_support);
