// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(GilShopItemQuestRequired, 1);
impl<'a> GilShopItemQuestRequired<'a> {
    i32_field!(field_0, 0);
}


define_row!(GilShopItemRow);
impl GilShopItemRow {
    i32_field!(item, 0);
    array_field!(quest_required, 1, 2, GilShopItemQuestRequired);
    i32_field!(achievement_required, 6);
    u16_field!(state_required, 8);
    u16_field!(patch, 9);
    u8_field!(unknown_70_1, 2);
    u8_field!(unknown_70_2, 3);
    u8_field!(unknown_1, 7);
    bool_field!(is_hq, 1);
}

define_sheet!(GilShopItemSheet, GilShopItemRow, "GilShopItem", no_language_support);
