// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GimmickTalkRow);
impl GimmickTalkRow {
    string_field!(message, 0);
    u8_field!(unknown_1, 1);
    bool_field!(unknown_2, 2);
}

define_sheet!(GimmickTalkSheet, GimmickTalkRow, "GimmickTalk");
