// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(GlassesStyleGlasses, 1);
impl<'a> GlassesStyleGlasses<'a> {
    string_field!(field_0, 0);
}


define_row!(GlassesStyleRow);
impl GlassesStyleRow {
    string_field!(singular, 0);
    string_field!(plural, 1);
    string_field!(name, 2);
    i8_field!(unknown_70_1, 3);
    i8_field!(unknown_70_2, 4);
    i8_field!(unknown_70_3, 5);
    i8_field!(unknown_70_4, 6);
    i8_field!(unknown_70_5, 7);
    i8_field!(unknown_70_6, 8);
    i32_field!(icon, 9);
    u16_field!(order, 10);
    array_field!(glasses, 11, 12, GlassesStyleGlasses);
    i16_field!(unknown_70_7, 23);
}

define_sheet!(GlassesStyleSheet, GlassesStyleRow, "GlassesStyle");
