// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(GlassesStyleGlasses, 1);
impl<'a> GlassesStyleGlasses<'a> {
    string_field!(field_0, 15);
}


define_row!(GlassesStyleRow);
impl GlassesStyleRow {
    string_field!(singular, 15);
    string_field!(plural, 17);
    string_field!(name, 23);
    i8_field!(unknown_70_1, 16);
    i8_field!(unknown_70_2, 18);
    i8_field!(unknown_70_3, 19);
    i8_field!(unknown_70_4, 20);
    i8_field!(unknown_70_5, 21);
    i8_field!(unknown_70_6, 22);
    i32_field!(icon, 1);
    u16_field!(order, 2);
    array_field!(glasses, 11, 12, GlassesStyleGlasses);
    i16_field!(unknown_70_7, 0);
}

define_sheet!(GlassesStyleSheet, GlassesStyleRow, "GlassesStyle", language_support);
