// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GlassesRow);
impl GlassesRow {
    string_field!(singular, 0);
    string_field!(plural, 1);
    string_field!(description, 2);
    string_field!(name, 3);
    i8_field!(unknown_70_1, 4);
    i8_field!(unknown_70_2, 5);
    i8_field!(unknown_70_3, 6);
    i8_field!(unknown_70_4, 7);
    i8_field!(unknown_70_5, 8);
    i8_field!(unknown_70_6, 9);
    u32_field!(unknown_70_7, 10);
    i32_field!(icon, 11);
    u16_field!(unknown_70_8, 12);
    i16_field!(style, 13);
}

define_sheet!(GlassesSheet, GlassesRow, "Glasses");
