// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GoldSaucerArcadeMachineRow);
impl GoldSaucerArcadeMachineRow {
    u32_field!(unknown_0, 0);
    u32_field!(poor, 1);
    u8_field!(unknown_1, 2);
    u8_field!(unknown_2, 3);
    u8_field!(unknown_3, 4);
    u8_field!(unknown_4, 5);
    u32_field!(unknown_5, 6);
    u32_field!(good, 7);
    u8_field!(unknown_6, 8);
    u8_field!(unknown_7, 9);
    u8_field!(unknown_8, 10);
    u8_field!(unknown_9, 11);
    u32_field!(unknown_10, 12);
    u32_field!(great, 13);
    u8_field!(unknown_11, 14);
    u8_field!(unknown_12, 15);
    u8_field!(unknown_13, 16);
    u8_field!(unknown_14, 17);
    u32_field!(unknown_15, 18);
    u32_field!(excellent, 19);
    u8_field!(unknown_16, 20);
    u8_field!(unknown_17, 21);
    u8_field!(unknown_18, 22);
    u8_field!(unknown_19, 23);
    string_field!(unknown_20, 24);
    string_field!(unknown_21, 25);
    string_field!(unknown_22, 26);
    string_field!(unknown_23, 27);
    u32_field!(fail_image, 28);
    u32_field!(unknown_24, 29);
    u16_field!(unknown_25, 30);
    u8_field!(unknown_26, 31);
    u8_field!(unknown_27, 32);
    u8_field!(unknown_28, 33);
    u8_field!(unknown_29, 34);
    u8_field!(unknown_30, 35);
    u8_field!(unknown_31, 36);
    i8_field!(unknown_32, 37);
    i8_field!(unknown_33, 38);
    i8_field!(unknown_34, 39);
    i8_field!(unknown_35, 40);
    i8_field!(unknown_36, 41);
    i8_field!(unknown_37, 42);
}

define_sheet!(GoldSaucerArcadeMachineSheet, GoldSaucerArcadeMachineRow, "GoldSaucerArcadeMachine");
