// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GrandCompanyRow);
impl GrandCompanyRow {
    string_field!(name, 0);
    string_field!(unknown_0, 2);
    string_field!(unknown_1, 8);
    i8_field!(unknown_2, 1);
    i8_field!(unknown_3, 3);
    i8_field!(unknown_4, 4);
    i8_field!(unknown_5, 5);
    i8_field!(unknown_6, 6);
    i8_field!(unknown_7, 7);
    i8_field!(monster_note, 9);
}

define_sheet!(GrandCompanySheet, GrandCompanyRow, "GrandCompany");
