// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GrandCompanyRankRow);
impl GrandCompanyRankRow {
    u32_field!(max_seals, 0);
    u32_field!(required_seals, 1);
    i32_field!(icon_maelstrom, 2);
    i32_field!(icon_serpents, 3);
    i32_field!(icon_flames, 4);
    i32_field!(quest_maelstrom, 5);
    i32_field!(quest_serpents, 6);
    i32_field!(quest_flames, 7);
    u8_field!(tier, 8);
    u8_field!(order, 9);
    u8_field!(unknown_0, 10);
}

define_sheet!(GrandCompanyRankSheet, GrandCompanyRankRow, "GrandCompanyRank");
