// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(GroupPoseStampCategoryRow);
impl GroupPoseStampCategoryRow {
    string_field!(name, 1);
    u8_field!(unknown_0, 0);
}

define_sheet!(GroupPoseStampCategorySheet, GroupPoseStampCategoryRow, "GroupPoseStampCategory");
