// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(HalloweenNpcSelectRow);
impl HalloweenNpcSelectRow {
    string_field!(description, 6);
    u32_field!(unknown_1, 2);
    u32_field!(unknown_2, 3);
    u32_field!(preview_icon, 5);
    u16_field!(transformation, 0);
    u16_field!(unknown_5, 4);
    u8_field!(expansion, 1);
}

define_sheet!(HalloweenNpcSelectSheet, HalloweenNpcSelectRow, "HalloweenNpcSelect");
