// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(HousingUnitedExteriorRow);
impl HousingUnitedExteriorRow {
    u32_field!(roof, 1);
    u32_field!(walls, 2);
    u32_field!(windows, 3);
    u32_field!(door, 4);
    u32_field!(optional_roof, 5);
    u32_field!(optional_wall, 6);
    u32_field!(optional_signboard, 7);
    u32_field!(fence, 8);
    u8_field!(plot_size, 0);
}

define_sheet!(HousingUnitedExteriorSheet, HousingUnitedExteriorRow, "HousingUnitedExterior");
