// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(HousingPlacementRow);
impl HousingPlacementRow {
    string_field!(text, 0);
}

define_sheet!(HousingPlacementSheet, HousingPlacementRow, "HousingPlacement", language_support);
