// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(HousingEmploymentNpcRaceRow);
impl HousingEmploymentNpcRaceRow {
    string_field!(race, 0);
}

define_sheet!(HousingEmploymentNpcRaceSheet, HousingEmploymentNpcRaceRow, "HousingEmploymentNpcRace");
