// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(HousingRenovationRow);
impl HousingRenovationRow {
    string_field!(name, 0);
    string_field!(description, 1);
    i32_field!(icon, 2);
    // Also links to HousingIndoorTerritory which shares a 1:1 map of ids to TerritoryType
    u16_field!(territory, 3);
}

define_sheet!(HousingRenovationSheet, HousingRenovationRow, "HousingRenovation");
