// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(HousingAethernetRow);
impl HousingAethernetRow {
    u32_field!(level, 0);
    u16_field!(territory_type, 1);
    u16_field!(place_name, 2);
    u8_field!(order, 3);
}

define_sheet!(HousingAethernetSheet, HousingAethernetRow, "HousingAethernet");
