// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(HouseRetainerPoseRow);
impl HouseRetainerPoseRow {
    u16_field!(action_timeline, 0);
}

define_sheet!(HouseRetainerPoseSheet, HouseRetainerPoseRow, "HouseRetainerPose");
