// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(HousingPresetRow);
impl HousingPresetRow {
    string_field!(singular, 0);
    string_field!(plural, 2);
    i8_field!(adjective, 1);
    i8_field!(possessive_pronoun, 3);
    i8_field!(starts_with_vowel, 4);
    i8_field!(unknown_0, 5);
    i8_field!(pronoun, 6);
    i8_field!(article, 7);
    i32_field!(exterior_roof, 10);
    i32_field!(exterior_wall, 11);
    i32_field!(exterior_window, 12);
    i32_field!(exterior_door, 13);
    i32_field!(interior_wall, 14);
    i32_field!(interior_flooring, 15);
    i32_field!(interior_lighting, 16);
    i32_field!(other_floor_wall, 17);
    i32_field!(other_floor_flooring, 18);
    i32_field!(other_floor_lighting, 19);
    i32_field!(basement_wall, 20);
    i32_field!(basement_flooring, 21);
    i32_field!(basement_lighting, 22);
    i32_field!(mansion_lighting, 23);
    u16_field!(place_name, 8);
    u8_field!(housing_size, 9);
}

define_sheet!(HousingPresetSheet, HousingPresetRow, "HousingPreset", language_support);
