// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(HowToHowToPagePC, 1);
impl<'a> HowToHowToPagePC<'a> {
    string_field!(field_0, 0);
}

define_subrow!(HowToHowToPageController, 1);
impl<'a> HowToHowToPageController<'a> {
    string_field!(field_0, 0);
}


define_row!(HowToRow);
impl HowToRow {
    string_field!(name, 0);
    array_field!(how_to_page_pc, 1, 5, HowToHowToPagePC);
    array_field!(how_to_page_controller, 6, 5, HowToHowToPageController);
    u8_field!(sort, 13);
    i8_field!(category, 12);
    bool_field!(announce, 1);
}

define_sheet!(HowToSheet, HowToRow, "HowTo", language_support);
