// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(HowToCategoryRow);
impl HowToCategoryRow {
    string_field!(category, 0);
}

define_sheet!(HowToCategorySheet, HowToCategoryRow, "HowToCategory");
