// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(HWDSharedGroupControlParamRow);
impl HWDSharedGroupControlParamRow {
    u8_field!(unknown_0, 0);
    u8_field!(param_value, 1);
}

define_sheet!(HWDSharedGroupControlParamSheet, HWDSharedGroupControlParamRow, "HWDSharedGroupControlParam");
