// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(HWDLevelChangeDeceptionRow);
impl HWDLevelChangeDeceptionRow {
    i32_field!(image, 0);
}

define_sheet!(HWDLevelChangeDeceptionSheet, HWDLevelChangeDeceptionRow, "HWDLevelChangeDeception");
