// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(HWDGathererInspectionRewardRow);
impl HWDGathererInspectionRewardRow {
    u16_field!(scrips, 0);
    u16_field!(points, 1);
}

define_sheet!(HWDGathererInspectionRewardSheet, HWDGathererInspectionRewardRow, "HWDGathererInspectionReward", no_language_support);
