// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(HWDGathererInspectionHWDGathererInspectionData, 6);
impl<'a> HWDGathererInspectionHWDGathererInspectionData<'a> {
    u32_field!(required_item, 0);
    u32_field!(fish_parameter, 79);
    u32_field!(item_received, 237);
    array_field!(reward, 3, 2, HWDGathererInspectionHWDGathererInspectionData);
    u8_field!(amount_required, 158);
    u8_field!(phase, 474);
}

define_subrow!(HWDGathererInspectionHWDGathererInspectionDataReward, 1);
impl<'a> HWDGathererInspectionHWDGathererInspectionDataReward<'a> {
    u32_field!(field_0, 0);
}


define_row!(HWDGathererInspectionRow);
impl HWDGathererInspectionRow {
    array_field!(hwd_gatherer_inspection_data, 0, 79, HWDGathererInspectionHWDGathererInspectionData);
}

define_sheet!(HWDGathererInspectionSheet, HWDGathererInspectionRow, "HWDGathererInspection", no_language_support);
