// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(IconLanguageRow);
impl IconLanguageRow {
    bool_field!(unknown_0, 0);
    bool_field!(unknown_1, 1);
    bool_field!(unknown_2, 2);
    bool_field!(unknown_3, 3);
    bool_field!(unknown_4, 4);
    bool_field!(unknown_5, 5);
    bool_field!(unknown_6, 6);
    bool_field!(unknown_7, 7);
    bool_field!(unknown_8, 8);
    bool_field!(unknown_9, 9);
}

define_sheet!(IconLanguageSheet, IconLanguageRow, "IconLanguage", no_language_support);
