// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(IKDFishParamRow);
impl IKDFishParamRow {
    u32_field!(fish, 0);
    u8_field!(ikd_content_bonus, 1);
    u8_field!(unknown_0, 2);
}

define_sheet!(IKDFishParamSheet, IKDFishParamRow, "IKDFishParam");
