// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(InclusionShopSeriesRow);
impl InclusionShopSeriesRow {
    u32_field!(special_shop, 0);
}

define_sheet!(InclusionShopSeriesSheet, InclusionShopSeriesRow, "InclusionShopSeries", no_language_support);
