// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(InclusionShopWelcomTextRow);
impl InclusionShopWelcomTextRow {
    string_field!(unknown_0, 0);
}

define_sheet!(InclusionShopWelcomTextSheet, InclusionShopWelcomTextRow, "InclusionShopWelcomText", language_support);
