// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(IndividualWeatherIndividualWeatherData, 4);
impl<'a> IndividualWeatherIndividualWeatherData<'a> {
    u32_field!(quest, 0);
    // quest progress maybe
    u32_field!(unknown_0, 1);
    u8_field!(weather, 2);
    u8_field!(unknown_1, 3);
}


define_row!(IndividualWeatherRow);
impl IndividualWeatherRow {
    array_field!(individual_weather_data, 0, 7, IndividualWeatherIndividualWeatherData);
}

define_sheet!(IndividualWeatherSheet, IndividualWeatherRow, "IndividualWeather", no_language_support);
