// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(InstanceContentGuideRow);
impl InstanceContentGuideRow {
    u32_field!(instance, 0);
    u32_field!(unknown_0, 1);
}

define_sheet!(InstanceContentGuideSheet, InstanceContentGuideRow, "InstanceContentGuide", no_language_support);
