// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ItemSpecialBonusRow);
impl ItemSpecialBonusRow {
    string_field!(name, 0);
    string_field!(requirement_text, 1);
}

define_sheet!(ItemSpecialBonusSheet, ItemSpecialBonusRow, "ItemSpecialBonus", language_support);
