// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ItemBarterWarningRow);
impl ItemBarterWarningRow {
    u32_field!(achievement, 0);
}

define_sheet!(ItemBarterWarningSheet, ItemBarterWarningRow, "ItemBarterWarning", no_language_support);
