// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ItemBarterCheckRow);
impl ItemBarterCheckRow {
    u32_field!(question, 0);
    u32_field!(confirm, 1);
    u16_field!(category, 2);
}

define_sheet!(ItemBarterCheckSheet, ItemBarterCheckRow, "ItemBarterCheck");
