// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(JobHudManualRow);
impl JobHudManualRow {
    u32_field!(action, 0);
    u32_field!(unknown_0, 1);
    u16_field!(guide, 2);
    u8_field!(unknown_1, 3);
    u8_field!(unknown_70, 4);
    u8_field!(unknown_2, 5);
    u8_field!(unknown_3, 6);
}

define_sheet!(JobHudManualSheet, JobHudManualRow, "JobHudManual");
