// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(KineDriverOffGroupRow);
impl KineDriverOffGroupRow {
    i8_field!(unknown_0, 0);
    i8_field!(unknown_1, 1);
    i8_field!(unknown_2, 2);
    i8_field!(unknown_3, 3);
    i8_field!(unknown_4, 4);
}

define_sheet!(KineDriverOffGroupSheet, KineDriverOffGroupRow, "KineDriverOffGroup", no_language_support);
