// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(LeveRewardItemGroupItem, 1);
impl<'a> LeveRewardItemGroupItem<'a> {
    i32_field!(field_0, 0);
}

define_element!(LeveRewardItemGroupCount, 1);
impl<'a> LeveRewardItemGroupCount<'a> {
    i32_field!(field_0, 0);
}

define_element!(LeveRewardItemGroupIsHQ, 1);
impl<'a> LeveRewardItemGroupIsHQ<'a> {
    i32_field!(field_0, 0);
}


define_row!(LeveRewardItemGroupRow);
impl LeveRewardItemGroupRow {
    array_field!(item, 0, 9, LeveRewardItemGroupItem);
    array_field!(count, 9, 9, LeveRewardItemGroupCount);
    array_field!(is_hq, 18, 9, LeveRewardItemGroupIsHQ);
}

define_sheet!(LeveRewardItemGroupSheet, LeveRewardItemGroupRow, "LeveRewardItemGroup", no_language_support);
