// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(LFGExtensionContentRow);
impl LFGExtensionContentRow {
    u32_field!(unknown_0, 2);
    u8_field!(unknown_1, 0);
    u8_field!(unknown_2, 1);
    u8_field!(unknown_3, 3);
}

define_sheet!(LFGExtensionContentSheet, LFGExtensionContentRow, "LFGExtensionContent");
