// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(LinkRaceRow);
impl LinkRaceRow {
    bool_field!(unknown_0, 0);
    bool_field!(unknown_1, 1);
    bool_field!(unknown_2, 2);
    bool_field!(unknown_3, 3);
}

define_sheet!(LinkRaceSheet, LinkRaceRow, "LinkRace", no_language_support);
