// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(LiveMinigamesDynamicDefineRow);
impl LiveMinigamesDynamicDefineRow {
    u32_field!(unknown_0, 0);
}

define_sheet!(LiveMinigamesDynamicDefineSheet, LiveMinigamesDynamicDefineRow, "LiveMinigamesDynamicDefine", no_language_support);
