// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(LoadingTipsRow);
impl LoadingTipsRow {
    bool_field!(unknown_0, 2);
    i32_field!(unknown_1, 1);
    u8_field!(unknown_2, 0);
}

define_sheet!(LoadingTipsSheet, LoadingTipsRow, "LoadingTips", language_support);
