// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(LobbyRow);
impl LobbyRow {
    string_field!(text, 0);
    string_field!(unknown_0, 1);
    string_field!(unknown_1, 2);
    u32_field!(type_, 3);
    u32_field!(param, 4);
    u32_field!(link, 5);
}

define_sheet!(LobbySheet, LobbyRow, "Lobby");
