// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MainCommandCategoryRow);
impl MainCommandCategoryRow {
    string_field!(name, 1);
    i32_field!(unknown_0, 0);
}

define_sheet!(MainCommandCategorySheet, MainCommandCategoryRow, "MainCommandCategory");
