// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MapRow);
impl MapRow {
    string_field!(id, 6);
    u32_field!(discovery_flag, 15);
    u16_field!(map_marker_range, 5);
    u16_field!(size_factor, 7);
    u16_field!(place_name_region, 10);
    u16_field!(place_name, 11);
    u16_field!(place_name_sub, 12);
    u16_field!(territory_type, 16);
    i16_field!(offset_x, 8);
    i16_field!(offset_y, 9);
    i16_field!(discovery_index, 14);
    u8_field!(map_condition, 0);
    u8_field!(priority_category_ui, 1);
    u8_field!(priority_ui, 2);
    u8_field!(map_type, 4);
    u8_field!(unknown_2, 13);
    u8_field!(map_replace, 20);
    i8_field!(map_index, 3);
    bool_field!(discovery_array_byte, 17);
    bool_field!(is_event, 18);
    bool_field!(unknown_1, 19);
}

define_sheet!(MapSheet, MapRow, "Map");
