// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MapReplaceRow);
impl MapReplaceRow {
    u32_field!(quest, 0);
    u16_field!(map, 1);
    u16_field!(territory_type, 2);
    u16_field!(unknown_4, 3);
    u8_field!(unknown_7, 4);
    u8_field!(unknown_8, 5);
    u8_field!(unknown_5, 6);
    u8_field!(unknown_6, 7);
    u8_field!(quest_sequence, 8);
}

define_sheet!(MapReplaceSheet, MapReplaceRow, "MapReplace");
