// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MarkerRow);
impl MarkerRow {
    string_field!(name, 0);
    i32_field!(icon, 1);
    u8_field!(sort_order, 2);
}

define_sheet!(MarkerSheet, MarkerRow, "Marker");
