// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(MateriaJoinRateGatherCraftNQOvermeldPercentSlot, 1);
impl<'a> MateriaJoinRateGatherCraftNQOvermeldPercentSlot<'a> {
    f32_field!(field_0, 0);
}

define_element!(MateriaJoinRateGatherCraftHQOvermeldPercentSlot, 1);
impl<'a> MateriaJoinRateGatherCraftHQOvermeldPercentSlot<'a> {
    f32_field!(field_0, 0);
}


define_row!(MateriaJoinRateGatherCraftRow);
impl MateriaJoinRateGatherCraftRow {
    array_field!(nq_overmeld_percent_slot, 0, 4, MateriaJoinRateGatherCraftNQOvermeldPercentSlot);
    array_field!(hq_overmeld_percent_slot, 4, 4, MateriaJoinRateGatherCraftHQOvermeldPercentSlot);
}

define_sheet!(MateriaJoinRateGatherCraftSheet, MateriaJoinRateGatherCraftRow, "MateriaJoinRateGatherCraft", no_language_support);
