// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MiniGameRARow);
impl MiniGameRARow {
    u32_field!(unknown_0, 0);
    i32_field!(unknown_1, 1);
    i32_field!(icon, 2);
    i32_field!(image, 3);
    i32_field!(bgm, 4);
    i32_field!(unknown_2, 5);
    u16_field!(unknown_3, 6);
    u16_field!(unknown_4, 7);
    u16_field!(unknown_5, 8);
    i16_field!(unknown_6, 9);
    i16_field!(unknown_7, 10);
    i16_field!(unknown_8, 11);
    i16_field!(unknown_9, 12);
    u8_field!(unknown_10, 13);
    u8_field!(unknown_11, 14);
    u8_field!(unknown_12, 15);
    u8_field!(unknown_13, 16);
    bool_field!(unknown_14, 17);
    bool_field!(unknown_15, 18);
    bool_field!(unknown_16, 19);
    bool_field!(unknown_17, 20);
    bool_field!(unknown_18, 21);
}

define_sheet!(MiniGameRASheet, MiniGameRARow, "MiniGameRA");
