// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MiniGameTurnBreakEnemyRow);
impl MiniGameTurnBreakEnemyRow {
    i32_field!(unknown_0, 28);
    u8_field!(unknown_1, 20);
    u8_field!(unknown_2, 24);
    bool_field!(unknown_3, 12);
    bool_field!(unknown_4, 16);
    i32_field!(unknown_5, 29);
    u8_field!(unknown_6, 21);
    u8_field!(unknown_7, 25);
    bool_field!(unknown_8, 13);
    bool_field!(unknown_9, 17);
    i32_field!(unknown_10, 30);
    u8_field!(unknown_11, 22);
    u8_field!(unknown_12, 26);
    bool_field!(unknown_13, 14);
    bool_field!(unknown_14, 18);
    i32_field!(unknown_15, 31);
    u8_field!(unknown_16, 23);
    u8_field!(unknown_17, 27);
    bool_field!(unknown_18, 15);
    bool_field!(unknown_19, 19);
    i32_field!(unknown_20, 3);
    i32_field!(unknown_21, 7);
    u8_field!(unknown_22, 0);
    u8_field!(unknown_23, 1);
    u8_field!(unknown_24, 2);
    u8_field!(unknown_25, 5);
    u8_field!(unknown_26, 6);
    u8_field!(unknown_27, 8);
    u8_field!(unknown_28, 9);
    u8_field!(unknown_29, 10);
    u8_field!(unknown_30, 11);
    u8_field!(unknown_31, 32);
    u8_field!(unknown_32, 33);
    u8_field!(unknown_33, 34);
    bool_field!(unknown_34, 4);
}

define_sheet!(MiniGameTurnBreakEnemySheet, MiniGameTurnBreakEnemyRow, "MiniGameTurnBreakEnemy", no_language_support);
