// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MinionStageRow);
impl MinionStageRow {
    string_field!(unknown_0, 0);
    u16_field!(unknown_1, 2);
    bool_field!(unknown_2, 1);
}

define_sheet!(MinionStageSheet, MinionStageRow, "MinionStage", language_support);
