// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MinionRulesRow);
impl MinionRulesRow {
    string_field!(rule, 0);
    string_field!(description, 1);
}

define_sheet!(MinionRulesSheet, MinionRulesRow, "MinionRules");
