// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(MirageStoreSetItemLookupItem, 1);
impl<'a> MirageStoreSetItemLookupItem<'a> {
    u32_field!(field_0, 0);
}


define_row!(MirageStoreSetItemLookupRow);
impl MirageStoreSetItemLookupRow {
    array_field!(item, 0, 5, MirageStoreSetItemLookupItem);
}

define_sheet!(MirageStoreSetItemLookupSheet, MirageStoreSetItemLookupRow, "MirageStoreSetItemLookup");
