// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(MJILandmarkSGB, 1);
impl<'a> MJILandmarkSGB<'a> {
    u32_field!(field_0, 0);
}

define_subrow!(MJILandmarkMaterial, 1);
impl<'a> MJILandmarkMaterial<'a> {
    u32_field!(field_0, 0);
}

define_subrow!(MJILandmarkAmount, 1);
impl<'a> MJILandmarkAmount<'a> {
    u32_field!(field_0, 0);
}


define_row!(MJILandmarkRow);
impl MJILandmarkRow {
    u32_field!(name, 30);
    u32_field!(icon, 32);
    u16_field!(unlock_link, 2);
    array_field!(sgb, 3, 7, MJILandmarkSGB);
    array_field!(material, 10, 5, MJILandmarkMaterial);
    u16_field!(unknown_1, 31);
    u8_field!(unknown_2, 0);
    u8_field!(unknown_3, 1);
    u8_field!(unknown_4, 6);
    u8_field!(unknown_5, 8);
    u8_field!(unknown_6, 10);
    u8_field!(unknown_7, 12);
    u8_field!(unknown_8, 14);
    u8_field!(unknown_9, 15);
    u8_field!(unknown_10, 16);
    u8_field!(unknown_11, 17);
    u8_field!(unknown_12, 18);
    u8_field!(unknown_13, 19);
    array_field!(amount, 28, 5, MJILandmarkAmount);
}

define_sheet!(MJILandmarkSheet, MJILandmarkRow, "MJILandmark", no_language_support);
