// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MJICraftworksTensionRow);
impl MJICraftworksTensionRow {
    u8_field!(unknown_0, 0);
}

define_sheet!(MJICraftworksTensionSheet, MJICraftworksTensionRow, "MJICraftworksTension", no_language_support);
