// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(MJICraftworksObjectTheme, 1);
impl<'a> MJICraftworksObjectTheme<'a> {
    u16_field!(field_0, 0);
}

define_element!(MJICraftworksObjectMaterial, 1);
impl<'a> MJICraftworksObjectMaterial<'a> {
    u16_field!(field_0, 0);
}

define_element!(MJICraftworksObjectAmount, 1);
impl<'a> MJICraftworksObjectAmount<'a> {
    u16_field!(field_0, 0);
}


define_row!(MJICraftworksObjectRow);
impl MJICraftworksObjectRow {
    u16_field!(item, 0);
    array_field!(theme, 1, 2, MJICraftworksObjectTheme);
    u16_field!(unknown_0, 3);
    array_field!(material, 4, 4, MJICraftworksObjectMaterial);
    array_field!(amount, 8, 4, MJICraftworksObjectAmount);
    u16_field!(level_req, 12);
    u16_field!(crafting_time, 13);
    u16_field!(value, 14);
}

define_sheet!(MJICraftworksObjectSheet, MJICraftworksObjectRow, "MJICraftworksObject", no_language_support);
