// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MJICropSeedRow);
impl MJICropSeedRow {
    u32_field!(item, 0);
    u32_field!(name, 2);
    u16_field!(sgb, 1);
}

define_sheet!(MJICropSeedSheet, MJICropSeedRow, "MJICropSeed", no_language_support);
