// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MJIVillageDevelopmentRow);
impl MJIVillageDevelopmentRow {
    u32_field!(enpc, 0);
    u32_field!(unknown_0, 4);
    u32_field!(unknown_1, 6);
    u32_field!(unknown_2, 8);
    u32_field!(unknown_3, 10);
    u32_field!(unknown_4, 12);
    u16_field!(behavior_0, 9);
    u16_field!(behavior_1, 11);
    u8_field!(unknown_5, 1);
    u8_field!(unknown_6, 2);
    u8_field!(unknown_7, 3);
    u8_field!(unknown_8, 5);
    u8_field!(unknown_9, 7);
    u8_field!(unknown_10, 13);
    u8_field!(unknown_11, 14);
}

define_sheet!(MJIVillageDevelopmentSheet, MJIVillageDevelopmentRow, "MJIVillageDevelopment", no_language_support);
