// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MJIFunctionRow);
impl MJIFunctionRow {
    u8_field!(unknown_0, 1);
    u8_field!(unknown_1, 2);
    u8_field!(unknown_2, 3);
    u8_field!(unknown_3, 4);
    i8_field!(unknown_4, 0);
}

define_sheet!(MJIFunctionSheet, MJIFunctionRow, "MJIFunction");
