// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MJIGatheringItemRow);
impl MJIGatheringItemRow {
    u16_field!(radius, 0);
    i16_field!(x, 1);
    i16_field!(y, 2);
    u8_field!(unknown_0, 3);
    u8_field!(unknown_1, 4);
    u32_field!(item, 5);
    u8_field!(sort, 6);
}

define_sheet!(MJIGatheringItemSheet, MJIGatheringItemRow, "MJIGatheringItem");
