// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(MJIBuildingSgb, 1);
impl<'a> MJIBuildingSgb<'a> {
    u32_field!(field_0, 0);
}

define_subrow!(MJIBuildingMaterial, 1);
impl<'a> MJIBuildingMaterial<'a> {
    u32_field!(field_0, 0);
}

define_subrow!(MJIBuildingAmount, 1);
impl<'a> MJIBuildingAmount<'a> {
    u32_field!(field_0, 0);
}


define_row!(MJIBuildingRow);
impl MJIBuildingRow {
    u32_field!(name, 0);
    u32_field!(unknown_0, 1);
    u32_field!(icon, 2);
    array_field!(sgb, 3, 5, MJIBuildingSgb);
    u8_field!(unknown_1, 8);
    u8_field!(unknown_2, 9);
    u8_field!(unknown_3, 10);
    u8_field!(unknown_4, 11);
    u8_field!(unknown_5, 12);
    u8_field!(unknown_6, 13);
    u8_field!(unknown_7, 14);
    u8_field!(unknown_8, 15);
    u8_field!(unknown_9, 16);
    u8_field!(unknown_10, 17);
    u8_field!(unknown_11, 18);
    u8_field!(unknown_12, 19);
    u8_field!(unknown_13, 20);
    u8_field!(unknown_14, 21);
    array_field!(material, 22, 5, MJIBuildingMaterial);
    array_field!(amount, 27, 5, MJIBuildingAmount);
}

define_sheet!(MJIBuildingSheet, MJIBuildingRow, "MJIBuilding");
