// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MJIMinionPopAreasRow);
impl MJIMinionPopAreasRow {
    i32_field!(text, 0);
    i16_field!(x, 1);
    i16_field!(y, 2);
    u8_field!(required_function, 3);
    bool_field!(unknown_4, 4);
}

define_sheet!(MJIMinionPopAreasSheet, MJIMinionPopAreasRow, "MJIMinionPopAreas");
