// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MJIGatheringObjectRow);
impl MJIGatheringObjectRow {
    u32_field!(map_icon, 0);
    u32_field!(unknown_0, 1);
    u32_field!(name, 2);
    u16_field!(sgb, 3);
    u16_field!(unknown_1, 4);
}

define_sheet!(MJIGatheringObjectSheet, MJIGatheringObjectRow, "MJIGatheringObject");
