// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MJIVillageAppearanceUIRow);
impl MJIVillageAppearanceUIRow {
    i32_field!(floor, 0);
    u16_field!(unknown_0, 1);
    u16_field!(unknown_1, 2);
}

define_sheet!(MJIVillageAppearanceUISheet, MJIVillageAppearanceUIRow, "MJIVillageAppearanceUI", no_language_support);
