// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MJIGardenscapingRow);
impl MJIGardenscapingRow {
    i32_field!(unknown_0, 0);
    i32_field!(unknown_1, 1);
    i32_field!(unknown_2, 2);
    i32_field!(item, 3);
    i32_field!(unknown_3, 4);
    u16_field!(unknown_4, 5);
    u16_field!(unknown_5, 6);
    u16_field!(unknown_6, 7);
    u8_field!(level, 8);
}

define_sheet!(MJIGardenscapingSheet, MJIGardenscapingRow, "MJIGardenscaping");
