// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MJIItemPouchRow);
impl MJIItemPouchRow {
    u32_field!(item, 0);
    i32_field!(category, 1);
    u8_field!(crop, 2);
    u8_field!(unknown_0, 3);
}

define_sheet!(MJIItemPouchSheet, MJIItemPouchRow, "MJIItemPouch");
