// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(MJIVillageAppearanceSGVillageAppearanceData, 2);
impl<'a> MJIVillageAppearanceSGVillageAppearanceData<'a> {
    u32_field!(unknown_param, 0);
    u16_field!(sgb, 1);
}


define_row!(MJIVillageAppearanceSGRow);
impl MJIVillageAppearanceSGRow {
    array_field!(village_appearance_data, 0, 5, MJIVillageAppearanceSGVillageAppearanceData);
}

define_sheet!(MJIVillageAppearanceSGSheet, MJIVillageAppearanceSGRow, "MJIVillageAppearanceSG", no_language_support);
