// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MJILivelyActorRow);
impl MJILivelyActorRow {
    f32_field!(x, 2);
    f32_field!(y, 3);
    f32_field!(z, 4);
    f32_field!(rot, 5);
    u32_field!(enpc, 0);
    u16_field!(behavior, 1);
}

define_sheet!(MJILivelyActorSheet, MJILivelyActorRow, "MJILivelyActor", no_language_support);
