// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(MJICraftworksPopularityPopularity, 1);
impl<'a> MJICraftworksPopularityPopularity<'a> {
    u8_field!(field_0, 0);
}


define_row!(MJICraftworksPopularityRow);
impl MJICraftworksPopularityRow {
    array_field!(popularity, 0, 91, MJICraftworksPopularityPopularity);
}

define_sheet!(MJICraftworksPopularitySheet, MJICraftworksPopularityRow, "MJICraftworksPopularity", no_language_support);
