// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MJIBuildingPlaceRow);
impl MJIBuildingPlaceRow {
    u32_field!(unknown_0, 0);
    u32_field!(name, 1);
    u32_field!(sgb, 2);
    i16_field!(unknown_1, 4);
    i16_field!(unknown_2, 5);
    u8_field!(unknown_3, 3);
}

define_sheet!(MJIBuildingPlaceSheet, MJIBuildingPlaceRow, "MJIBuildingPlace");
