// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MJIStockyardManagementAreaRow);
impl MJIStockyardManagementAreaRow {
    u16_field!(area, 0);
    u8_field!(rare_material, 1);
    u8_field!(unknown_0, 2);
}

define_sheet!(MJIStockyardManagementAreaSheet, MJIStockyardManagementAreaRow, "MJIStockyardManagementArea");
