// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(MJIFarmPastureRankRankData, 9);
impl<'a> MJIFarmPastureRankRankData<'a> {
    array_field!(sgb, 0, 4, MJIFarmPastureRankRankData);
    u32_field!(unknown_0, 28);
    u32_field!(unknown_1, 32);
    u16_field!(unknown_2, 40);
    u16_field!(unknown_3, 44);
    u8_field!(unknown_4, 16);
    u8_field!(unknown_5, 20);
    u8_field!(unknown_6, 24);
    u8_field!(unknown_7, 36);
}

define_subrow!(MJIFarmPastureRankRankDataSGB, 1);
impl<'a> MJIFarmPastureRankRankDataSGB<'a> {
    u32_field!(field_0, 0);
}


define_row!(MJIFarmPastureRankRow);
impl MJIFarmPastureRankRow {
    array_field!(rank_data, 0, 4, MJIFarmPastureRankRankData);
}

define_sheet!(MJIFarmPastureRankSheet, MJIFarmPastureRankRow, "MJIFarmPastureRank", no_language_support);
