// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MKDTraitRow);
impl MKDTraitRow {
    string_field!(name, 0);
    string_field!(description, 1);
    i32_field!(icon, 2);
    u8_field!(mkd_support_job, 3);
    u8_field!(level_unlock, 4);
}

define_sheet!(MKDTraitSheet, MKDTraitRow, "MKDTrait");
