// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MKDRelicGrowth2ContentListRow);
impl MKDRelicGrowth2ContentListRow {
    string_field!(description, 0);
    u32_field!(unknown_1, 1);
    u32_field!(level, 2);
    u8_field!(category, 3);
}

define_sheet!(MKDRelicGrowth2ContentListSheet, MKDRelicGrowth2ContentListRow, "MKDRelicGrowth2ContentList");
