// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MobHuntOrderRow);
impl MobHuntOrderRow {
    u16_field!(target, 0);
    u8_field!(needed_kills, 1);
    u8_field!(type_, 2);
    u8_field!(rank, 3);
    u8_field!(mob_hunt_reward, 4);
}

define_sheet!(MobHuntOrderSheet, MobHuntOrderRow, "MobHuntOrder");
