// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MobHuntOrderTypeRow);
impl MobHuntOrderTypeRow {
    u32_field!(quest, 1);
    u32_field!(event_item, 2);
    u16_field!(order_start, 3);
    u8_field!(type_, 0);
    u8_field!(order_amount, 4);
}

define_sheet!(MobHuntOrderTypeSheet, MobHuntOrderTypeRow, "MobHuntOrderType", no_language_support);
