// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MobHuntRewardRow);
impl MobHuntRewardRow {
    u32_field!(exp_reward, 0);
    u16_field!(gil_reward, 1);
    u16_field!(currency_reward, 3);
    u8_field!(expansion, 2);
}

define_sheet!(MobHuntRewardSheet, MobHuntRewardRow, "MobHuntReward");
