// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ModelStateRow);
impl ModelStateRow {
    u16_field!(start, 0);
    u8_field!(unknown_0, 1);
}

define_sheet!(ModelStateSheet, ModelStateRow, "ModelState");
