// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ModelCharaRow);
impl ModelCharaRow {
    f32_field!(unknown_0, 0);
    f32_field!(unknown_1, 1);
    f32_field!(unknown_15, 2);
    u16_field!(model, 3);
    u16_field!(se_pack, 4);
    u8_field!(type_, 5);
    u8_field!(base, 6);
    u8_field!(variant, 7);
    u8_field!(unknown_2, 8);
    u8_field!(unknown_3, 9);
    u8_field!(unknown_4, 10);
    u8_field!(unknown_5, 11);
    u8_field!(unknown_14, 12);
    u8_field!(unknown_70, 13);
    i8_field!(unknown_6, 14);
    bool_field!(unknown_7, 15);
    bool_field!(pap_variation, 16);
    bool_field!(unknown_8, 17);
    bool_field!(unknown_9, 18);
    bool_field!(unknown_10, 19);
    bool_field!(unknown_11, 20);
    bool_field!(unknown_12, 21);
    bool_field!(unknown_13, 22);
}

define_sheet!(ModelCharaSheet, ModelCharaRow, "ModelChara");
