// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(MonsterNoteMonsterNoteTarget, 1);
impl<'a> MonsterNoteMonsterNoteTarget<'a> {
    string_field!(field_0, 9);
}

define_subrow!(MonsterNoteCount, 1);
impl<'a> MonsterNoteCount<'a> {
    string_field!(field_0, 9);
}


define_row!(MonsterNoteRow);
impl MonsterNoteRow {
    string_field!(name, 9);
    u32_field!(reward, 8);
    array_field!(monster_note_target, 2, 4, MonsterNoteMonsterNoteTarget);
    array_field!(count, 6, 4, MonsterNoteCount);
}

define_sheet!(MonsterNoteSheet, MonsterNoteRow, "MonsterNote", language_support);
