// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(MountActionAction, 1);
impl<'a> MountActionAction<'a> {
    u16_field!(field_0, 0);
}


define_row!(MountActionRow);
impl MountActionRow {
    array_field!(action, 0, 6, MountActionAction);
}

define_sheet!(MountActionSheet, MountActionRow, "MountAction");
