// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MountCustomizeRow);
impl MountCustomizeRow {
    u16_field!(hyur_midlander_male_scale, 0);
    u16_field!(hyur_midlander_female_scale, 1);
    u16_field!(hyur_highlander_male_scale, 2);
    u16_field!(hyur_highlander_female_scale, 3);
    u16_field!(elezen_male_scale, 4);
    u16_field!(elezen_female_scale, 5);
    u16_field!(lala_male_scale, 6);
    u16_field!(lala_female_scale, 7);
    u16_field!(miqo_male_scale, 8);
    u16_field!(miqo_female_scale, 9);
    u16_field!(roe_male_scale, 10);
    u16_field!(roe_female_scale, 11);
    u16_field!(au_ra_male_scale, 12);
    u16_field!(au_ra_female_scale, 13);
    u16_field!(hrothgar_male_scale, 14);
    u16_field!(hrothgar_female_scale, 15);
    u16_field!(viera_male_scale, 16);
    u16_field!(viera_female_scale, 17);
    u16_field!(hyur_midlander_male_camera_height, 18);
    u16_field!(hyur_midlander_female_camera_height, 19);
    u16_field!(hyur_highlander_male_camera_height, 20);
    u8_field!(hyur_highlander_female_camera_height, 21);
    u8_field!(elezen_male_camera_height, 22);
    u8_field!(elezen_female_camera_height, 23);
    u8_field!(lala_male_camera_height, 24);
    u8_field!(lala_female_camera_height, 25);
    u8_field!(miqo_male_camera_height, 26);
    u8_field!(miqo_female_camera_height, 27);
    u8_field!(roe_male_camera_height, 28);
    u8_field!(roe_female_camera_height, 29);
    u8_field!(au_ra_male_camera_height, 30);
    u8_field!(au_ra_female_camera_height, 31);
    u8_field!(hrothgar_male_camera_height, 32);
    u8_field!(hrothgar_female_camera_height, 33);
    u8_field!(viera_male_camera_height, 34);
    u8_field!(viera_female_camera_height, 35);
    u8_field!(unknown_0, 36);
    u8_field!(unknown_1, 37);
    u8_field!(unknown_70_1, 38);
    u8_field!(unknown_70_2, 39);
    u8_field!(unknown_2, 40);
    u8_field!(unknown_3, 41);
    bool_field!(unknown_4, 42);
}

define_sheet!(MountCustomizeSheet, MountCustomizeRow, "MountCustomize");
