// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MountFlyingConditionRow);
impl MountFlyingConditionRow {
    u32_field!(quest, 0);
}

define_sheet!(MountFlyingConditionSheet, MountFlyingConditionRow, "MountFlyingCondition");
