// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MoveTimelineRow);
impl MoveTimelineRow {
    u16_field!(idle, 0);
    u16_field!(move_forward, 1);
    u16_field!(move_back, 2);
    u16_field!(move_left, 3);
    u16_field!(move_right, 4);
    u16_field!(move_up, 5);
    u16_field!(move_down, 6);
    u16_field!(move_turn_left, 7);
    u16_field!(move_turn_right, 8);
    u16_field!(extra, 9);
}

define_sheet!(MoveTimelineSheet, MoveTimelineRow, "MoveTimeline", no_language_support);
