// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(MovieSubtitle500Row);
impl MovieSubtitle500Row {
    f32_field!(start_time, 0);
    f32_field!(end_time, 1);
}

define_sheet!(MovieSubtitle500Sheet, MovieSubtitle500Row, "MovieSubtitle500");
