// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(NotebookDivisionSecretRecipeBookGroups, 1);
impl<'a> NotebookDivisionSecretRecipeBookGroups<'a> {
    string_field!(field_0, 0);
}

define_subrow!(NotebookDivisionAllowedCraftTypes, 1);
impl<'a> NotebookDivisionAllowedCraftTypes<'a> {
    string_field!(field_0, 0);
}


define_row!(NotebookDivisionRow);
impl NotebookDivisionRow {
    string_field!(name, 0);
    u32_field!(quest_unlock, 1);
    u8_field!(notebook_division_category, 2);
    u8_field!(craft_opening_level, 3);
    u8_field!(gathering_opening_level, 4);
    u8_field!(unknown_0, 5);
    array_field!(secret_recipe_book_groups, 6, 2, NotebookDivisionSecretRecipeBookGroups);
    // Index is CraftType
    array_field!(allowed_craft_types, 8, 8, NotebookDivisionAllowedCraftTypes);
    bool_field!(requires_secret_recipe_book_group_unlock, 16);
}

define_sheet!(NotebookDivisionSheet, NotebookDivisionRow, "NotebookDivision");
