// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(NotebookDivisionCategoryRow);
impl NotebookDivisionCategoryRow {
    string_field!(name, 0);
    u8_field!(index, 1);
}

define_sheet!(NotebookDivisionCategorySheet, NotebookDivisionCategoryRow, "NotebookDivisionCategory", language_support);
