// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(NotoriousMonsterRow);
impl NotoriousMonsterRow {
    u32_field!(b_npc_name, 0);
    i32_field!(b_npc_base, 1);
    u16_field!(unknown_0, 2);
    u8_field!(rank, 3);
}

define_sheet!(NotoriousMonsterSheet, NotoriousMonsterRow, "NotoriousMonster");
