// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(NotoriousMonsterTerritoryNotoriousMonsters, 1);
impl<'a> NotoriousMonsterTerritoryNotoriousMonsters<'a> {
    u16_field!(field_0, 0);
}


define_row!(NotoriousMonsterTerritoryRow);
impl NotoriousMonsterTerritoryRow {
    array_field!(notorious_monsters, 0, 10, NotoriousMonsterTerritoryNotoriousMonsters);
}

define_sheet!(NotoriousMonsterTerritorySheet, NotoriousMonsterTerritoryRow, "NotoriousMonsterTerritory", no_language_support);
