// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(NpcEquipRow);
impl NpcEquipRow {
    u64_field!(model_main_hand, 0);
    u64_field!(model_off_hand, 1);
    u32_field!(model_head, 2);
    u32_field!(model_body, 3);
    u32_field!(model_hands, 4);
    u32_field!(model_legs, 5);
    u32_field!(model_feet, 6);
    u32_field!(model_ears, 7);
    u32_field!(model_neck, 8);
    u32_field!(model_wrists, 9);
    u32_field!(model_left_ring, 10);
    u32_field!(model_right_ring, 11);
    u16_field!(unknown_70_1, 12);
    u16_field!(unknown_70_2, 13);
    u8_field!(dye_main_hand, 14);
    u8_field!(dye_2_main_hand, 15);
    u8_field!(dye_off_hand, 16);
    u8_field!(dye_2_off_hand, 17);
    u8_field!(dye_head, 18);
    u8_field!(dye_body, 19);
    u8_field!(dye_hands, 20);
    u8_field!(dye_legs, 21);
    u8_field!(dye_feet, 22);
    u8_field!(dye_ears, 23);
    u8_field!(dye_neck, 24);
    u8_field!(dye_wrists, 25);
    u8_field!(dye_left_ring, 26);
    u8_field!(dye_right_ring, 27);
    u8_field!(dye_2_head, 28);
    u8_field!(dye_2_body, 29);
    u8_field!(dye_2_hands, 30);
    u8_field!(dye_2_legs, 31);
    u8_field!(dye_2_feet, 32);
    u8_field!(dye_2_ears, 33);
    u8_field!(dye_2_neck, 34);
    u8_field!(dye_2_wrists, 35);
    u8_field!(dye_2_left_ring, 36);
    u8_field!(dye_2_right_ring, 37);
    bool_field!(visor, 38);
    bool_field!(unknown_0, 39);
}

define_sheet!(NpcEquipSheet, NpcEquipRow, "NpcEquip");
