// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(OmenRow);
impl OmenRow {
    string_field!(path, 0);
    string_field!(path_ally, 1);
    u8_field!(type_, 2);
    i8_field!(unknown_0, 3);
    bool_field!(restrict_y_scale, 4);
    bool_field!(large_scale, 5);
}

define_sheet!(OmenSheet, OmenRow, "Omen");
