// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(OnlineStatusRow);
impl OnlineStatusRow {
    string_field!(name, 0);
    u32_field!(icon, 1);
    i32_field!(unknown_0, 2);
    u8_field!(priority, 3);
    bool_field!(unknown_1, 4);
    bool_field!(list, 5);
    bool_field!(unknown_2, 6);
}

define_sheet!(OnlineStatusSheet, OnlineStatusRow, "OnlineStatus");
