// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(OpenContentOpenContentData, 2);
impl<'a> OpenContentOpenContentData<'a> {
    u32_field!(candidate_name, 0);
    u16_field!(content, 1);
}


define_row!(OpenContentRow);
impl OpenContentRow {
    array_field!(open_content_data, 0, 16, OpenContentOpenContentData);
}

define_sheet!(OpenContentSheet, OpenContentRow, "OpenContent", no_language_support);
