// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(OpeningVariables, 2);
impl<'a> OpeningVariables<'a> {
    string_field!(name, 0);
    u32_field!(value, 1);
}


define_row!(OpeningRow);
impl OpeningRow {
    array_field!(variables, 0, 40, OpeningVariables);
    string_field!(name, 80);
    u32_field!(quest, 81);
}

define_sheet!(OpeningSheet, OpeningRow, "Opening");
