// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(OrchestrionUiparamRow);
impl OrchestrionUiparamRow {
    u16_field!(order, 1);
    u8_field!(orchestrion_category, 0);
}

define_sheet!(OrchestrionUiparamSheet, OrchestrionUiparamRow, "OrchestrionUiparam", no_language_support);
