// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(OrnamentActionActions, 1);
impl<'a> OrnamentActionActions<'a> {
    u16_field!(field_0, 0);
}


define_row!(OrnamentActionRow);
impl OrnamentActionRow {
    array_field!(actions, 0, 6, OrnamentActionActions);
}

define_sheet!(OrnamentActionSheet, OrnamentActionRow, "OrnamentAction", no_language_support);
