// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(OrnamentRow);
impl OrnamentRow {
    string_field!(singular, 8);
    string_field!(plural, 10);
    i8_field!(adjective, 9);
    i8_field!(possessive_pronoun, 11);
    i8_field!(starts_with_vowel, 12);
    i8_field!(unknown_0, 13);
    i8_field!(pronoun, 14);
    i8_field!(article, 15);
    u16_field!(model, 0);
    u16_field!(action, 4);
    u16_field!(icon, 6);
    u16_field!(transient, 7);
    i16_field!(order, 5);
    u8_field!(attachment_point, 1);
    u8_field!(unknown_3, 2);
    u8_field!(unknown_4, 3);
}

define_sheet!(OrnamentSheet, OrnamentRow, "Ornament");
