// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(PartyContentLGBEventObject, 1);
impl<'a> PartyContentLGBEventObject<'a> {
    u32_field!(field_0, 0);
}

define_subrow!(PartyContentLGBEventRange, 1);
impl<'a> PartyContentLGBEventRange<'a> {
    u32_field!(field_0, 0);
}

define_subrow!(PartyContentLGBEventObject2, 1);
impl<'a> PartyContentLGBEventObject2<'a> {
    u32_field!(field_0, 0);
}


define_row!(PartyContentRow);
impl PartyContentRow {
    array_field!(lgb_event_object, 0, 9, PartyContentLGBEventObject);
    array_field!(lgb_event_range, 9, 9, PartyContentLGBEventRange);
    array_field!(lgb_event_object_2, 18, 9, PartyContentLGBEventObject2);
    u32_field!(text_data_start, 3);
    u32_field!(text_data_end, 4);
    u32_field!(image, 34);
    u16_field!(time_limit, 1);
    u16_field!(unknown_0, 32);
    u16_field!(content_finder_condition, 33);
    u8_field!(key, 0);
    u8_field!(unknown_1, 35);
    bool_field!(name, 2);
}

define_sheet!(PartyContentSheet, PartyContentRow, "PartyContent", no_language_support);
