// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(PerformGuideScoreRow);
impl PerformGuideScoreRow {
    string_field!(unknown_0, 2);
    string_field!(unknown_1, 0);
    u8_field!(unknown_2, 1);
}

define_sheet!(PerformGuideScoreSheet, PerformGuideScoreRow, "PerformGuideScore");
