// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(PhysicsGroupSimulationTime, 1);
impl<'a> PhysicsGroupSimulationTime<'a> {
    f32_field!(field_0, 0);
}

define_subrow!(PhysicsGroupPS3SimulationTime, 1);
impl<'a> PhysicsGroupPS3SimulationTime<'a> {
    f32_field!(field_0, 0);
}

define_subrow!(PhysicsGroupConfigSwitch, 1);
impl<'a> PhysicsGroupConfigSwitch<'a> {
    f32_field!(field_0, 0);
}


define_row!(PhysicsGroupRow);
impl PhysicsGroupRow {
    array_field!(simulation_time, 0, 6, PhysicsGroupSimulationTime);
    array_field!(ps_3_simulation_time, 6, 6, PhysicsGroupPS3SimulationTime);
    f32_field!(root_following_game, 13);
    f32_field!(root_following_cut_scene, 14);
    array_field!(config_switch, 14, 3, PhysicsGroupConfigSwitch);
    bool_field!(reset_by_look_at, 12);
    bool_field!(force_attract_by_physics_off, 18);
}

define_sheet!(PhysicsGroupSheet, PhysicsGroupRow, "PhysicsGroup", no_language_support);
