// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(PictureRow);
impl PictureRow {
    i32_field!(image, 0);
    i32_field!(signature, 1);
}

define_sheet!(PictureSheet, PictureRow, "Picture", no_language_support);
