// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(PlantPotFlowerSeedSeedIcon, 1);
impl<'a> PlantPotFlowerSeedSeedIcon<'a> {
    u32_field!(field_0, 0);
}


define_row!(PlantPotFlowerSeedRow);
impl PlantPotFlowerSeedRow {
    array_field!(seed_icon, 0, 9, PlantPotFlowerSeedSeedIcon);
}

define_sheet!(PlantPotFlowerSeedSheet, PlantPotFlowerSeedRow, "PlantPotFlowerSeed", no_language_support);
