// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(PointMenuStringRow);
impl PointMenuStringRow {
    string_field!(unknown_0, 0);
}

define_sheet!(PointMenuStringSheet, PointMenuStringRow, "PointMenuString", language_support);
