// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(PointMenuChoiceRow);
impl PointMenuChoiceRow {
    f32_field!(unknown_0, 0);
    f32_field!(unknown_1, 1);
    f32_field!(unknown_2, 4);
    f32_field!(unknown_3, 5);
    f32_field!(unknown_4, 6);
    f32_field!(unknown_5, 7);
    u16_field!(unknown_6, 12);
    u8_field!(unknown_7, 2);
    u8_field!(unknown_8, 3);
    u8_field!(unknown_9, 8);
    u8_field!(unknown_10, 9);
    u8_field!(unknown_11, 10);
    u8_field!(unknown_12, 11);
}

define_sheet!(PointMenuChoiceSheet, PointMenuChoiceRow, "PointMenuChoice", no_language_support);
