// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(PointMenuRow);
impl PointMenuRow {
    string_field!(unknown_0, 1);
    u32_field!(unknown_1, 0);
}

define_sheet!(PointMenuSheet, PointMenuRow, "PointMenu", language_support);
