// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(PreHandlerMovementRow);
impl PreHandlerMovementRow {
    u16_field!(unknown_0, 1);
    u8_field!(unknown_1, 0);
}

define_sheet!(PreHandlerMovementSheet, PreHandlerMovementRow, "PreHandlerMovement", no_language_support);
