// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(PvPActionSortRow);
impl PvPActionSortRow {
    i32_field!(unknown_0, 0);
    u16_field!(action, 1);
    u8_field!(action_type, 2);
    bool_field!(unknown_1, 3);
    bool_field!(unknown_2, 4);
}

define_sheet!(PvPActionSortSheet, PvPActionSortRow, "PvPActionSort");
