// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(PvPRankTransientRow);
impl PvPRankTransientRow {
    string_field!(unknown_0, 0);
    string_field!(unknown_1, 1);
    string_field!(unknown_2, 2);
    string_field!(unknown_3, 3);
    string_field!(unknown_4, 4);
    string_field!(unknown_5, 5);
}

define_sheet!(PvPRankTransientSheet, PvPRankTransientRow, "PvPRankTransient", language_support);
