// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(PvPSeriesLevelRow);
impl PvPSeriesLevelRow {
    u16_field!(exp_to_next, 0);
}

define_sheet!(PvPSeriesLevelSheet, PvPSeriesLevelRow, "PvPSeriesLevel", no_language_support);
