// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(PvPActionGrandCompany, 1);
impl<'a> PvPActionGrandCompany<'a> {
    u16_field!(field_0, 0);
}


define_row!(PvPActionRow);
impl PvPActionRow {
    u16_field!(action, 0);
    u16_field!(unknown_0, 1);
    u16_field!(unknown_1, 2);
    u16_field!(unknown_2, 3);
    u8_field!(unknown_3, 4);
    u8_field!(unknown_4, 5);
    array_field!(grand_company, 6, 3, PvPActionGrandCompany);
}

define_sheet!(PvPActionSheet, PvPActionRow, "PvPAction");
