// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(QuestRedoIncompChapterRow);
impl QuestRedoIncompChapterRow {
    u16_field!(chapter, 0);
}

define_sheet!(QuestRedoIncompChapterSheet, QuestRedoIncompChapterRow, "QuestRedoIncompChapter");
