// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(QuestBattleSystemDefineRow);
impl QuestBattleSystemDefineRow {
    string_field!(unknown_0, 0);
    u32_field!(unknown_1, 1);
}

define_sheet!(QuestBattleSystemDefineSheet, QuestBattleSystemDefineRow, "QuestBattleSystemDefine", no_language_support);
