// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(QuestSubCommandRow);
impl QuestSubCommandRow {
    u32_field!(unknown_0, 16);
    u32_field!(unknown_1, 17);
    u32_field!(unknown_2, 18);
    u32_field!(unknown_3, 19);
    u32_field!(unknown_4, 20);
    u32_field!(unknown_5, 21);
    u32_field!(unknown_6, 22);
    u32_field!(unknown_7, 23);
    u8_field!(unknown_8, 0);
    u8_field!(unknown_9, 1);
    u8_field!(unknown_10, 2);
    u8_field!(unknown_11, 3);
    u8_field!(unknown_12, 4);
    u8_field!(unknown_13, 5);
    u8_field!(unknown_14, 6);
    u8_field!(unknown_15, 7);
    u8_field!(unknown_16, 8);
    u8_field!(unknown_17, 9);
    u8_field!(unknown_18, 10);
    u8_field!(unknown_19, 11);
    u8_field!(unknown_20, 12);
    u8_field!(unknown_21, 13);
    u8_field!(unknown_22, 14);
    u8_field!(unknown_23, 15);
}

define_sheet!(QuestSubCommandSheet, QuestSubCommandRow, "QuestSubCommand");
