// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(QuestAcceptAdditionConditionRow);
impl QuestAcceptAdditionConditionRow {
    u32_field!(requirement_0, 0);
    u32_field!(requirement_1, 1);
    u32_field!(unknown_0, 2);
    bool_field!(unknown_2, 3);
    bool_field!(unknown_1, 4);
}

define_sheet!(QuestAcceptAdditionConditionSheet, QuestAcceptAdditionConditionRow, "QuestAcceptAdditionCondition");
