// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(QuestSystemDefineRow);
impl QuestSystemDefineRow {
    string_field!(unknown_0, 0);
    i32_field!(unknown_1, 1);
}

define_sheet!(QuestSystemDefineSheet, QuestSystemDefineRow, "QuestSystemDefine", no_language_support);
