// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(QuestLinkMarkerSetRow);
impl QuestLinkMarkerSetRow {
    u32_field!(unknown_0, 1);
    u16_field!(unknown_1, 0);
    u8_field!(unknown_2, 2);
    u8_field!(unknown_3, 3);
    u8_field!(unknown_4, 4);
    bool_field!(unknown_5, 5);
    bool_field!(unknown_6, 6);
}

define_sheet!(QuestLinkMarkerSetSheet, QuestLinkMarkerSetRow, "QuestLinkMarkerSet", no_language_support);
