// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(QuestRedoValidCustomTalkRow);
impl QuestRedoValidCustomTalkRow {
    u32_field!(unknown_0, 0);
}

define_sheet!(QuestRedoValidCustomTalkSheet, QuestRedoValidCustomTalkRow, "QuestRedoValidCustomTalk", no_language_support);
