// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(QuestBattleResidentRow);
impl QuestBattleResidentRow {
    u16_field!(unknown_0, 0);
}

define_sheet!(QuestBattleResidentSheet, QuestBattleResidentRow, "QuestBattleResident", no_language_support);
