// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(RacingChocoboNameCategoryRow);
impl RacingChocoboNameCategoryRow {
    string_field!(name, 1);
    u8_field!(sort_key, 0);
}

define_sheet!(RacingChocoboNameCategorySheet, RacingChocoboNameCategoryRow, "RacingChocoboNameCategory", language_support);
