// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(RecastNavimeshRow);
impl RecastNavimeshRow {
    string_field!(unknown_0, 0);
    f32_field!(tile_size, 1);
    f32_field!(cell_size, 2);
    f32_field!(cell_height, 3);
    f32_field!(agent_height, 4);
    f32_field!(agent_radius, 5);
    f32_field!(agent_max_climb, 6);
    f32_field!(agent_max_slope, 7);
    f32_field!(region_min_size, 8);
    f32_field!(region_merged_size, 9);
    f32_field!(max_edge_length, 10);
    f32_field!(max_edge_error, 11);
    f32_field!(verts_per_poly, 12);
    f32_field!(detail_mesh_sample_distance, 13);
    f32_field!(detail_mesh_max_sample_error, 14);
    f32_field!(unknown_1, 15);
    f32_field!(unknown_2, 16);
    f32_field!(unknown_3, 17);
    f32_field!(unknown_4, 18);
    f32_field!(unknown_5, 19);
    f32_field!(unknown_6, 20);
    f32_field!(unknown_7, 21);
    f32_field!(unknown_8, 22);
    f32_field!(unknown_9, 23);
    f32_field!(unknown_10, 24);
    f32_field!(unknown_11, 25);
    f32_field!(unknown_12, 26);
    f32_field!(unknown_13, 27);
    f32_field!(unknown_14, 28);
    f32_field!(unknown_15, 29);
    f32_field!(unknown_16, 30);
    bool_field!(unknown_17, 31);
    bool_field!(unknown_18, 32);
    bool_field!(unknown_19, 33);
    bool_field!(unknown_20, 34);
}

define_sheet!(RecastNavimeshSheet, RecastNavimeshRow, "RecastNavimesh");
