// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(RecipeLookupRow);
impl RecipeLookupRow {
    u16_field!(crp, 0);
    u16_field!(bsm, 1);
    u16_field!(arm, 2);
    u16_field!(gsm, 3);
    u16_field!(ltw, 4);
    u16_field!(wvr, 5);
    u16_field!(alc, 6);
    u16_field!(cul, 7);
}

define_sheet!(RecipeLookupSheet, RecipeLookupRow, "RecipeLookup");
