// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(RecipeSubCategoryRow);
impl RecipeSubCategoryRow {
    string_field!(unknown_0, 1);
    u8_field!(unknown_1, 0);
}

define_sheet!(RecipeSubCategorySheet, RecipeSubCategoryRow, "RecipeSubCategory", language_support);
