// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(Relic3Row);
impl Relic3Row {
    u32_field!(item_animus, 0);
    u32_field!(item_scroll, 1);
    u32_field!(item_novus, 3);
    i32_field!(icon, 4);
    u8_field!(materia_limit, 2);
    i8_field!(unknown_0, 5);
}

define_sheet!(Relic3Sheet, Relic3Row, "Relic3", no_language_support);
