// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(RelicNoteMonsterNoteTargetCommon, 1);
impl<'a> RelicNoteMonsterNoteTargetCommon<'a> {
    u32_field!(field_0, 0);
}

define_element!(RelicNoteMonsterNoteTargetNM, 1);
impl<'a> RelicNoteMonsterNoteTargetNM<'a> {
    u32_field!(field_0, 0);
}

define_element!(RelicNoteFate, 1);
impl<'a> RelicNoteFate<'a> {
    u32_field!(field_0, 0);
}

define_element!(RelicNotePlaceNameFate, 1);
impl<'a> RelicNotePlaceNameFate<'a> {
    u32_field!(field_0, 0);
}

define_element!(RelicNoteLeve, 1);
impl<'a> RelicNoteLeve<'a> {
    u32_field!(field_0, 0);
}

define_element!(RelicNoteMonsterCount, 1);
impl<'a> RelicNoteMonsterCount<'a> {
    u32_field!(field_0, 0);
}


define_row!(RelicNoteRow);
impl RelicNoteRow {
    u32_field!(event_item, 0);
    array_field!(monster_note_target_common, 1, 10, RelicNoteMonsterNoteTargetCommon);
    array_field!(monster_note_target_nm, 11, 3, RelicNoteMonsterNoteTargetNM);
    u16_field!(unknown_0, 24);
    array_field!(fate, 15, 3, RelicNoteFate);
    array_field!(place_name_fate, 18, 3, RelicNotePlaceNameFate);
    array_field!(leve, 21, 3, RelicNoteLeve);
    array_field!(monster_count, 24, 10, RelicNoteMonsterCount);
}

define_sheet!(RelicNoteSheet, RelicNoteRow, "RelicNote", no_language_support);
