// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(ReplaceActionReplaceActions, 1);
impl<'a> ReplaceActionReplaceActions<'a> {
    i32_field!(field_0, 0);
}


define_row!(ReplaceActionRow);
impl ReplaceActionRow {
    i32_field!(action, 0);
    array_field!(replace_actions, 1, 4, ReplaceActionReplaceActions);
    i16_field!(param_1, 2);
    i16_field!(param_2, 5);
    i16_field!(param_3, 8);
    i16_field!(param_4, 11);
    i8_field!(type_1, 1);
    i8_field!(type_2, 4);
    i8_field!(type_3, 7);
    i8_field!(type_4, 10);
    i8_field!(replace_settable, 13);
    bool_field!(unknown_70, 14);
}

define_sheet!(ReplaceActionSheet, ReplaceActionRow, "ReplaceAction");
