// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ResidentRow);
impl ResidentRow {
    u64_field!(model, 0);
    i32_field!(npc_yell, 1);
    u16_field!(unknown_0, 2);
    u8_field!(unknown_1, 3);
    u8_field!(resident_motion_type, 4);
}

define_sheet!(ResidentSheet, ResidentRow, "Resident");
