// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(ResistanceWeaponAdjustBaseParam, 1);
impl<'a> ResistanceWeaponAdjustBaseParam<'a> {
    u32_field!(field_0, 0);
}


define_row!(ResistanceWeaponAdjustRow);
impl ResistanceWeaponAdjustRow {
    u32_field!(image, 0);
    u16_field!(max_total_stats, 1);
    u16_field!(max_each_stat, 2);
    array_field!(base_param, 3, 4, ResistanceWeaponAdjustBaseParam);
    u8_field!(unknown_0, 7);
}

define_sheet!(ResistanceWeaponAdjustSheet, ResistanceWeaponAdjustRow, "ResistanceWeaponAdjust");
