// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ResidentMotionTypeRow);
impl ResidentMotionTypeRow {
    string_field!(unknown_0, 0);
    string_field!(unknown_1, 1);
    string_field!(unknown_2, 2);
    string_field!(unknown_3, 3);
    string_field!(unknown_4, 4);
    string_field!(unknown_5, 5);
    string_field!(unknown_6, 6);
    string_field!(unknown_7, 7);
}

define_sheet!(ResidentMotionTypeSheet, ResidentMotionTypeRow, "ResidentMotionType");
