// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(RetainerTaskNormalQuantity, 1);
impl<'a> RetainerTaskNormalQuantity<'a> {
    i32_field!(field_0, 0);
}


define_row!(RetainerTaskNormalRow);
impl RetainerTaskNormalRow {
    i32_field!(item, 0);
    i16_field!(gathering_log, 6);
    i16_field!(fishing_log, 7);
    array_field!(quantity, 3, 5, RetainerTaskNormalQuantity);
}

define_sheet!(RetainerTaskNormalSheet, RetainerTaskNormalRow, "RetainerTaskNormal", no_language_support);
