// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(RetainerTaskParameterItemLevelDoW, 1);
impl<'a> RetainerTaskParameterItemLevelDoW<'a> {
    i16_field!(field_0, 0);
}

define_element!(RetainerTaskParameterPerceptionDoL, 1);
impl<'a> RetainerTaskParameterPerceptionDoL<'a> {
    i16_field!(field_0, 0);
}

define_element!(RetainerTaskParameterPerceptionFSH, 1);
impl<'a> RetainerTaskParameterPerceptionFSH<'a> {
    i16_field!(field_0, 0);
}


define_row!(RetainerTaskParameterRow);
impl RetainerTaskParameterRow {
    array_field!(item_level_do_w, 0, 4, RetainerTaskParameterItemLevelDoW);
    array_field!(perception_do_l, 4, 4, RetainerTaskParameterPerceptionDoL);
    array_field!(perception_fsh, 8, 4, RetainerTaskParameterPerceptionFSH);
}

define_sheet!(RetainerTaskParameterSheet, RetainerTaskParameterRow, "RetainerTaskParameter", no_language_support);
