// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(RetainerTaskRandomRow);
impl RetainerTaskRandomRow {
    string_field!(name, 0);
    i16_field!(requirement, 1);
}

define_sheet!(RetainerTaskRandomSheet, RetainerTaskRandomRow, "RetainerTaskRandom");
