// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(RideShootingTextDataRow);
impl RideShootingTextDataRow {
    string_field!(string, 0);
}

define_sheet!(RideShootingTextDataSheet, RideShootingTextDataRow, "RideShootingTextData");
