// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(RideShootingRideShootingParams, 14);
impl<'a> RideShootingRideShootingParams<'a> {
    u32_field!(unknown_0, 6);
    u32_field!(pop_range, 14);
    u32_field!(e_npc, 22);
    u32_field!(unknown_1, 38);
    u32_field!(unknown_2, 54);
    u32_field!(unknown_3, 70);
    u32_field!(unknown_4, 86);
    u32_field!(unknown_5, 102);
    u8_field!(e_npc_scale, 30);
    u8_field!(unknown_6, 46);
    u8_field!(unknown_7, 62);
    u8_field!(unknown_8, 78);
    u8_field!(unknown_9, 94);
    u8_field!(unknown_10, 110);
}


define_row!(RideShootingRow);
impl RideShootingRow {
    array_field!(ride_shooting_params, 0, 8, RideShootingRideShootingParams);
    u16_field!(g_fate_ride_shooting, 0);
    u16_field!(unknown_0, 3);
    u16_field!(unknown_1, 4);
    u16_field!(start_text, 5);
    i16_field!(unknown_2, 1);
    i16_field!(unknown_3, 2);
}

define_sheet!(RideShootingSheet, RideShootingRow, "RideShooting");
