// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(RideShootingTargetRow);
impl RideShootingTargetRow {
    u32_field!(unknown_0, 0);
    u32_field!(unknown_1, 1);
    u32_field!(unknown_2, 2);
    u8_field!(unknown_3, 3);
    u8_field!(unknown_4, 4);
    u8_field!(unknown_5, 5);
}

define_sheet!(RideShootingTargetSheet, RideShootingTargetRow, "RideShootingTarget");
