// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(RoleRow);
impl RoleRow {
    // 1 &#x3D; Tank, 2 &#x3D; DPS, 3 &#x3D; Healer
    u8_field!(type_, 0);
}

define_sheet!(RoleSheet, RoleRow, "Role", no_language_support);
