// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(RPParameterRow);
impl RPParameterRow {
    u16_field!(b_npc_name, 0);
    u8_field!(class_job, 1);
    u8_field!(sex, 2);
}

define_sheet!(RPParameterSheet, RPParameterRow, "RPParameter", no_language_support);
