// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(SatisfactionNpcSatisfactionNpcParams, 5);
impl<'a> SatisfactionNpcSatisfactionNpcParams<'a> {
    i32_field!(supply_index, 0);
    array_field!(item, 1, 3, SatisfactionNpcSatisfactionNpcParams);
    u16_field!(satisfaction_required, 4);
    array_field!(item_count, 5, 3, SatisfactionNpcSatisfactionNpcParams);
    array_field!(is_hq, 8, 3, SatisfactionNpcSatisfactionNpcParams);
}

define_element!(SatisfactionNpcSatisfactionNpcParamsItem, 1);
impl<'a> SatisfactionNpcSatisfactionNpcParamsItem<'a> {
    i32_field!(field_0, 0);
}

define_element!(SatisfactionNpcSatisfactionNpcParamsItemCount, 1);
impl<'a> SatisfactionNpcSatisfactionNpcParamsItemCount<'a> {
    i32_field!(field_0, 0);
}

define_element!(SatisfactionNpcSatisfactionNpcParamsIsHQ, 1);
impl<'a> SatisfactionNpcSatisfactionNpcParamsIsHQ<'a> {
    i32_field!(field_0, 0);
}

define_element!(SatisfactionNpcRankParams, 3);
impl<'a> SatisfactionNpcRankParams<'a> {
    i32_field!(image_id, 0);
    i32_field!(unknown_1, 1);
    i32_field!(quest, 2);
}


define_row!(SatisfactionNpcRow);
impl SatisfactionNpcRow {
    array_field!(satisfaction_npc_params, 0, 6, SatisfactionNpcSatisfactionNpcParams);
    array_field!(rank_params, 66, 6, SatisfactionNpcRankParams);
    u32_field!(level, 88);
    i32_field!(npc, 0);
    i32_field!(quest_required, 1);
    i32_field!(icon, 89);
    u8_field!(level_unlock, 2);
    u8_field!(deliveries_per_week, 3);
    u8_field!(glamour_index, 90);
    u8_field!(unknown_19, 91);
    u8_field!(unknown_20, 92);
}

define_sheet!(SatisfactionNpcSheet, SatisfactionNpcRow, "SatisfactionNpc", no_language_support);
