// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(SatisfactionSupplyRewardExpRow);
impl SatisfactionSupplyRewardExpRow {
    u8_field!(percent_of_level_low, 0);
    u8_field!(percent_of_level_mid, 1);
    u8_field!(percent_of_level_high, 2);
}

define_sheet!(SatisfactionSupplyRewardExpSheet, SatisfactionSupplyRewardExpRow, "SatisfactionSupplyRewardExp", no_language_support);
