// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(SatisfactionSupplyRewardSatisfactionSupplyRewardData, 4);
impl<'a> SatisfactionSupplyRewardSatisfactionSupplyRewardData<'a> {
    u16_field!(reward_currency, 0);
    u16_field!(quantity_low, 1);
    u16_field!(quantity_mid, 2);
    u16_field!(quantity_high, 3);
}


define_row!(SatisfactionSupplyRewardRow);
impl SatisfactionSupplyRewardRow {
    array_field!(satisfaction_supply_reward_data, 0, 2, SatisfactionSupplyRewardSatisfactionSupplyRewardData);
    u16_field!(satisfaction_low, 8);
    u16_field!(satisfaction_mid, 9);
    u16_field!(satisfaction_high, 10);
    u16_field!(gil_low, 11);
    u16_field!(gil_mid, 12);
    u16_field!(gil_high, 13);
    u8_field!(bonus_multiplier, 14);
    // 0 &#x3D;&#x3D; current cap
    u8_field!(min_level_for_second_reward, 15);
}

define_sheet!(SatisfactionSupplyRewardSheet, SatisfactionSupplyRewardRow, "SatisfactionSupplyReward");
