// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ScreenImageRow);
impl ScreenImageRow {
    u32_field!(image, 0);
    i16_field!(jingle, 1);
    i8_field!(type_, 2);
    bool_field!(lang, 3);
}

define_sheet!(ScreenImageSheet, ScreenImageRow, "ScreenImage");
