// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(SharlayanCraftWorksRow);
impl SharlayanCraftWorksRow {
    string_field!(description, 2);
    u32_field!(questgiver, 0);
    u16_field!(unknown_2, 1);
}

define_sheet!(SharlayanCraftWorksSheet, SharlayanCraftWorksRow, "SharlayanCraftWorks", language_support);
