// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(SharlayanCraftWorksSupplyItem, 11);
impl<'a> SharlayanCraftWorksSupplyItem<'a> {
    u32_field!(item_id, 0);
    u32_field!(xp_reward, 1);
    u16_field!(collectability_mid, 2);
    u16_field!(collectability_high, 3);
    u16_field!(gil_reward, 4);
    u8_field!(level, 5);
    u8_field!(high_xp_multiplier, 6);
    u8_field!(high_gil_multiplier, 7);
    u8_field!(unknown_8, 8);
    u8_field!(scrip_reward, 9);
    u8_field!(high_scrip_multiplier, 10);
}


define_row!(SharlayanCraftWorksSupplyRow);
impl SharlayanCraftWorksSupplyRow {
    array_field!(item, 0, 4, SharlayanCraftWorksSupplyItem);
}

define_sheet!(SharlayanCraftWorksSupplySheet, SharlayanCraftWorksSupplyRow, "SharlayanCraftWorksSupply", no_language_support);
