// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(SkyIslandSubjectRow);
impl SkyIslandSubjectRow {
    u32_field!(unknown_0, 2);
    u32_field!(unknown_1, 5);
    u32_field!(unknown_2, 8);
    u32_field!(unknown_3, 11);
    u32_field!(unknown_4, 14);
    u32_field!(unknown_5, 17);
    u8_field!(unknown_6, 0);
    u8_field!(unknown_7, 3);
    u8_field!(unknown_8, 6);
    u8_field!(unknown_9, 9);
    u8_field!(unknown_10, 12);
    u8_field!(unknown_11, 15);
    u8_field!(unknown_12, 1);
    u8_field!(unknown_13, 4);
    u8_field!(unknown_14, 7);
    u8_field!(unknown_15, 10);
    u8_field!(unknown_16, 13);
    u8_field!(unknown_17, 16);
}

define_sheet!(SkyIslandSubjectSheet, SkyIslandSubjectRow, "SkyIslandSubject", no_language_support);
