// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(SkyIsland2MissionDetailRow);
impl SkyIsland2MissionDetailRow {
    string_field!(objective, 0);
    string_field!(unknown_0, 1);
    string_field!(unknown_1, 2);
    string_field!(unknown_2, 3);
    u32_field!(e_obj, 4);
    u32_field!(unknown_3, 5);
    u32_field!(unknown_4, 6);
    u8_field!(type_, 7);
    u8_field!(unknown_5, 8);
    u8_field!(range, 9);
    i8_field!(unknown_6, 10);
}

define_sheet!(SkyIsland2MissionDetailSheet, SkyIsland2MissionDetailRow, "SkyIsland2MissionDetail");
