// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(SkyIsland2MissionRow);
impl SkyIsland2MissionRow {
    string_field!(unknown_0, 0);
    string_field!(unknown_1, 1);
    string_field!(unknown_2, 2);
    string_field!(unknown_3, 3);
    string_field!(unknown_4, 4);
    u32_field!(item_1, 5);
    u32_field!(item_2, 6);
    u32_field!(pop_range_0, 7);
    u32_field!(pop_range_1, 8);
    u32_field!(pop_range_2, 9);
    u32_field!(unknown_5, 10);
    u32_field!(unknown_6, 11);
    u32_field!(unknown_7, 12);
    u32_field!(unknown_8, 13);
    u32_field!(image, 14);
    u16_field!(place_name, 15);
    u16_field!(unknown_9, 16);
    u16_field!(objective_1, 17);
    u16_field!(objective_2, 18);
    u16_field!(objective_3, 19);
    u8_field!(required_amount_1, 20);
    u8_field!(required_amount_2, 21);
    u8_field!(unknown_10, 22);
    u8_field!(unknown_11, 23);
    u8_field!(unknown_12, 24);
    u8_field!(unknown_13, 25);
}

define_sheet!(SkyIsland2MissionSheet, SkyIsland2MissionRow, "SkyIsland2Mission");
