// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(SnipeTalkRow);
impl SnipeTalkRow {
    string_field!(text, 3);
    string_field!(unknown_0, 4);
    string_field!(unknown_1, 5);
    u16_field!(name, 2);
    u8_field!(unknown_2, 0);
    u8_field!(unknown_3, 1);
}

define_sheet!(SnipeTalkSheet, SnipeTalkRow, "SnipeTalk", language_support);
