// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(SnipeSnipeData, 7);
impl<'a> SnipeSnipeData<'a> {
    u32_field!(data_event_npc, 0);
    u16_field!(unknown_0, 1);
    u16_field!(unknown_1, 2);
    u16_field!(unknown_2, 3);
    u16_field!(unknown_3, 4);
    u8_field!(unknown_4, 5);
    u8_field!(unknown_5, 6);
}

define_subrow!(SnipeEventNPC, 1);
impl<'a> SnipeEventNPC<'a> {
    u32_field!(field_0, 0);
}


define_row!(SnipeRow);
impl SnipeRow {
    array_field!(snipe_data, 0, 8, SnipeSnipeData);
    array_field!(event_npc, 56, 8, SnipeEventNPC);
    u32_field!(unknown_0, 89);
    u16_field!(unknown_1, 81);
    u8_field!(unknown_2, 85);
    u32_field!(unknown_3, 90);
    u16_field!(unknown_4, 82);
    u8_field!(unknown_5, 86);
    u32_field!(unknown_6, 91);
    u16_field!(unknown_7, 83);
    u8_field!(unknown_8, 87);
    u32_field!(unknown_9, 92);
    u16_field!(unknown_10, 84);
    u8_field!(unknown_11, 88);
    string_field!(objective_0, 93);
    string_field!(hint_0, 94);
    string_field!(objective_1, 95);
    string_field!(hint_1, 96);
    string_field!(unknown_12, 97);
    string_field!(unknown_13, 98);
    string_field!(unknown_14, 99);
    string_field!(unknown_15, 100);
    string_field!(unknown_16, 101);
    string_field!(unknown_17, 102);
    string_field!(unknown_18, 103);
    string_field!(action_text, 104);
    u8_field!(unknown_19, 105);
    u8_field!(unknown_20, 106);
    string_field!(vfx_fire, 11);
    string_field!(vfx_hit, 12);
    string_field!(vfx_miss, 13);
    string_field!(vfx_additional, 14);
    u32_field!(lgb_target_marker, 0);
    u16_field!(unknown_21, 1);
    u16_field!(unknown_22, 8);
    u16_field!(unknown_23, 15);
    u8_field!(unknown_24, 3);
    u8_field!(unknown_25, 4);
    u8_field!(unknown_26, 5);
    u8_field!(unknown_27, 6);
    u8_field!(unknown_28, 7);
    u8_field!(unknown_29, 9);
    u8_field!(unknown_30, 10);
    bool_field!(unknown_31, 2);
    bool_field!(unknown_32, 16);
}

define_sheet!(SnipeSheet, SnipeRow, "Snipe", language_support);
