// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(StainTransientRow);
impl StainTransientRow {
    u32_field!(item_1, 0);
    u32_field!(item_2, 1);
}

define_sheet!(StainTransientSheet, StainTransientRow, "StainTransient", no_language_support);
