// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(StatusLoopVFXVFX, 1);
impl<'a> StatusLoopVFXVFX<'a> {
    u16_field!(field_0, 0);
}


define_row!(StatusLoopVFXRow);
impl StatusLoopVFXRow {
    array_field!(vfx, 0, 4, StatusLoopVFXVFX);
    u8_field!(unknown_0, 1);
    u8_field!(unknown_1, 3);
    u8_field!(unknown_2, 6);
    u8_field!(unknown_3, 7);
    bool_field!(unknown_4, 8);
    bool_field!(unknown_5, 9);
    bool_field!(unknown_6, 10);
}

define_sheet!(StatusLoopVFXSheet, StatusLoopVFXRow, "StatusLoopVFX");
