// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(SubmarineSpecCategoryRow);
impl SubmarineSpecCategoryRow {
    string_field!(unknown_0, 0);
}

define_sheet!(SubmarineSpecCategorySheet, SubmarineSpecCategoryRow, "SubmarineSpecCategory", language_support);
