// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(SubmarineExplorationRow);
impl SubmarineExplorationRow {
    string_field!(destination, 0);
    string_field!(location, 1);
    u32_field!(exp_reward, 2);
    u16_field!(survey_durationmin, 3);
    i16_field!(x, 4);
    i16_field!(y, 5);
    i16_field!(z, 6);
    u8_field!(map, 7);
    u8_field!(stars, 8);
    u8_field!(rank_req, 9);
    u8_field!(ceruleum_tank_req, 10);
    u8_field!(survey_distance, 11);
    bool_field!(starting_point, 12);
}

define_sheet!(SubmarineExplorationSheet, SubmarineExplorationRow, "SubmarineExploration");
