// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(SubmarineRankRow);
impl SubmarineRankRow {
    u32_field!(exp_to_next, 1);
    u16_field!(capacity, 0);
    u8_field!(surveillance_bonus, 2);
    u8_field!(retrieval_bonus, 3);
    u8_field!(speed_bonus, 4);
    u8_field!(range_bonus, 5);
    u8_field!(favor_bonus, 6);
}

define_sheet!(SubmarineRankSheet, SubmarineRankRow, "SubmarineRank");
