// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(SwitchTalkVariationRow);
impl SwitchTalkVariationRow {
    u32_field!(quest_0, 0);
    u32_field!(quest_1, 1);
    u32_field!(default_talk, 2);
    u8_field!(unknown_0, 3);
}

define_sheet!(SwitchTalkVariationSheet, SwitchTalkVariationRow, "SwitchTalkVariation");
