// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(SystemGraphicPresetRow);
impl SystemGraphicPresetRow {
    i8_field!(unknown_0, 0);
    i8_field!(unknown_1, 1);
    i8_field!(unknown_2, 2);
    i8_field!(unknown_3, 3);
    i8_field!(unknown_4, 4);
    i8_field!(unknown_5, 5);
    i8_field!(unknown_6, 6);
    i8_field!(unknown_7, 7);
    i8_field!(unknown_8, 8);
    i8_field!(unknown_9, 9);
    i8_field!(unknown_10, 10);
    i8_field!(unknown_11, 11);
    i8_field!(unknown_12, 12);
    i8_field!(unknown_13, 13);
    i8_field!(unknown_14, 14);
    i8_field!(unknown_15, 15);
    i8_field!(unknown_16, 16);
    i8_field!(unknown_17, 17);
    i8_field!(unknown_18, 18);
    i8_field!(unknown_19, 19);
    i8_field!(unknown_20, 20);
    i8_field!(unknown_21, 21);
    i8_field!(unknown_22, 22);
    i8_field!(unknown_23, 23);
    i8_field!(unknown_24, 24);
    i8_field!(unknown_25, 25);
    i8_field!(unknown_26, 26);
    i8_field!(unknown_27, 27);
    i8_field!(unknown_28, 28);
    i8_field!(unknown_29, 29);
    i8_field!(unknown_30, 30);
    i8_field!(unknown_31, 31);
    i8_field!(unknown_32, 32);
    i8_field!(unknown_70_1, 33);
    i8_field!(unknown_70_2, 34);
    i8_field!(unknown_70_3, 35);
    i8_field!(unknown_70_4, 36);
    i8_field!(unknown_70_5, 37);
    i8_field!(unknown_70_6, 38);
    i8_field!(unknown_70_7, 39);
}

define_sheet!(SystemGraphicPresetSheet, SystemGraphicPresetRow, "SystemGraphicPreset", no_language_support);
