// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(TerritoryIntendedUseRow);
impl TerritoryIntendedUseRow {
    u16_field!(unknown_0, 0);
    // Ambient noise of people talking in a crowd. Values: 0 &#x3D; None, 1 &#x3D; sound/strm/GAYA_LestArea_01.scd, 2 &#x3D; sound/strm/GAYA_Village_01.scd
    u8_field!(gaya_sound_id, 1);
    u8_field!(chat_rule, 2);
    u8_field!(unknown_3, 3);
    bool_field!(enable_crafting, 4);
    bool_field!(enable_gathering, 5);
    bool_field!(enable_repairs, 6);
    bool_field!(unknown_7, 7);
    bool_field!(unknown_8, 8);
    bool_field!(enable_job_change_to_limited_job, 9);
    // Enables summoning Chocobo Companion
    bool_field!(enable_companion, 10);
    // Enables summoning Summoner/Scholar pets
    bool_field!(enable_pets, 11);
    bool_field!(enable_ride_pillion, 12);
    bool_field!(disable_logout_timer, 13);
    bool_field!(enable_teleport, 14);
    bool_field!(enable_return, 15);
    bool_field!(unknown_16, 16);
    bool_field!(unknown_17, 17);
    bool_field!(enable_recommend_list, 18);
    bool_field!(unknown_19, 19);
    bool_field!(unknown_20, 20);
    // Related to Map in Island Sanctuary, Cosmic Exploration
    bool_field!(unknown_21, 21);
    bool_field!(disable_field_markers, 22);
    bool_field!(unknown_23, 23);
    bool_field!(enable_actions, 24);
    bool_field!(enable_consumable_items, 25);
    bool_field!(unknown_26, 26);
    bool_field!(enable_triple_triad_matches, 27);
    bool_field!(enable_triple_triad_matches_anywhere, 28);
    bool_field!(unknown_29, 29);
    bool_field!(unknown_30, 30);
    // Related to Idle Cam
    bool_field!(unknown_31, 31);
    bool_field!(can_pause_time_weather, 32);
    bool_field!(unknown_33, 33);
    bool_field!(enable_pv_p_quick_chat, 34);
    bool_field!(unknown_35, 35);
    bool_field!(unknown_36, 36);
    bool_field!(can_apply_glamour_plates_anywhere, 37);
    // Related to idle timer
    bool_field!(unknown_38, 38);
    bool_field!(enable_field_marker_presets, 39);
    bool_field!(ignore_combat_flag_for_markers, 40);
    // Related to blocking Say/Yell/Shout of a muted player in Eureka/Bozja/OccultCrescent
    bool_field!(unknown_41, 41);
    bool_field!(unknown_42, 42);
}

define_sheet!(TerritoryIntendedUseSheet, TerritoryIntendedUseRow, "TerritoryIntendedUse");
