// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(TerritoryTypeRow);
impl TerritoryTypeRow {
    string_field!(name, 0);
    string_field!(bg, 1);
    u32_field!(array_event_handler, 2);
    i32_field!(place_name_region_icon, 3);
    i32_field!(place_name_icon, 4);
    i32_field!(aetheryte, 5);
    i32_field!(fixed_time, 6);
    u16_field!(place_name_region, 7);
    u16_field!(place_name_zone, 8);
    u16_field!(place_name, 9);
    u16_field!(map, 10);
    u16_field!(content_finder_condition, 11);
    u16_field!(bgm, 12);
    u16_field!(quest_battle, 13);
    u16_field!(resident, 14);
    u16_field!(notorious_monster_territory, 15);
    u8_field!(battalion_mode, 16);
    u8_field!(loading_image, 17);
    u8_field!(exclusive_type, 18);
    u8_field!(territory_intended_use, 19);
    u8_field!(weather_rate, 20);
    u8_field!(unknown_1, 21);
    u8_field!(ex_version, 22);
    u8_field!(unknown_2, 23);
    u8_field!(zone_shared_group, 24);
    u8_field!(aether_current_comp_flg_set, 25);
    u8_field!(mount_speed, 26);
    u8_field!(individual_weather, 27);
    i8_field!(achievement_index, 28);
    bool_field!(unknown_6, 29);
    bool_field!(unknown_7, 30);
    bool_field!(pc_search, 31);
    bool_field!(stealth, 32);
    bool_field!(mount, 33);
    bool_field!(unknown_8, 34);
    bool_field!(is_pvp_zone, 35);
    bool_field!(unknown_9, 36);
    bool_field!(is_in_use, 37);
    bool_field!(unknown_11, 38);
    bool_field!(unknown_12, 39);
    bool_field!(unknown_13, 40);
    bool_field!(unknown_14, 41);
    bool_field!(unknown_15, 42);
    bool_field!(unknown_16, 43);
}

define_sheet!(TerritoryTypeSheet, TerritoryTypeRow, "TerritoryType");
