// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(TextCommandParamRow);
impl TextCommandParamRow {
    string_field!(param, 0);
}

define_sheet!(TextCommandParamSheet, TextCommandParamRow, "TextCommandParam");
