// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(TofuPresetObjects, 1);
impl<'a> TofuPresetObjects<'a> {
    string_field!(field_0, 0);
}


define_row!(TofuPresetRow);
impl TofuPresetRow {
    string_field!(name, 3);
    i32_field!(category, 1);
    array_field!(objects, 2, 8, TofuPresetObjects);
    i32_field!(unknown_10, 12);
    i32_field!(unknown_11, 13);
    u16_field!(unknown_12, 2);
    bool_field!(unknown_13, 0);
}

define_sheet!(TofuPresetSheet, TofuPresetRow, "TofuPreset", language_support);
