// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(TofuBgRow);
impl TofuBgRow {
    string_field!(name, 3);
    u32_field!(icon, 2);
    u16_field!(unknown_2, 1);
    bool_field!(unknown_3, 0);
}

define_sheet!(TofuBgSheet, TofuBgRow, "TofuBg", language_support);
