// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_subrow!(TopicSelectShop, 1);
impl<'a> TopicSelectShop<'a> {
    string_field!(field_0, 0);
}


define_row!(TopicSelectRow);
impl TopicSelectRow {
    string_field!(name, 0);
    array_field!(shop, 1, 10, TopicSelectShop);
    u16_field!(unknown_0, 3);
    u8_field!(unknown_1, 2);
    bool_field!(unknown_2, 1);
}

define_sheet!(TopicSelectSheet, TopicSelectRow, "TopicSelect", language_support);
