// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(TransformationRow);
impl TransformationRow {
    f32_field!(speed, 24);
    f32_field!(scale, 25);
    u32_field!(action_6, 33);
    i32_field!(b_npc_customize, 3);
    i32_field!(npc_equip, 4);
    u16_field!(b_npc_name, 2);
    u16_field!(action_0, 6);
    u16_field!(action_1, 8);
    u16_field!(action_2, 10);
    u16_field!(action_3, 12);
    u16_field!(action_4, 14);
    u16_field!(action_5, 16);
    u16_field!(rp_parameter, 18);
    u16_field!(remove_action, 19);
    u16_field!(start_vfx, 31);
    u16_field!(end_vfx, 32);
    u16_field!(action_7, 36);
    i16_field!(model, 1);
    u8_field!(unknown_0, 0);
    u8_field!(unknown_1, 22);
    u8_field!(rp_parameter_2, 37);
    i8_field!(unknown_3, 34);
    i8_field!(unknown_4, 35);
    bool_field!(ex_hotbar_enable_config, 5);
    bool_field!(unknown_5, 7);
    bool_field!(unknown_6, 9);
    bool_field!(unknown_7, 11);
    bool_field!(unknown_8, 13);
    bool_field!(unknown_9, 15);
    bool_field!(unknown_10, 17);
    bool_field!(unknown_11, 20);
    bool_field!(unknown_12, 21);
    bool_field!(unknown_13, 23);
    bool_field!(is_pv_p, 26);
    bool_field!(is_event, 27);
    bool_field!(player_camera, 28);
    bool_field!(unknown_14, 29);
    bool_field!(unknown_15, 30);
    bool_field!(unknown_16, 38);
    bool_field!(unknown_17, 39);
}

define_sheet!(TransformationSheet, TransformationRow, "Transformation", no_language_support);
