// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(TripleTriadCardResidentRow);
impl TripleTriadCardResidentRow {
    u32_field!(acquisition, 0);
    u32_field!(location, 1);
    u32_field!(quest, 2);
    u16_field!(unknown_0, 3);
    u16_field!(sale_value, 4);
    u16_field!(order, 5);
    u8_field!(top, 6);
    u8_field!(bottom, 7);
    u8_field!(left, 8);
    u8_field!(right, 9);
    u8_field!(triple_triad_card_rarity, 10);
    u8_field!(triple_triad_card_type, 11);
    u8_field!(sort_key, 12);
    u8_field!(ui_priority, 13);
    u8_field!(acquisition_type, 14);
    bool_field!(unknown_1, 15);
}

define_sheet!(TripleTriadCardResidentSheet, TripleTriadCardResidentRow, "TripleTriadCardResident");
