// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(TripleTriadCardObtainRow);
impl TripleTriadCardObtainRow {
    u32_field!(icon, 0);
    u32_field!(text, 1);
}

define_sheet!(TripleTriadCardObtainSheet, TripleTriadCardObtainRow, "TripleTriadCardObtain");
