// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(TripleTriadDefineRow);
impl TripleTriadDefineRow {
    i32_field!(value, 0);
}

define_sheet!(TripleTriadDefineSheet, TripleTriadDefineRow, "TripleTriadDefine");
