// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(TripleTriadCardResidentRow);
impl TripleTriadCardResidentRow {
    u32_field!(acquisition, 13);
    u32_field!(location, 14);
    u32_field!(quest, 15);
    u16_field!(unknown_0, 0);
    u16_field!(sale_value, 7);
    u16_field!(order, 9);
    u8_field!(top, 1);
    u8_field!(bottom, 2);
    u8_field!(left, 3);
    u8_field!(right, 4);
    u8_field!(triple_triad_card_rarity, 5);
    u8_field!(triple_triad_card_type, 6);
    u8_field!(sort_key, 8);
    u8_field!(ui_priority, 10);
    u8_field!(acquisition_type, 12);
    bool_field!(unknown_1, 11);
}

define_sheet!(TripleTriadCardResidentSheet, TripleTriadCardResidentRow, "TripleTriadCardResident", no_language_support);
