// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(TripleTriadCardTypeRow);
impl TripleTriadCardTypeRow {
    string_field!(name, 0);
}

define_sheet!(TripleTriadCardTypeSheet, TripleTriadCardTypeRow, "TripleTriadCardType", language_support);
