// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(TutorialRow);
impl TutorialRow {
    u32_field!(exp, 0);
    u32_field!(gil, 1);
    u32_field!(reward_tank, 2);
    u32_field!(reward_melee, 3);
    u32_field!(reward_ranged, 4);
    u32_field!(unknown_4, 5);
    u32_field!(objective, 6);
    u8_field!(unknown_5, 7);
    u8_field!(unknown_0, 8);
    u8_field!(unknown_1, 9);
    u8_field!(unknown_2, 10);
    u8_field!(unknown_3, 11);
}

define_sheet!(TutorialSheet, TutorialRow, "Tutorial");
