// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(TutorialGimmickRow);
impl TutorialGimmickRow {
    u32_field!(image, 1);
    u8_field!(objective, 0);
}

define_sheet!(TutorialGimmickSheet, TutorialGimmickRow, "TutorialGimmick");
