// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(TutorialRow);
impl TutorialRow {
    u32_field!(exp, 5);
    u32_field!(gil, 6);
    u32_field!(reward_tank, 7);
    u32_field!(reward_melee, 8);
    u32_field!(reward_ranged, 9);
    u32_field!(unknown_4, 10);
    u32_field!(objective, 11);
    u8_field!(unknown_5, 0);
    u8_field!(unknown_0, 1);
    u8_field!(unknown_1, 2);
    u8_field!(unknown_2, 3);
    u8_field!(unknown_3, 4);
}

define_sheet!(TutorialSheet, TutorialRow, "Tutorial", no_language_support);
