// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(UDS_StatsRow);
impl UDS_StatsRow {
    string_field!(unknown_0, 0);
    string_field!(unknown_1, 1);
}

define_sheet!(UDS_StatsSheet, UDS_StatsRow, "UDS_Stats", no_language_support);
