// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(UDS_EventProperty, 1);
impl<'a> UDS_EventProperty<'a> {
    string_field!(field_0, 0);
}


define_row!(UDS_EventRow);
impl UDS_EventRow {
    string_field!(text, 0);
    string_field!(type_, 1);
    array_field!(property, 2, 32, UDS_EventProperty);
}

define_sheet!(UDS_EventSheet, UDS_EventRow, "UDS_Event", no_language_support);
