// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(UIColorRow);
impl UIColorRow {
    u32_field!(dark, 0);
    u32_field!(light, 1);
    u32_field!(classic_ff, 2);
    u32_field!(clear_blue, 3);
    u32_field!(clear_white, 4);
    u32_field!(clear_green, 5);
    u32_field!(unknown_2, 6);
    u32_field!(unknown_3, 7);
}

define_sheet!(UIColorSheet, UIColorRow, "UIColor", no_language_support);
