// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(ValentionSweetsMaterialRow);
impl ValentionSweetsMaterialRow {
    string_field!(unknown_0, 0);
}

define_sheet!(ValentionSweetsMaterialSheet, ValentionSweetsMaterialRow, "ValentionSweetsMaterial", language_support);
