// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(VaseFlowerRow);
impl VaseFlowerRow {
    u32_field!(item, 3);
    u16_field!(unknown_0, 0);
    u8_field!(unknown_1, 1);
    u8_field!(unknown_2, 2);
}

define_sheet!(VaseFlowerSheet, VaseFlowerRow, "VaseFlower");
