// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(VaseRow);
impl VaseRow {
    u32_field!(vase_flower_start, 0);
    u32_field!(vase_flower_end, 1);
}

define_sheet!(VaseSheet, VaseRow, "Vase");
