// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(VVDDataRow);
impl VVDDataRow {
    u32_field!(content_finder_condition, 2);
    u32_field!(currency_item, 3);
    u32_field!(content_ex_action, 4);
    u32_field!(unlock_quest, 5);
    // RowId of VVDRouteData and VVDNotebookSeries
    u8_field!(series, 0);
    u8_field!(unknown_5, 1);
    u8_field!(unknown_6, 6);
}

define_sheet!(VVDDataSheet, VVDDataRow, "VVDData", no_language_support);
