// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(VVDVariantActionRow);
impl VVDVariantActionRow {
    u32_field!(action, 0);
}

define_sheet!(VVDVariantActionSheet, VVDVariantActionRow, "VVDVariantAction");
