// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(VVDRouteDataRow);
impl VVDRouteDataRow {
    u16_field!(notebook_entry, 0);
}

define_sheet!(VVDRouteDataSheet, VVDRouteDataRow, "VVDRouteData", no_language_support);
