// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WeaponTimelineRow);
impl WeaponTimelineRow {
    string_field!(file, 0);
    i16_field!(next_weapon_timeline, 1);
    bool_field!(unknown_0, 2);
    bool_field!(unknown_1, 3);
}

define_sheet!(WeaponTimelineSheet, WeaponTimelineRow, "WeaponTimeline", no_language_support);
