// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WeatherRow);
impl WeatherRow {
    string_field!(name, 1);
    string_field!(description, 2);
    string_field!(unknown_0, 3);
    string_field!(unknown_1, 4);
    string_field!(unknown_2, 5);
    string_field!(unknown_3, 6);
    i32_field!(icon, 0);
}

define_sheet!(WeatherSheet, WeatherRow, "Weather", language_support);
