// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WeatherReportReplaceRow);
impl WeatherReportReplaceRow {
    u16_field!(place_name_sub, 0);
    u16_field!(place_name_parent, 1);
}

define_sheet!(WeatherReportReplaceSheet, WeatherReportReplaceRow, "WeatherReportReplace");
