// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WebURLRow);
impl WebURLRow {
    string_field!(url, 0);
}

define_sheet!(WebURLSheet, WebURLRow, "WebURL", language_support);
