// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WebGuidanceRow);
impl WebGuidanceRow {
    string_field!(name, 0);
    string_field!(unknown_0, 1);
    string_field!(description, 2);
    i32_field!(image, 3);
    u8_field!(url, 4);
}

define_sheet!(WebGuidanceSheet, WebGuidanceRow, "WebGuidance");
