// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WeeklyBingoOrderDataRow);
impl WeeklyBingoOrderDataRow {
    u32_field!(type_, 0);
    u32_field!(data, 1);
    u32_field!(unknown_2, 2);
    u32_field!(icon, 5);
    u8_field!(unknown_0, 3);
    u8_field!(text, 4);
    u8_field!(unknown_1, 6);
}

define_sheet!(WeeklyBingoOrderDataSheet, WeeklyBingoOrderDataRow, "WeeklyBingoOrderData", no_language_support);
