// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WKSMissionToDoEvalutionRefinRow);
impl WKSMissionToDoEvalutionRefinRow {
    u16_field!(unknown_0, 0);
    u16_field!(unknown_1, 1);
    u16_field!(unknown_2, 2);
}

define_sheet!(WKSMissionToDoEvalutionRefinSheet, WKSMissionToDoEvalutionRefinRow, "WKSMissionToDoEvalutionRefin", no_language_support);
