// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WKSCosmoToolCommonLevelRow);
impl WKSCosmoToolCommonLevelRow {
    bool_field!(is_common, 0);
}

define_sheet!(WKSCosmoToolCommonLevelSheet, WKSCosmoToolCommonLevelRow, "WKSCosmoToolCommonLevel", no_language_support);
