// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WKSFortuneSPPatternUIPlaceRow);
impl WKSFortuneSPPatternUIPlaceRow {
    u32_field!(unknown_0, 0);
    u32_field!(unknown_1, 1);
    u32_field!(unknown_2, 2);
    u32_field!(unknown_3, 3);
    u32_field!(unknown_4, 4);
    u32_field!(unknown_5, 5);
    u32_field!(unknown_6, 6);
    u32_field!(unknown_7, 7);
    u32_field!(unknown_8, 8);
    u32_field!(unknown_9, 9);
    u32_field!(unknown_10, 10);
    u32_field!(unknown_11, 11);
    u32_field!(unknown_12, 12);
    u32_field!(unknown_13, 13);
    u32_field!(unknown_14, 14);
    u32_field!(unknown_15, 15);
    u32_field!(unknown_16, 16);
    u32_field!(unknown_17, 17);
    u32_field!(unknown_18, 18);
    u32_field!(unknown_19, 19);
    u32_field!(unknown_20, 20);
    u32_field!(unknown_21, 21);
    u32_field!(unknown_22, 22);
    u32_field!(unknown_23, 23);
    u32_field!(unknown_24, 24);
    u32_field!(unknown_25, 25);
    u32_field!(unknown_26, 26);
    u32_field!(unknown_27, 27);
    u32_field!(unknown_28, 28);
    u32_field!(unknown_29, 29);
    u32_field!(unknown_30, 30);
    u32_field!(unknown_31, 31);
    u32_field!(unknown_32, 32);
    u32_field!(unknown_33, 33);
    u32_field!(unknown_34, 34);
    u32_field!(unknown_35, 35);
    u32_field!(unknown_36, 36);
    u32_field!(unknown_37, 37);
    u32_field!(unknown_38, 38);
    u32_field!(unknown_39, 39);
}

define_sheet!(WKSFortuneSPPatternUIPlaceSheet, WKSFortuneSPPatternUIPlaceRow, "WKSFortuneSPPatternUIPlace");
