// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WKSMechaEventDataRow);
impl WKSMechaEventDataRow {
    string_field!(unknown_0, 0);
    string_field!(unknown_1, 1);
    string_field!(unknown_2, 2);
    string_field!(unknown_3, 3);
    string_field!(unknown_4, 4);
    string_field!(unknown_5, 5);
    string_field!(unknown_6, 6);
    string_field!(unknown_7, 7);
    string_field!(unknown_8, 8);
    string_field!(unknown_9, 9);
    u32_field!(unknown_10, 10);
    u32_field!(unknown_11, 11);
    u32_field!(unknown_12, 12);
    u32_field!(unknown_13, 13);
    u32_field!(unknown_14, 14);
    u32_field!(unknown_15, 15);
    u32_field!(unknown_16, 16);
    u32_field!(unknown_17, 17);
    u32_field!(unknown_18, 18);
    u32_field!(unknown_19, 19);
    u32_field!(unknown_20, 20);
    u32_field!(unknown_21, 21);
    u32_field!(unknown_22, 22);
    u32_field!(unknown_23, 23);
    u32_field!(unknown_24, 24);
    u32_field!(unknown_25, 25);
    u32_field!(unknown_26, 26);
    u32_field!(unknown_27, 27);
    u32_field!(unknown_28, 28);
    u32_field!(unknown_29, 29);
    u32_field!(unknown_30, 30);
    u32_field!(unknown_31, 31);
    u32_field!(unknown_32, 32);
    u32_field!(unknown_33, 33);
    u32_field!(unknown_34, 34);
    u32_field!(unknown_35, 35);
    u32_field!(unknown_36, 36);
    u32_field!(unknown_37, 37);
    u32_field!(unknown_38, 38);
    u32_field!(unknown_39, 39);
    u32_field!(unknown_40, 40);
    i32_field!(unknown_41, 41);
    i32_field!(unknown_42, 42);
    i32_field!(unknown_43, 43);
    i32_field!(unknown_44, 44);
    i32_field!(unknown_45, 45);
    i32_field!(unknown_46, 46);
    i32_field!(unknown_47, 47);
    i32_field!(unknown_48, 48);
    i32_field!(unknown_49, 49);
    u16_field!(unknown_50, 50);
    u16_field!(unknown_51, 51);
    u8_field!(unknown_52, 52);
}

define_sheet!(WKSMechaEventDataSheet, WKSMechaEventDataRow, "WKSMechaEventData");
