// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WKSSharedGroupRow);
impl WKSSharedGroupRow {
    u32_field!(unknown_0, 0);
    u32_field!(unknown_1, 1);
    u16_field!(unknown_5, 2);
    u8_field!(unknown_2, 3);
    u8_field!(unknown_3, 4);
    bool_field!(unknown_4, 5);
}

define_sheet!(WKSSharedGroupSheet, WKSSharedGroupRow, "WKSSharedGroup");
