// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WKSFortuneSPPatternUIPlaceRow);
impl WKSFortuneSPPatternUIPlaceRow {
    u32_field!(unknown_0, 0);
    u32_field!(unknown_1, 2);
    u32_field!(unknown_2, 4);
    u32_field!(unknown_3, 6);
    u32_field!(unknown_4, 8);
    u32_field!(unknown_5, 10);
    u32_field!(unknown_6, 12);
    u32_field!(unknown_7, 14);
    u32_field!(unknown_8, 16);
    u32_field!(unknown_9, 18);
    u32_field!(unknown_10, 20);
    u32_field!(unknown_11, 22);
    u32_field!(unknown_12, 24);
    u32_field!(unknown_13, 26);
    u32_field!(unknown_14, 28);
    u32_field!(unknown_15, 30);
    u32_field!(unknown_16, 32);
    u32_field!(unknown_17, 34);
    u32_field!(unknown_18, 36);
    u32_field!(unknown_19, 38);
    u32_field!(unknown_20, 1);
    u32_field!(unknown_21, 3);
    u32_field!(unknown_22, 5);
    u32_field!(unknown_23, 7);
    u32_field!(unknown_24, 9);
    u32_field!(unknown_25, 11);
    u32_field!(unknown_26, 13);
    u32_field!(unknown_27, 15);
    u32_field!(unknown_28, 17);
    u32_field!(unknown_29, 19);
    u32_field!(unknown_30, 21);
    u32_field!(unknown_31, 23);
    u32_field!(unknown_32, 25);
    u32_field!(unknown_33, 27);
    u32_field!(unknown_34, 29);
    u32_field!(unknown_35, 31);
    u32_field!(unknown_36, 33);
    u32_field!(unknown_37, 35);
    u32_field!(unknown_38, 37);
    u32_field!(unknown_39, 39);
}

define_sheet!(WKSFortuneSPPatternUIPlaceSheet, WKSFortuneSPPatternUIPlaceRow, "WKSFortuneSPPatternUIPlace");
