// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WKSMechaEventRewardUIRow);
impl WKSMechaEventRewardUIRow {
    u32_field!(unknown_0, 0);
    u32_field!(unknown_1, 1);
    bool_field!(unknown_2, 2);
    bool_field!(unknown_3, 3);
    bool_field!(unknown_4, 4);
}

define_sheet!(WKSMechaEventRewardUISheet, WKSMechaEventRewardUIRow, "WKSMechaEventRewardUI");
