// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WKSTextRow);
impl WKSTextRow {
    string_field!(text, 0);
}

define_sheet!(WKSTextSheet, WKSTextRow, "WKSText");
