// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WKSMechaEventObjectRow);
impl WKSMechaEventObjectRow {
    u32_field!(unknown_0, 2);
    i32_field!(unknown_1, 1);
    i32_field!(unknown_2, 3);
    u16_field!(unknown_5, 4);
    u8_field!(unknown_3, 0);
    u8_field!(unknown_4, 5);
}

define_sheet!(WKSMechaEventObjectSheet, WKSMechaEventObjectRow, "WKSMechaEventObject", no_language_support);
