// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(WKSMissionToDoRequiredItem, 1);
impl<'a> WKSMissionToDoRequiredItem<'a> {
    u32_field!(field_0, 0);
}

define_element!(WKSMissionToDoRequiredItemQuantity, 1);
impl<'a> WKSMissionToDoRequiredItemQuantity<'a> {
    u32_field!(field_0, 0);
}


define_row!(WKSMissionToDoRow);
impl WKSMissionToDoRow {
    u32_field!(temporary_action, 0);
    u32_field!(unknown_1, 13);
    u16_field!(unknown_2, 3);
    array_field!(required_item, 3, 3, WKSMissionToDoRequiredItem);
    array_field!(required_item_quantity, 6, 3, WKSMissionToDoRequiredItemQuantity);
    u16_field!(unknown_9, 11);
    u16_field!(unknown_10, 15);
    u16_field!(unknown_11, 16);
    u16_field!(unknown_12, 17);
    u16_field!(unknown_13, 18);
    u16_field!(wks_mission_text, 19);
    u8_field!(unknown_14, 1);
    u8_field!(unknown_15, 2);
    u8_field!(unknown_16, 10);
    u8_field!(unknown_17, 12);
    u8_field!(mission_type, 14);
}

define_sheet!(WKSMissionToDoSheet, WKSMissionToDoRow, "WKSMissionToDo", no_language_support);
