// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WKSTerritoryInfoRow);
impl WKSTerritoryInfoRow {
    u32_field!(unknown_6, 0);
    u32_field!(unknown_7, 1);
    u32_field!(unknown_8, 2);
    u32_field!(unknown_9, 3);
    u32_field!(unknown_10, 4);
    u32_field!(unknown_11, 5);
    u32_field!(unknown_12, 6);
    u32_field!(unknown_0, 7);
    u32_field!(mecha_event_npc, 8);
    u32_field!(item, 9);
    u32_field!(unknown_3, 10);
    u16_field!(unknown_4, 11);
    u8_field!(unknown_5, 12);
}

define_sheet!(WKSTerritoryInfoSheet, WKSTerritoryInfoRow, "WKSTerritoryInfo");
