// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WKSFateControlRow);
impl WKSFateControlRow {
    string_field!(startup_text, 0);
    string_field!(running_text, 1);
    u16_field!(unknown_0, 2);
}

define_sheet!(WKSFateControlSheet, WKSFateControlRow, "WKSFateControl");
