// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;


define_row!(WorldRow);
impl WorldRow {
    string_field!(internal_name, 0);
    string_field!(name, 1);
    u8_field!(data_center, 2);
    u8_field!(user_type, 3);
    u8_field!(region, 4);
    bool_field!(is_public, 5);
}

define_sheet!(WorldSheet, WorldRow, "World", no_language_support);
