// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

use crate::Sheet;
use crate::macros::*;

define_element!(YKWLocation, 1);
impl<'a> YKWLocation<'a> {
    string_field!(field_0, 0);
}


define_row!(YKWRow);
impl YKWRow {
    string_field!(transient, 8);
    u32_field!(item, 1);
    u16_field!(companion, 0);
    array_field!(location, 3, 6, YKWLocation);
}

define_sheet!(YKWSheet, YKWRow, "YKW", language_support);
