// -----------------------------------------------------------------------------
//  This file was automatically generated by logos-builder.
//  Do not edit this file directly; your changes will be overwritten.
// -----------------------------------------------------------------------------

#[cfg(feature = "achievement")]
pub mod achievement;

#[cfg(feature = "achievement-category")]
pub mod achievement_category;

#[cfg(feature = "achievement-hide-condition")]
pub mod achievement_hide_condition;

#[cfg(feature = "achievement-kind")]
pub mod achievement_kind;

#[cfg(feature = "achievement-target")]
pub mod achievement_target;

#[cfg(feature = "action")]
pub mod action;

#[cfg(feature = "action-cast-timeline")]
pub mod action_cast_timeline;

#[cfg(feature = "action-cast-vfx")]
pub mod action_cast_vfx;

#[cfg(feature = "action-category")]
pub mod action_category;

#[cfg(feature = "action-combo-route")]
pub mod action_combo_route;

#[cfg(feature = "action-combo-route-transient")]
pub mod action_combo_route_transient;

#[cfg(feature = "action-cost-type")]
pub mod action_cost_type;

#[cfg(feature = "action-indirection")]
pub mod action_indirection;

#[cfg(feature = "action-init")]
pub mod action_init;

#[cfg(feature = "action-param")]
pub mod action_param;

#[cfg(feature = "action-proc-status")]
pub mod action_proc_status;

#[cfg(feature = "action-setting")]
pub mod action_setting;

#[cfg(feature = "action-timeline")]
pub mod action_timeline;

#[cfg(feature = "action-timeline-move")]
pub mod action_timeline_move;

#[cfg(feature = "action-timeline-replace")]
pub mod action_timeline_replace;

#[cfg(feature = "action-transient")]
pub mod action_transient;

#[cfg(feature = "activity-feed-buttons")]
pub mod activity_feed_buttons;

#[cfg(feature = "activity-feed-captions")]
pub mod activity_feed_captions;

#[cfg(feature = "activity-feed-group-captions")]
pub mod activity_feed_group_captions;

#[cfg(feature = "activity-feed-images")]
pub mod activity_feed_images;

#[cfg(feature = "addon")]
pub mod addon;

#[cfg(feature = "addon-hud-size")]
pub mod addon_hud_size;

#[cfg(feature = "addon-layout")]
pub mod addon_layout;

#[cfg(feature = "addon-param")]
pub mod addon_param;

#[cfg(feature = "addon-talk-param")]
pub mod addon_talk_param;

#[cfg(feature = "addon-transient")]
pub mod addon_transient;

#[cfg(feature = "advanced-vibration")]
pub mod advanced_vibration;

#[cfg(feature = "adventure")]
pub mod adventure;

#[cfg(feature = "adventure-ex-phase")]
pub mod adventure_ex_phase;

#[cfg(feature = "aether-current")]
pub mod aether_current;

#[cfg(feature = "aether-current-comp-flg-set")]
pub mod aether_current_comp_flg_set;

#[cfg(feature = "aetherial-wheel")]
pub mod aetherial_wheel;

#[cfg(feature = "aetheryte")]
pub mod aetheryte;

#[cfg(feature = "aetheryte-system-define")]
pub mod aetheryte_system_define;

#[cfg(feature = "aetheryte-transient")]
pub mod aetheryte_transient;

#[cfg(feature = "airship-exploration-level")]
pub mod airship_exploration_level;

#[cfg(feature = "airship-exploration-log")]
pub mod airship_exploration_log;

#[cfg(feature = "airship-exploration-param-type")]
pub mod airship_exploration_param_type;

#[cfg(feature = "airship-exploration-part")]
pub mod airship_exploration_part;

#[cfg(feature = "airship-exploration-point")]
pub mod airship_exploration_point;

#[cfg(feature = "airship-sky-island")]
pub mod airship_sky_island;

#[cfg(feature = "akatsuki-note")]
pub mod akatsuki_note;

#[cfg(feature = "akatsuki-note-string")]
pub mod akatsuki_note_string;

#[cfg(feature = "animation-lod")]
pub mod animation_lod;

#[cfg(feature = "anima-weapon-5")]
pub mod anima_weapon_5;

#[cfg(feature = "anima-weapon-5-param")]
pub mod anima_weapon_5_param;

#[cfg(feature = "anima-weapon-5-pattern-group")]
pub mod anima_weapon_5_pattern_group;

#[cfg(feature = "anima-weapon-5-spirit-talk")]
pub mod anima_weapon_5_spirit_talk;

#[cfg(feature = "anima-weapon-5-spirit-talk-param")]
pub mod anima_weapon_5_spirit_talk_param;

#[cfg(feature = "anima-weapon-5-spirit-talk-type")]
pub mod anima_weapon_5_spirit_talk_type;

#[cfg(feature = "anima-weapon-5-trade-item")]
pub mod anima_weapon_5_trade_item;

#[cfg(feature = "anima-weapon-fui-talk")]
pub mod anima_weapon_fui_talk;

#[cfg(feature = "anima-weapon-fui-talk-param")]
pub mod anima_weapon_fui_talk_param;

#[cfg(feature = "anima-weapon-icon")]
pub mod anima_weapon_icon;

#[cfg(feature = "anima-weapon-item")]
pub mod anima_weapon_item;

#[cfg(feature = "aoz-action")]
pub mod aoz_action;

#[cfg(feature = "aoz-action-transient")]
pub mod aoz_action_transient;

#[cfg(feature = "aoz-arrangement")]
pub mod aoz_arrangement;

#[cfg(feature = "aoz-boss")]
pub mod aoz_boss;

#[cfg(feature = "aoz-content")]
pub mod aoz_content;

#[cfg(feature = "aoz-content-briefing-b-npc")]
pub mod aoz_content_briefing_b_npc;

#[cfg(feature = "aoz-content-briefing-object")]
pub mod aoz_content_briefing_object;

#[cfg(feature = "aoz-report")]
pub mod aoz_report;

#[cfg(feature = "aoz-report-reward")]
pub mod aoz_report_reward;

#[cfg(feature = "aoz-score")]
pub mod aoz_score;

#[cfg(feature = "aoz-weekly-reward")]
pub mod aoz_weekly_reward;

#[cfg(feature = "aquarium-fish")]
pub mod aquarium_fish;

#[cfg(feature = "aquarium-water")]
pub mod aquarium_water;

#[cfg(feature = "archive-item")]
pub mod archive_item;

#[cfg(feature = "array-event-handler")]
pub mod array_event_handler;

#[cfg(feature = "attack-type")]
pub mod attack_type;

#[cfg(feature = "attract")]
pub mod attract;

#[cfg(feature = "attributive")]
pub mod attributive;

#[cfg(feature = "backlight-color")]
pub mod backlight_color;

#[cfg(feature = "ballista")]
pub mod ballista;

#[cfg(feature = "balloon")]
pub mod balloon;

#[cfg(feature = "banka-craft-works")]
pub mod banka_craft_works;

#[cfg(feature = "banka-craft-works-supply")]
pub mod banka_craft_works_supply;

#[cfg(feature = "banner-bg")]
pub mod banner_bg;

#[cfg(feature = "banner-condition")]
pub mod banner_condition;

#[cfg(feature = "banner-decoration")]
pub mod banner_decoration;

#[cfg(feature = "banner-design-preset")]
pub mod banner_design_preset;

#[cfg(feature = "banner-facial")]
pub mod banner_facial;

#[cfg(feature = "banner-frame")]
pub mod banner_frame;

#[cfg(feature = "banner-obtain-hint-type")]
pub mod banner_obtain_hint_type;

#[cfg(feature = "banner-preset")]
pub mod banner_preset;

#[cfg(feature = "banner-timeline")]
pub mod banner_timeline;

#[cfg(feature = "base-param")]
pub mod base_param;

#[cfg(feature = "battalion")]
pub mod battalion;

#[cfg(feature = "battle-leve")]
pub mod battle_leve;

#[cfg(feature = "battle-leve-rule")]
pub mod battle_leve_rule;

#[cfg(feature = "beast-rank-bonus")]
pub mod beast_rank_bonus;

#[cfg(feature = "beast-reputation-rank")]
pub mod beast_reputation_rank;

#[cfg(feature = "beast-tribe")]
pub mod beast_tribe;

#[cfg(feature = "behavior")]
pub mod behavior;

#[cfg(feature = "behavior-move")]
pub mod behavior_move;

#[cfg(feature = "behavior-path")]
pub mod behavior_path;

#[cfg(feature = "benchmark-cut-scene-table")]
pub mod benchmark_cut_scene_table;

#[cfg(feature = "benchmark-override-equipment")]
pub mod benchmark_override_equipment;

#[cfg(feature = "bgc-army-action")]
pub mod bgc_army_action;

#[cfg(feature = "bgc-army-action-transient")]
pub mod bgc_army_action_transient;

#[cfg(feature = "bgm")]
pub mod bgm;

#[cfg(feature = "bgm-fade")]
pub mod bgm_fade;

#[cfg(feature = "bgm-fade-type")]
pub mod bgm_fade_type;

#[cfg(feature = "bgm-scene")]
pub mod bgm_scene;

#[cfg(feature = "bgm-situation")]
pub mod bgm_situation;

#[cfg(feature = "bgm-switch")]
pub mod bgm_switch;

#[cfg(feature = "bgm-system-define")]
pub mod bgm_system_define;

#[cfg(feature = "b-npc-announce-icon")]
pub mod b_npc_announce_icon;

#[cfg(feature = "b-npc-base")]
pub mod b_npc_base;

#[cfg(feature = "b-npc-base-pop-vfx")]
pub mod b_npc_base_pop_vfx;

#[cfg(feature = "b-npc-customize")]
pub mod b_npc_customize;

#[cfg(feature = "b-npc-name")]
pub mod b_npc_name;

#[cfg(feature = "b-npc-parts")]
pub mod b_npc_parts;

#[cfg(feature = "b-npc-state")]
pub mod b_npc_state;

#[cfg(feature = "booster")]
pub mod booster;

#[cfg(feature = "buddy")]
pub mod buddy;

#[cfg(feature = "buddy-action")]
pub mod buddy_action;

#[cfg(feature = "buddy-equip")]
pub mod buddy_equip;

#[cfg(feature = "buddy-item")]
pub mod buddy_item;

#[cfg(feature = "buddy-rank")]
pub mod buddy_rank;

#[cfg(feature = "buddy-skill")]
pub mod buddy_skill;

#[cfg(feature = "cabinet")]
pub mod cabinet;

#[cfg(feature = "cabinet-category")]
pub mod cabinet_category;

#[cfg(feature = "cabinet-sub-category")]
pub mod cabinet_sub_category;

#[cfg(feature = "calendar")]
pub mod calendar;

#[cfg(feature = "carry")]
pub mod carry;

#[cfg(feature = "channeling")]
pub mod channeling;

#[cfg(feature = "chara-card-base")]
pub mod chara_card_base;

#[cfg(feature = "chara-card-decoration")]
pub mod chara_card_decoration;

#[cfg(feature = "chara-card-design-category")]
pub mod chara_card_design_category;

#[cfg(feature = "chara-card-design-preset")]
pub mod chara_card_design_preset;

#[cfg(feature = "chara-card-design-type")]
pub mod chara_card_design_type;

#[cfg(feature = "chara-card-header")]
pub mod chara_card_header;

#[cfg(feature = "chara-card-play-style")]
pub mod chara_card_play_style;

#[cfg(feature = "chara-make-class-equip")]
pub mod chara_make_class_equip;

#[cfg(feature = "chara-make-customize")]
pub mod chara_make_customize;

#[cfg(feature = "chara-make-name")]
pub mod chara_make_name;

#[cfg(feature = "chara-make-type")]
pub mod chara_make_type;

#[cfg(feature = "chat-bubble-sampe-text-list")]
pub mod chat_bubble_sampe_text_list;

#[cfg(feature = "chat-bubble-type")]
pub mod chat_bubble_type;

#[cfg(feature = "chocobo-race")]
pub mod chocobo_race;

#[cfg(feature = "chocobo-race-ability")]
pub mod chocobo_race_ability;

#[cfg(feature = "chocobo-race-ability-type")]
pub mod chocobo_race_ability_type;

#[cfg(feature = "chocobo-race-calculate-param")]
pub mod chocobo_race_calculate_param;

#[cfg(feature = "chocobo-race-challenge")]
pub mod chocobo_race_challenge;

#[cfg(feature = "chocobo-race-item")]
pub mod chocobo_race_item;

#[cfg(feature = "chocobo-race-rank")]
pub mod chocobo_race_rank;

#[cfg(feature = "chocobo-race-ranking")]
pub mod chocobo_race_ranking;

#[cfg(feature = "chocobo-race-status")]
pub mod chocobo_race_status;

#[cfg(feature = "chocobo-race-territory")]
pub mod chocobo_race_territory;

#[cfg(feature = "chocobo-race-tutorial")]
pub mod chocobo_race_tutorial;

#[cfg(feature = "chocobo-race-weather")]
pub mod chocobo_race_weather;

#[cfg(feature = "chocobo-taxi")]
pub mod chocobo_taxi;

#[cfg(feature = "chocobo-taxi-stand")]
pub mod chocobo_taxi_stand;

#[cfg(feature = "circle-activity")]
pub mod circle_activity;

#[cfg(feature = "class-job")]
pub mod class_job;

#[cfg(feature = "class-job-action-ui")]
pub mod class_job_action_ui;

#[cfg(feature = "class-job-action-ui-category")]
pub mod class_job_action_ui_category;

#[cfg(feature = "class-job-category")]
pub mod class_job_category;

#[cfg(feature = "class-job-resident")]
pub mod class_job_resident;

#[cfg(feature = "collectables-refine")]
pub mod collectables_refine;

#[cfg(feature = "collectables-shop")]
pub mod collectables_shop;

#[cfg(feature = "collectables-shop-item")]
pub mod collectables_shop_item;

#[cfg(feature = "collectables-shop-item-group")]
pub mod collectables_shop_item_group;

#[cfg(feature = "collectables-shop-refine")]
pub mod collectables_shop_refine;

#[cfg(feature = "collectables-shop-reward-item")]
pub mod collectables_shop_reward_item;

#[cfg(feature = "collectables-shop-reward-scrip")]
pub mod collectables_shop_reward_scrip;

#[cfg(feature = "collision-id-pallet")]
pub mod collision_id_pallet;

#[cfg(feature = "color-filter")]
pub mod color_filter;

#[cfg(feature = "colosseum")]
pub mod colosseum;

#[cfg(feature = "colosseum-match-rank")]
pub mod colosseum_match_rank;

#[cfg(feature = "companion")]
pub mod companion;

#[cfg(feature = "companion-move")]
pub mod companion_move;

#[cfg(feature = "companion-transient")]
pub mod companion_transient;

#[cfg(feature = "company-action")]
pub mod company_action;

#[cfg(feature = "company-craft-draft")]
pub mod company_craft_draft;

#[cfg(feature = "company-craft-draft-category")]
pub mod company_craft_draft_category;

#[cfg(feature = "company-craft-manufactory-state")]
pub mod company_craft_manufactory_state;

#[cfg(feature = "company-craft-part")]
pub mod company_craft_part;

#[cfg(feature = "company-craft-process")]
pub mod company_craft_process;

#[cfg(feature = "company-craft-sequence")]
pub mod company_craft_sequence;

#[cfg(feature = "company-craft-supply-item")]
pub mod company_craft_supply_item;

#[cfg(feature = "company-craft-type")]
pub mod company_craft_type;

#[cfg(feature = "company-leve")]
pub mod company_leve;

#[cfg(feature = "company-leve-rule")]
pub mod company_leve_rule;

#[cfg(feature = "complete-journal")]
pub mod complete_journal;

#[cfg(feature = "complete-journal-category")]
pub mod complete_journal_category;

#[cfg(feature = "completion")]
pub mod completion;

#[cfg(feature = "condition")]
pub mod condition;

#[cfg(feature = "config-key")]
pub mod config_key;

#[cfg(feature = "content-attribute-rect")]
pub mod content_attribute_rect;

#[cfg(feature = "content-close-cycle")]
pub mod content_close_cycle;

#[cfg(feature = "content-director-battle-talk")]
pub mod content_director_battle_talk;

#[cfg(feature = "content-director-managed-sg")]
pub mod content_director_managed_sg;

#[cfg(feature = "content-effective-time")]
pub mod content_effective_time;

#[cfg(feature = "content-entry")]
pub mod content_entry;

#[cfg(feature = "content-event-item")]
pub mod content_event_item;

#[cfg(feature = "content-ex-action")]
pub mod content_ex_action;

#[cfg(feature = "content-finder-condition")]
pub mod content_finder_condition;

#[cfg(feature = "content-finder-condition-region")]
pub mod content_finder_condition_region;

#[cfg(feature = "content-finder-condition-transient")]
pub mod content_finder_condition_transient;

#[cfg(feature = "content-gauge")]
pub mod content_gauge;

#[cfg(feature = "content-gauge-color")]
pub mod content_gauge_color;

#[cfg(feature = "content-member-type")]
pub mod content_member_type;

#[cfg(feature = "content-npc")]
pub mod content_npc;

#[cfg(feature = "content-npc-talk")]
pub mod content_npc_talk;

#[cfg(feature = "content-random-select")]
pub mod content_random_select;

#[cfg(feature = "content-reward-condition")]
pub mod content_reward_condition;

#[cfg(feature = "content-roulette")]
pub mod content_roulette;

#[cfg(feature = "content-roulette-open-rule")]
pub mod content_roulette_open_rule;

#[cfg(feature = "content-roulette-role-bonus")]
pub mod content_roulette_role_bonus;

#[cfg(feature = "contents-note")]
pub mod contents_note;

#[cfg(feature = "contents-note-category")]
pub mod contents_note_category;

#[cfg(feature = "contents-note-level")]
pub mod contents_note_level;

#[cfg(feature = "contents-note-reward-eureka-exp")]
pub mod contents_note_reward_eureka_exp;

#[cfg(feature = "contents-tutorial")]
pub mod contents_tutorial;

#[cfg(feature = "contents-tutorial-page")]
pub mod contents_tutorial_page;

#[cfg(feature = "content-talk")]
pub mod content_talk;

#[cfg(feature = "content-talk-param")]
pub mod content_talk_param;

#[cfg(feature = "content-todo")]
pub mod content_todo;

#[cfg(feature = "content-tourism-construct")]
pub mod content_tourism_construct;

#[cfg(feature = "content-type")]
pub mod content_type;

#[cfg(feature = "content-ui-category")]
pub mod content_ui_category;

#[cfg(feature = "craft-action")]
pub mod craft_action;

#[cfg(feature = "craft-action-indirection")]
pub mod craft_action_indirection;

#[cfg(feature = "craft-leve")]
pub mod craft_leve;

#[cfg(feature = "craft-leve-talk")]
pub mod craft_leve_talk;

#[cfg(feature = "craft-type")]
pub mod craft_type;

#[cfg(feature = "credit")]
pub mod credit;

#[cfg(feature = "credit-back-image")]
pub mod credit_back_image;

#[cfg(feature = "credit-cast")]
pub mod credit_cast;

#[cfg(feature = "credit-data-set")]
pub mod credit_data_set;

#[cfg(feature = "credit-font")]
pub mod credit_font;

#[cfg(feature = "credit-list")]
pub mod credit_list;

#[cfg(feature = "credit-list-text")]
pub mod credit_list_text;

#[cfg(feature = "credit-version")]
pub mod credit_version;

#[cfg(feature = "cs-bonus-content")]
pub mod cs_bonus_content;

#[cfg(feature = "cs-bonus-content-identifier")]
pub mod cs_bonus_content_identifier;

#[cfg(feature = "cs-bonus-content-type")]
pub mod cs_bonus_content_type;

#[cfg(feature = "cs-bonus-mission")]
pub mod cs_bonus_mission;

#[cfg(feature = "cs-bonus-mission-type")]
pub mod cs_bonus_mission_type;

#[cfg(feature = "cs-bonus-season")]
pub mod cs_bonus_season;

#[cfg(feature = "cs-bonus-text-data")]
pub mod cs_bonus_text_data;

#[cfg(feature = "currency-scrip-convert")]
pub mod currency_scrip_convert;

#[cfg(feature = "custom-talk")]
pub mod custom_talk;

#[cfg(feature = "custom-talk-define-client")]
pub mod custom_talk_define_client;

#[cfg(feature = "custom-talk-nest-handlers")]
pub mod custom_talk_nest_handlers;

#[cfg(feature = "custom-talk-resident")]
pub mod custom_talk_resident;

#[cfg(feature = "cut-action-timeline")]
pub mod cut_action_timeline;

#[cfg(feature = "cutscene")]
pub mod cutscene;

#[cfg(feature = "cutscene-actor-size")]
pub mod cutscene_actor_size;

#[cfg(feature = "cutscene-event-motion")]
pub mod cutscene_event_motion;

#[cfg(feature = "cut-scene-incomp-quest")]
pub mod cut_scene_incomp_quest;

#[cfg(feature = "cutscene-motion")]
pub mod cutscene_motion;

#[cfg(feature = "cutscene-name")]
pub mod cutscene_name;

#[cfg(feature = "cutscene-work-index")]
pub mod cutscene_work_index;

#[cfg(feature = "cut-screen-image")]
pub mod cut_screen_image;

#[cfg(feature = "cutting-grass")]
pub mod cutting_grass;

#[cfg(feature = "cycle-time")]
pub mod cycle_time;

#[cfg(feature = "daily-supply-item")]
pub mod daily_supply_item;

#[cfg(feature = "dawn-content")]
pub mod dawn_content;

#[cfg(feature = "dawn-content-participable")]
pub mod dawn_content_participable;

#[cfg(feature = "dawn-grow-member")]
pub mod dawn_grow_member;

#[cfg(feature = "dawn-member")]
pub mod dawn_member;

#[cfg(feature = "dawn-member-ui-param")]
pub mod dawn_member_ui_param;

#[cfg(feature = "dawn-quest-member")]
pub mod dawn_quest_member;

#[cfg(feature = "deep-dungeon")]
pub mod deep_dungeon;

#[cfg(feature = "deep-dungeon-4-gimmick-effect")]
pub mod deep_dungeon_4_gimmick_effect;

#[cfg(feature = "deep-dungeon-4-gimmick-effect-transient")]
pub mod deep_dungeon_4_gimmick_effect_transient;

#[cfg(feature = "deep-dungeon-ban")]
pub mod deep_dungeon_ban;

#[cfg(feature = "deep-dungeon-danger")]
pub mod deep_dungeon_danger;

#[cfg(feature = "deep-dungeon-demiclone")]
pub mod deep_dungeon_demiclone;

#[cfg(feature = "deep-dungeon-equipment")]
pub mod deep_dungeon_equipment;

#[cfg(feature = "deep-dungeon-floor-effect-ui")]
pub mod deep_dungeon_floor_effect_ui;

#[cfg(feature = "deep-dungeon-grow-data")]
pub mod deep_dungeon_grow_data;

#[cfg(feature = "deep-dungeon-hard-mode-item")]
pub mod deep_dungeon_hard_mode_item;

#[cfg(feature = "deep-dungeon-item")]
pub mod deep_dungeon_item;

#[cfg(feature = "deep-dungeon-layer")]
pub mod deep_dungeon_layer;

#[cfg(feature = "deep-dungeon-magic-stone")]
pub mod deep_dungeon_magic_stone;

#[cfg(feature = "deep-dungeon-map-5-x")]
pub mod deep_dungeon_map_5_x;

#[cfg(feature = "deep-dungeon-resident")]
pub mod deep_dungeon_resident;

#[cfg(feature = "deep-dungeon-room")]
pub mod deep_dungeon_room;

#[cfg(feature = "deep-dungeon-status")]
pub mod deep_dungeon_status;

#[cfg(feature = "default-talk")]
pub mod default_talk;

#[cfg(feature = "default-talk-lip-sync-type")]
pub mod default_talk_lip_sync_type;

#[cfg(feature = "delivery-quest")]
pub mod delivery_quest;

#[cfg(feature = "description")]
pub mod description;

#[cfg(feature = "description-page")]
pub mod description_page;

#[cfg(feature = "description-section")]
pub mod description_section;

#[cfg(feature = "description-stand-alone")]
pub mod description_stand_alone;

#[cfg(feature = "description-stand-alone-transient")]
pub mod description_stand_alone_transient;

#[cfg(feature = "description-string")]
pub mod description_string;

#[cfg(feature = "director-system-define")]
pub mod director_system_define;

#[cfg(feature = "director-type")]
pub mod director_type;

#[cfg(feature = "disposal-shop")]
pub mod disposal_shop;

#[cfg(feature = "disposal-shop-filter-type")]
pub mod disposal_shop_filter_type;

#[cfg(feature = "disposal-shop-item")]
pub mod disposal_shop_item;

#[cfg(feature = "doma-story-progress")]
pub mod doma_story_progress;

#[cfg(feature = "dps-challenge")]
pub mod dps_challenge;

#[cfg(feature = "dps-challenge-officer")]
pub mod dps_challenge_officer;

#[cfg(feature = "dps-challenge-transient")]
pub mod dps_challenge_transient;

#[cfg(feature = "dynamic-event")]
pub mod dynamic_event;

#[cfg(feature = "dynamic-event-enemy-type")]
pub mod dynamic_event_enemy_type;

#[cfg(feature = "dynamic-event-manager")]
pub mod dynamic_event_manager;

#[cfg(feature = "dynamic-event-set")]
pub mod dynamic_event_set;

#[cfg(feature = "dynamic-event-single-battle")]
pub mod dynamic_event_single_battle;

#[cfg(feature = "dynamic-event-type")]
pub mod dynamic_event_type;

#[cfg(feature = "dynamic-event-ui-type")]
pub mod dynamic_event_ui_type;

#[cfg(feature = "emj-addon")]
pub mod emj_addon;

#[cfg(feature = "emj-chara-view-camera")]
pub mod emj_chara_view_camera;

#[cfg(feature = "emj-costume")]
pub mod emj_costume;

#[cfg(feature = "emj-costume-data")]
pub mod emj_costume_data;

#[cfg(feature = "emj-dani")]
pub mod emj_dani;

#[cfg(feature = "emj-voice-npc")]
pub mod emj_voice_npc;

#[cfg(feature = "emote")]
pub mod emote;

#[cfg(feature = "emote-category")]
pub mod emote_category;

#[cfg(feature = "emote-mode")]
pub mod emote_mode;

#[cfg(feature = "emote-transient")]
pub mod emote_transient;

#[cfg(feature = "e-npc-base")]
pub mod e_npc_base;

#[cfg(feature = "e-npc-dress-up")]
pub mod e_npc_dress_up;

#[cfg(feature = "e-npc-dress-up-dress")]
pub mod e_npc_dress_up_dress;

#[cfg(feature = "e-npc-resident")]
pub mod e_npc_resident;

#[cfg(feature = "e-obj")]
pub mod e_obj;

#[cfg(feature = "e-obj-name")]
pub mod e_obj_name;

#[cfg(feature = "equip-race-category")]
pub mod equip_race_category;

#[cfg(feature = "equip-slot-category")]
pub mod equip_slot_category;

#[cfg(feature = "error")]
pub mod error;

#[cfg(feature = "eureka")]
pub mod eureka;

#[cfg(feature = "eureka-aether-item")]
pub mod eureka_aether_item;

#[cfg(feature = "eureka-aethernet")]
pub mod eureka_aethernet;

#[cfg(feature = "eureka-dungeon-portal")]
pub mod eureka_dungeon_portal;

#[cfg(feature = "eureka-grow-data")]
pub mod eureka_grow_data;

#[cfg(feature = "eureka-logos-mixer-probability")]
pub mod eureka_logos_mixer_probability;

#[cfg(feature = "eureka-magia-action")]
pub mod eureka_magia_action;

#[cfg(feature = "eureka-magicite-item")]
pub mod eureka_magicite_item;

#[cfg(feature = "eureka-magicite-item-type")]
pub mod eureka_magicite_item_type;

#[cfg(feature = "eureka-sphere-element-adjust")]
pub mod eureka_sphere_element_adjust;

#[cfg(feature = "eureka-story-progress")]
pub mod eureka_story_progress;

#[cfg(feature = "event-action")]
pub mod event_action;

#[cfg(feature = "event-custom-icon-type")]
pub mod event_custom_icon_type;

#[cfg(feature = "event-extra-condition-set")]
pub mod event_extra_condition_set;

#[cfg(feature = "event-gimmick-path-move")]
pub mod event_gimmick_path_move;

#[cfg(feature = "event-icon-priority")]
pub mod event_icon_priority;

#[cfg(feature = "event-icon-priority-pair")]
pub mod event_icon_priority_pair;

#[cfg(feature = "event-icon-type")]
pub mod event_icon_type;

#[cfg(feature = "event-item")]
pub mod event_item;

#[cfg(feature = "event-item-cast-timeline")]
pub mod event_item_cast_timeline;

#[cfg(feature = "event-item-category")]
pub mod event_item_category;

#[cfg(feature = "event-item-help")]
pub mod event_item_help;

#[cfg(feature = "event-item-timeline")]
pub mod event_item_timeline;

#[cfg(feature = "event-mount-gimmick-path-move")]
pub mod event_mount_gimmick_path_move;

#[cfg(feature = "event-path-move")]
pub mod event_path_move;

#[cfg(feature = "event-set-define")]
pub mod event_set_define;

#[cfg(feature = "event-situation-icon-tooltip")]
pub mod event_situation_icon_tooltip;

#[cfg(feature = "event-system-define")]
pub mod event_system_define;

#[cfg(feature = "event-tutorial")]
pub mod event_tutorial;

#[cfg(feature = "event-tutorial-page")]
pub mod event_tutorial_page;

#[cfg(feature = "event-vfx")]
pub mod event_vfx;

#[cfg(feature = "ex-hotbar-crossbar-index-type")]
pub mod ex_hotbar_crossbar_index_type;

#[cfg(feature = "exported-gathering-point")]
pub mod exported_gathering_point;

#[cfg(feature = "exported-sg")]
pub mod exported_sg;

#[cfg(feature = "extra-command")]
pub mod extra_command;

#[cfg(feature = "ex-version")]
pub mod ex_version;

#[cfg(feature = "fashion-check-theme-category")]
pub mod fashion_check_theme_category;

#[cfg(feature = "fashion-check-weekly-theme")]
pub mod fashion_check_weekly_theme;

#[cfg(feature = "fate")]
pub mod fate;

#[cfg(feature = "fate-event")]
pub mod fate_event;

#[cfg(feature = "fate-mode")]
pub mod fate_mode;

#[cfg(feature = "fate-progress-ui")]
pub mod fate_progress_ui;

#[cfg(feature = "fate-rule-ex")]
pub mod fate_rule_ex;

#[cfg(feature = "fate-shop")]
pub mod fate_shop;

#[cfg(feature = "fate-token-type")]
pub mod fate_token_type;

#[cfg(feature = "fc-activity")]
pub mod fc_activity;

#[cfg(feature = "fc-activity-category")]
pub mod fc_activity_category;

#[cfg(feature = "fc-authority")]
pub mod fc_authority;

#[cfg(feature = "fc-authority-category")]
pub mod fc_authority_category;

#[cfg(feature = "fc-chest-name")]
pub mod fc_chest_name;

#[cfg(feature = "fc-crest-symbol")]
pub mod fc_crest_symbol;

#[cfg(feature = "fcc-shop")]
pub mod fcc_shop;

#[cfg(feature = "fc-define")]
pub mod fc_define;

#[cfg(feature = "fc-hierarchy")]
pub mod fc_hierarchy;

#[cfg(feature = "fc-profile")]
pub mod fc_profile;

#[cfg(feature = "fc-rank")]
pub mod fc_rank;

#[cfg(feature = "fc-reputation")]
pub mod fc_reputation;

#[cfg(feature = "fc-rights")]
pub mod fc_rights;

#[cfg(feature = "festival")]
pub mod festival;

#[cfg(feature = "fgs-addon")]
pub mod fgs_addon;

#[cfg(feature = "fgs-stage-ui")]
pub mod fgs_stage_ui;

#[cfg(feature = "field-marker")]
pub mod field_marker;

#[cfg(feature = "fishing-bait-parameter")]
pub mod fishing_bait_parameter;

#[cfg(feature = "fishing-note-info")]
pub mod fishing_note_info;

#[cfg(feature = "fishing-record-type")]
pub mod fishing_record_type;

#[cfg(feature = "fishing-record-type-transient")]
pub mod fishing_record_type_transient;

#[cfg(feature = "fishing-spot")]
pub mod fishing_spot;

#[cfg(feature = "fish-parameter")]
pub mod fish_parameter;

#[cfg(feature = "fish-parameter-reverse")]
pub mod fish_parameter_reverse;

#[cfg(feature = "fitting-shop")]
pub mod fitting_shop;

#[cfg(feature = "fitting-shop-category")]
pub mod fitting_shop_category;

#[cfg(feature = "fitting-shop-category-item")]
pub mod fitting_shop_category_item;

#[cfg(feature = "fitting-shop-item-set")]
pub mod fitting_shop_item_set;

#[cfg(feature = "follow-mount")]
pub mod follow_mount;

#[cfg(feature = "frontline")]
pub mod frontline;

#[cfg(feature = "frontline-01")]
pub mod frontline_01;

#[cfg(feature = "frontline-02")]
pub mod frontline_02;

#[cfg(feature = "frontline-03")]
pub mod frontline_03;

#[cfg(feature = "furniture-catalog-category")]
pub mod furniture_catalog_category;

#[cfg(feature = "furniture-catalog-item-list")]
pub mod furniture_catalog_item_list;

#[cfg(feature = "game-condition-value-array")]
pub mod game_condition_value_array;

#[cfg(feature = "game-reward-obtain-type")]
pub mod game_reward_obtain_type;

#[cfg(feature = "gardening-seed")]
pub mod gardening_seed;

#[cfg(feature = "gatherer-crafter-lv-adjust-table")]
pub mod gatherer_crafter_lv_adjust_table;

#[cfg(feature = "gatherer-crafter-tool")]
pub mod gatherer_crafter_tool;

#[cfg(feature = "gatherer-reduction-reward")]
pub mod gatherer_reduction_reward;

#[cfg(feature = "gathering-condition")]
pub mod gathering_condition;

#[cfg(feature = "gathering-exp")]
pub mod gathering_exp;

#[cfg(feature = "gathering-item")]
pub mod gathering_item;

#[cfg(feature = "gathering-item-level-convert-table")]
pub mod gathering_item_level_convert_table;

#[cfg(feature = "gathering-item-point")]
pub mod gathering_item_point;

#[cfg(feature = "gathering-leve")]
pub mod gathering_leve;

#[cfg(feature = "gathering-leve-b-npc-entry")]
pub mod gathering_leve_b_npc_entry;

#[cfg(feature = "gathering-leve-route")]
pub mod gathering_leve_route;

#[cfg(feature = "gathering-leve-rule")]
pub mod gathering_leve_rule;

#[cfg(feature = "gathering-notebook-item")]
pub mod gathering_notebook_item;

#[cfg(feature = "gathering-notebook-list")]
pub mod gathering_notebook_list;

#[cfg(feature = "gathering-point")]
pub mod gathering_point;

#[cfg(feature = "gathering-point-base")]
pub mod gathering_point_base;

#[cfg(feature = "gathering-point-bonus")]
pub mod gathering_point_bonus;

#[cfg(feature = "gathering-point-bonus-type")]
pub mod gathering_point_bonus_type;

#[cfg(feature = "gathering-point-name")]
pub mod gathering_point_name;

#[cfg(feature = "gathering-point-transient")]
pub mod gathering_point_transient;

#[cfg(feature = "gathering-rare-pop-time-table")]
pub mod gathering_rare_pop_time_table;

#[cfg(feature = "gathering-sub-category")]
pub mod gathering_sub_category;

#[cfg(feature = "gathering-type")]
pub mod gathering_type;

#[cfg(feature = "gc-army-candidate-category")]
pub mod gc_army_candidate_category;

#[cfg(feature = "gc-army-capture")]
pub mod gc_army_capture;

#[cfg(feature = "gc-army-capture-tactics")]
pub mod gc_army_capture_tactics;

#[cfg(feature = "gc-army-equip-preset")]
pub mod gc_army_equip_preset;

#[cfg(feature = "gc-army-expedition")]
pub mod gc_army_expedition;

#[cfg(feature = "gc-army-expedition-member-bonus")]
pub mod gc_army_expedition_member_bonus;

#[cfg(feature = "gc-army-expedition-trait")]
pub mod gc_army_expedition_trait;

#[cfg(feature = "gc-army-expedition-trait-cond")]
pub mod gc_army_expedition_trait_cond;

#[cfg(feature = "gc-army-expedition-type")]
pub mod gc_army_expedition_type;

#[cfg(feature = "gc-army-member")]
pub mod gc_army_member;

#[cfg(feature = "gc-army-member-grow")]
pub mod gc_army_member_grow;

#[cfg(feature = "gc-army-member-grow-exp")]
pub mod gc_army_member_grow_exp;

#[cfg(feature = "gc-army-progress")]
pub mod gc_army_progress;

#[cfg(feature = "gc-army-training")]
pub mod gc_army_training;

#[cfg(feature = "gc-rank-gridania-female-text")]
pub mod gc_rank_gridania_female_text;

#[cfg(feature = "gc-rank-gridania-male-text")]
pub mod gc_rank_gridania_male_text;

#[cfg(feature = "gc-rank-limsa-female-text")]
pub mod gc_rank_limsa_female_text;

#[cfg(feature = "gc-rank-limsa-male-text")]
pub mod gc_rank_limsa_male_text;

#[cfg(feature = "gc-rank-uldah-female-text")]
pub mod gc_rank_uldah_female_text;

#[cfg(feature = "gc-rank-uldah-male-text")]
pub mod gc_rank_uldah_male_text;

#[cfg(feature = "gc-scrip-shop-category")]
pub mod gc_scrip_shop_category;

#[cfg(feature = "gc-scrip-shop-item")]
pub mod gc_scrip_shop_item;

#[cfg(feature = "gc-shop")]
pub mod gc_shop;

#[cfg(feature = "gc-shop-item-category")]
pub mod gc_shop_item_category;

#[cfg(feature = "gc-supply-define")]
pub mod gc_supply_define;

#[cfg(feature = "gc-supply-duty")]
pub mod gc_supply_duty;

#[cfg(feature = "gc-supply-duty-reward")]
pub mod gc_supply_duty_reward;

#[cfg(feature = "general-action")]
pub mod general_action;

#[cfg(feature = "gfate")]
pub mod gfate;

#[cfg(feature = "g-fate-climbing")]
pub mod g_fate_climbing;

#[cfg(feature = "g-fate-climbing-2")]
pub mod g_fate_climbing_2;

#[cfg(feature = "g-fate-climbing-2-content")]
pub mod g_fate_climbing_2_content;

#[cfg(feature = "g-fate-climbing-2-totem-type")]
pub mod g_fate_climbing_2_totem_type;

#[cfg(feature = "g-fate-dance")]
pub mod g_fate_dance;

#[cfg(feature = "g-fate-hidden-object")]
pub mod g_fate_hidden_object;

#[cfg(feature = "g-fate-ride-shooting")]
pub mod g_fate_ride_shooting;

#[cfg(feature = "g-fate-roulette")]
pub mod g_fate_roulette;

#[cfg(feature = "g-fate-stelth")]
pub mod g_fate_stelth;

#[cfg(feature = "g-fate-type")]
pub mod g_fate_type;

#[cfg(feature = "gil-shop")]
pub mod gil_shop;

#[cfg(feature = "gil-shop-info")]
pub mod gil_shop_info;

#[cfg(feature = "gil-shop-item")]
pub mod gil_shop_item;

#[cfg(feature = "gimmick-accessor")]
pub mod gimmick_accessor;

#[cfg(feature = "gimmick-bill")]
pub mod gimmick_bill;

#[cfg(feature = "gimmick-jump")]
pub mod gimmick_jump;

#[cfg(feature = "gimmick-rect")]
pub mod gimmick_rect;

#[cfg(feature = "gimmick-talk")]
pub mod gimmick_talk;

#[cfg(feature = "gimmick-yes-no")]
pub mod gimmick_yes_no;

#[cfg(feature = "glasses")]
pub mod glasses;

#[cfg(feature = "glasses-style")]
pub mod glasses_style;

#[cfg(feature = "gold-saucer-arcade-machine")]
pub mod gold_saucer_arcade_machine;

#[cfg(feature = "gold-saucer-content")]
pub mod gold_saucer_content;

#[cfg(feature = "gold-saucer-talk")]
pub mod gold_saucer_talk;

#[cfg(feature = "gold-saucer-text-data")]
pub mod gold_saucer_text_data;

#[cfg(feature = "grand-company")]
pub mod grand_company;

#[cfg(feature = "grand-company-rank")]
pub mod grand_company_rank;

#[cfg(feature = "group-pose-character-show-preset")]
pub mod group_pose_character_show_preset;

#[cfg(feature = "group-pose-chara-status")]
pub mod group_pose_chara_status;

#[cfg(feature = "group-pose-frame")]
pub mod group_pose_frame;

#[cfg(feature = "group-pose-stamp")]
pub mod group_pose_stamp;

#[cfg(feature = "group-pose-stamp-category")]
pub mod group_pose_stamp_category;

#[cfg(feature = "group-pose-stamp-font-color")]
pub mod group_pose_stamp_font_color;

#[cfg(feature = "guardian-deity")]
pub mod guardian_deity;

#[cfg(feature = "guide")]
pub mod guide;

#[cfg(feature = "guide-page")]
pub mod guide_page;

#[cfg(feature = "guide-page-string")]
pub mod guide_page_string;

#[cfg(feature = "guide-title")]
pub mod guide_title;

#[cfg(feature = "guildleve-assignment")]
pub mod guildleve_assignment;

#[cfg(feature = "guildleve-assignment-category")]
pub mod guildleve_assignment_category;

#[cfg(feature = "guildleve-assignment-talk")]
pub mod guildleve_assignment_talk;

#[cfg(feature = "guild-order")]
pub mod guild_order;

#[cfg(feature = "guild-order-guide")]
pub mod guild_order_guide;

#[cfg(feature = "guild-order-officer")]
pub mod guild_order_officer;

#[cfg(feature = "hair-make-type")]
pub mod hair_make_type;

#[cfg(feature = "halloween-npc-select")]
pub mod halloween_npc_select;

#[cfg(feature = "house-retainer-pose")]
pub mod house_retainer_pose;

#[cfg(feature = "housing-aethernet")]
pub mod housing_aethernet;

#[cfg(feature = "housing-appeal")]
pub mod housing_appeal;

#[cfg(feature = "housing-employment-npc-list")]
pub mod housing_employment_npc_list;

#[cfg(feature = "housing-employment-npc-race")]
pub mod housing_employment_npc_race;

#[cfg(feature = "housing-exterior")]
pub mod housing_exterior;

#[cfg(feature = "housing-furniture")]
pub mod housing_furniture;

#[cfg(feature = "housing-indoor-territory")]
pub mod housing_indoor_territory;

#[cfg(feature = "housing-interior")]
pub mod housing_interior;

#[cfg(feature = "housing-land-set")]
pub mod housing_land_set;

#[cfg(feature = "housing-map-marker-info")]
pub mod housing_map_marker_info;

#[cfg(feature = "housing-mate-authority")]
pub mod housing_mate_authority;

#[cfg(feature = "housing-merchant-pose")]
pub mod housing_merchant_pose;

#[cfg(feature = "housing-pile-limit")]
pub mod housing_pile_limit;

#[cfg(feature = "housing-placement")]
pub mod housing_placement;

#[cfg(feature = "housing-preset")]
pub mod housing_preset;

#[cfg(feature = "housing-renovation")]
pub mod housing_renovation;

#[cfg(feature = "housing-training-doll")]
pub mod housing_training_doll;

#[cfg(feature = "housing-united-exterior")]
pub mod housing_united_exterior;

#[cfg(feature = "housing-unplacement")]
pub mod housing_unplacement;

#[cfg(feature = "housing-yard-object")]
pub mod housing_yard_object;

#[cfg(feature = "how-to")]
pub mod how_to;

#[cfg(feature = "how-to-category")]
pub mod how_to_category;

#[cfg(feature = "how-to-page")]
pub mod how_to_page;

#[cfg(feature = "hud")]
pub mod hud;

#[cfg(feature = "hud-transient")]
pub mod hud_transient;

#[cfg(feature = "huge-craftworks-npc")]
pub mod huge_craftworks_npc;

#[cfg(feature = "huge-craftworks-rank")]
pub mod huge_craftworks_rank;

#[cfg(feature = "hwd-announce")]
pub mod hwd_announce;

#[cfg(feature = "hwd-crafter-supply")]
pub mod hwd_crafter_supply;

#[cfg(feature = "hwd-crafter-supply-reward")]
pub mod hwd_crafter_supply_reward;

#[cfg(feature = "hwd-crafter-supply-term")]
pub mod hwd_crafter_supply_term;

#[cfg(feature = "hwd-dev-layer-control")]
pub mod hwd_dev_layer_control;

#[cfg(feature = "hwd-dev-level-ui")]
pub mod hwd_dev_level_ui;

#[cfg(feature = "hwd-dev-level-web-text")]
pub mod hwd_dev_level_web_text;

#[cfg(feature = "hwd-dev-lively")]
pub mod hwd_dev_lively;

#[cfg(feature = "hwd-dev-progress")]
pub mod hwd_dev_progress;

#[cfg(feature = "hwd-gathere-inspect-term")]
pub mod hwd_gathere_inspect_term;

#[cfg(feature = "hwd-gatherer-inspection")]
pub mod hwd_gatherer_inspection;

#[cfg(feature = "hwd-gatherer-inspection-reward")]
pub mod hwd_gatherer_inspection_reward;

#[cfg(feature = "hwd-info-board-article")]
pub mod hwd_info_board_article;

#[cfg(feature = "hwd-info-board-article-transient")]
pub mod hwd_info_board_article_transient;

#[cfg(feature = "hwd-info-board-article-type")]
pub mod hwd_info_board_article_type;

#[cfg(feature = "hwd-info-board-back-number")]
pub mod hwd_info_board_back_number;

#[cfg(feature = "hwd-level-change-deception")]
pub mod hwd_level_change_deception;

#[cfg(feature = "hwd-shared-group")]
pub mod hwd_shared_group;

#[cfg(feature = "hwd-shared-group-control-param")]
pub mod hwd_shared_group_control_param;

#[cfg(feature = "icon-language")]
pub mod icon_language;

#[cfg(feature = "ikd-content-bonus")]
pub mod ikd_content_bonus;

#[cfg(feature = "ikd-fish-param")]
pub mod ikd_fish_param;

#[cfg(feature = "ikd-player-mission-condition")]
pub mod ikd_player_mission_condition;

#[cfg(feature = "ikd-route")]
pub mod ikd_route;

#[cfg(feature = "ikd-route-table")]
pub mod ikd_route_table;

#[cfg(feature = "ikd-spot")]
pub mod ikd_spot;

#[cfg(feature = "ikd-time-define")]
pub mod ikd_time_define;

#[cfg(feature = "inclusion-shop")]
pub mod inclusion_shop;

#[cfg(feature = "inclusion-shop-category")]
pub mod inclusion_shop_category;

#[cfg(feature = "inclusion-shop-series")]
pub mod inclusion_shop_series;

#[cfg(feature = "inclusion-shop-welcom")]
pub mod inclusion_shop_welcom;

#[cfg(feature = "inclusion-shop-welcom-text")]
pub mod inclusion_shop_welcom_text;

#[cfg(feature = "individual-weather")]
pub mod individual_weather;

#[cfg(feature = "instance-content")]
pub mod instance_content;

#[cfg(feature = "instance-content-buff")]
pub mod instance_content_buff;

#[cfg(feature = "instance-content-guide")]
pub mod instance_content_guide;

#[cfg(feature = "instance-content-qic-data")]
pub mod instance_content_qic_data;

#[cfg(feature = "instance-content-reward-item")]
pub mod instance_content_reward_item;

#[cfg(feature = "instance-content-text-data")]
pub mod instance_content_text_data;

#[cfg(feature = "instance-content-type")]
pub mod instance_content_type;

#[cfg(feature = "item")]
pub mod item;

#[cfg(feature = "item-action")]
pub mod item_action;

#[cfg(feature = "item-action-telepo")]
pub mod item_action_telepo;

#[cfg(feature = "item-barter-check")]
pub mod item_barter_check;

#[cfg(feature = "item-barter-warning")]
pub mod item_barter_warning;

#[cfg(feature = "item-food")]
pub mod item_food;

#[cfg(feature = "item-level")]
pub mod item_level;

#[cfg(feature = "item-once-hq-masterpiece")]
pub mod item_once_hq_masterpiece;

#[cfg(feature = "item-repair-price")]
pub mod item_repair_price;

#[cfg(feature = "item-repair-resource")]
pub mod item_repair_resource;

#[cfg(feature = "item-retainer-level-up")]
pub mod item_retainer_level_up;

#[cfg(feature = "item-search-category")]
pub mod item_search_category;

#[cfg(feature = "item-series")]
pub mod item_series;

#[cfg(feature = "item-sort-category")]
pub mod item_sort_category;

#[cfg(feature = "item-special-bonus")]
pub mod item_special_bonus;

#[cfg(feature = "item-stain-condition")]
pub mod item_stain_condition;

#[cfg(feature = "item-ui-category")]
pub mod item_ui_category;

#[cfg(feature = "jigsaw-score")]
pub mod jigsaw_score;

#[cfg(feature = "jigsaw-time-bonus")]
pub mod jigsaw_time_bonus;

#[cfg(feature = "jingle")]
pub mod jingle;

#[cfg(feature = "job-hud-manual")]
pub mod job_hud_manual;

#[cfg(feature = "job-hud-manual-priority")]
pub mod job_hud_manual_priority;

#[cfg(feature = "journal-category")]
pub mod journal_category;

#[cfg(feature = "journal-genre")]
pub mod journal_genre;

#[cfg(feature = "journal-section")]
pub mod journal_section;

#[cfg(feature = "kine-driver-off-group")]
pub mod kine_driver_off_group;

#[cfg(feature = "knockback")]
pub mod knockback;

#[cfg(feature = "legacy-quest")]
pub mod legacy_quest;

#[cfg(feature = "leve")]
pub mod leve;

#[cfg(feature = "leve-assignment-type")]
pub mod leve_assignment_type;

#[cfg(feature = "leve-client")]
pub mod leve_client;

#[cfg(feature = "level")]
pub mod level;

#[cfg(feature = "leve-reward-item")]
pub mod leve_reward_item;

#[cfg(feature = "leve-reward-item-group")]
pub mod leve_reward_item_group;

#[cfg(feature = "leve-string")]
pub mod leve_string;

#[cfg(feature = "leve-system-define")]
pub mod leve_system_define;

#[cfg(feature = "leve-vfx")]
pub mod leve_vfx;

#[cfg(feature = "lfg-extension-content")]
pub mod lfg_extension_content;

#[cfg(feature = "link-race")]
pub mod link_race;

#[cfg(feature = "lively-actor-group")]
pub mod lively_actor_group;

#[cfg(feature = "live-minigames")]
pub mod live_minigames;

#[cfg(feature = "live-minigames-dynamic-define")]
pub mod live_minigames_dynamic_define;

#[cfg(feature = "live-minigames-object-event")]
pub mod live_minigames_object_event;

#[cfg(feature = "live-minigames-territory-type")]
pub mod live_minigames_territory_type;

#[cfg(feature = "loading-image")]
pub mod loading_image;

#[cfg(feature = "loading-tips")]
pub mod loading_tips;

#[cfg(feature = "loading-tips-sub")]
pub mod loading_tips_sub;

#[cfg(feature = "lobby")]
pub mod lobby;

#[cfg(feature = "lockon")]
pub mod lockon;

#[cfg(feature = "log-filter")]
pub mod log_filter;

#[cfg(feature = "log-kind")]
pub mod log_kind;

#[cfg(feature = "log-message")]
pub mod log_message;

#[cfg(feature = "loot-mode-type")]
pub mod loot_mode_type;

#[cfg(feature = "lottery-exchange-shop")]
pub mod lottery_exchange_shop;

#[cfg(feature = "macro-icon")]
pub mod macro_icon;

#[cfg(feature = "macro-icon-redirect-old")]
pub mod macro_icon_redirect_old;

#[cfg(feature = "main-command")]
pub mod main_command;

#[cfg(feature = "main-command-category")]
pub mod main_command_category;

#[cfg(feature = "manderville-weapon-enhance")]
pub mod manderville_weapon_enhance;

#[cfg(feature = "maneuvers")]
pub mod maneuvers;

#[cfg(feature = "maneuvers-armor")]
pub mod maneuvers_armor;

#[cfg(feature = "map")]
pub mod map;

#[cfg(feature = "map-condition")]
pub mod map_condition;

#[cfg(feature = "map-exclusive")]
pub mod map_exclusive;

#[cfg(feature = "map-marker")]
pub mod map_marker;

#[cfg(feature = "map-marker-region")]
pub mod map_marker_region;

#[cfg(feature = "map-replace")]
pub mod map_replace;

#[cfg(feature = "map-symbol")]
pub mod map_symbol;

#[cfg(feature = "map-transient-pv-p-map")]
pub mod map_transient_pv_p_map;

#[cfg(feature = "map-type")]
pub mod map_type;

#[cfg(feature = "marker")]
pub mod marker;

#[cfg(feature = "massive-pc-content")]
pub mod massive_pc_content;

#[cfg(feature = "massive-pc-content-battle-talk")]
pub mod massive_pc_content_battle_talk;

#[cfg(feature = "massive-pc-content-text-data")]
pub mod massive_pc_content_text_data;

#[cfg(feature = "massive-pc-content-todo")]
pub mod massive_pc_content_todo;

#[cfg(feature = "mate-authority-category")]
pub mod mate_authority_category;

#[cfg(feature = "materia")]
pub mod materia;

#[cfg(feature = "materia-grade")]
pub mod materia_grade;

#[cfg(feature = "materia-join-rate")]
pub mod materia_join_rate;

#[cfg(feature = "materia-join-rate-gather-craft")]
pub mod materia_join_rate_gather_craft;

#[cfg(feature = "materia-param")]
pub mod materia_param;

#[cfg(feature = "mc-guffin")]
pub mod mc_guffin;

#[cfg(feature = "mc-guffin-ui-data")]
pub mod mc_guffin_ui_data;

#[cfg(feature = "mini-game-ra")]
pub mod mini_game_ra;

#[cfg(feature = "mini-game-ra-notes")]
pub mod mini_game_ra_notes;

#[cfg(feature = "mini-game-turn-break-action")]
pub mod mini_game_turn_break_action;

#[cfg(feature = "mini-game-turn-break-const")]
pub mod mini_game_turn_break_const;

#[cfg(feature = "mini-game-turn-break-enemy")]
pub mod mini_game_turn_break_enemy;

#[cfg(feature = "mini-game-turn-break-pop")]
pub mod mini_game_turn_break_pop;

#[cfg(feature = "mini-game-turn-break-pop-offset")]
pub mod mini_game_turn_break_pop_offset;

#[cfg(feature = "mini-game-turn-break-stage")]
pub mod mini_game_turn_break_stage;

#[cfg(feature = "mini-game-turn-break-status")]
pub mod mini_game_turn_break_status;

#[cfg(feature = "minion-race")]
pub mod minion_race;

#[cfg(feature = "minion-rules")]
pub mod minion_rules;

#[cfg(feature = "minion-skill-type")]
pub mod minion_skill_type;

#[cfg(feature = "minion-stage")]
pub mod minion_stage;

#[cfg(feature = "mirage-store-set-item")]
pub mod mirage_store_set_item;

#[cfg(feature = "mirage-store-set-item-lookup")]
pub mod mirage_store_set_item_lookup;

#[cfg(feature = "mji-animals")]
pub mod mji_animals;

#[cfg(feature = "mji-building")]
pub mod mji_building;

#[cfg(feature = "mji-building-place")]
pub mod mji_building_place;

#[cfg(feature = "mji-craftworks-object")]
pub mod mji_craftworks_object;

#[cfg(feature = "mji-craftworks-object-theme")]
pub mod mji_craftworks_object_theme;

#[cfg(feature = "mji-craftworks-popularity")]
pub mod mji_craftworks_popularity;

#[cfg(feature = "mji-craftworks-popularity-type")]
pub mod mji_craftworks_popularity_type;

#[cfg(feature = "mji-craftworks-rank-ratio")]
pub mod mji_craftworks_rank_ratio;

#[cfg(feature = "mji-craftworks-supply-define")]
pub mod mji_craftworks_supply_define;

#[cfg(feature = "mji-craftworks-tension")]
pub mod mji_craftworks_tension;

#[cfg(feature = "mji-crop-seed")]
pub mod mji_crop_seed;

#[cfg(feature = "mji-disposal-shop-item")]
pub mod mji_disposal_shop_item;

#[cfg(feature = "mji-disposal-shop-ui-category")]
pub mod mji_disposal_shop_ui_category;

#[cfg(feature = "mji-farm-pasture-rank")]
pub mod mji_farm_pasture_rank;

#[cfg(feature = "mji-function")]
pub mod mji_function;

#[cfg(feature = "mji-gardenscaping")]
pub mod mji_gardenscaping;

#[cfg(feature = "mji-gathering")]
pub mod mji_gathering;

#[cfg(feature = "mji-gathering-item")]
pub mod mji_gathering_item;

#[cfg(feature = "mji-gathering-object")]
pub mod mji_gathering_object;

#[cfg(feature = "mji-gathering-tool")]
pub mod mji_gathering_tool;

#[cfg(feature = "mji-hud-mode")]
pub mod mji_hud_mode;

#[cfg(feature = "mji-item-category")]
pub mod mji_item_category;

#[cfg(feature = "mji-item-pouch")]
pub mod mji_item_pouch;

#[cfg(feature = "mji-key-item")]
pub mod mji_key_item;

#[cfg(feature = "mji-landmark")]
pub mod mji_landmark;

#[cfg(feature = "mji-landmark-place")]
pub mod mji_landmark_place;

#[cfg(feature = "mji-lively-actor")]
pub mod mji_lively_actor;

#[cfg(feature = "mji-minion-pop-areas")]
pub mod mji_minion_pop_areas;

#[cfg(feature = "mji-name")]
pub mod mji_name;

#[cfg(feature = "mji-nekomimi-request")]
pub mod mji_nekomimi_request;

#[cfg(feature = "mji-progress")]
pub mod mji_progress;

#[cfg(feature = "mji-rank")]
pub mod mji_rank;

#[cfg(feature = "mji-recipe")]
pub mod mji_recipe;

#[cfg(feature = "mji-recipe-material")]
pub mod mji_recipe_material;

#[cfg(feature = "mji-stockyard-management-area")]
pub mod mji_stockyard_management_area;

#[cfg(feature = "mji-stockyard-management-table")]
pub mod mji_stockyard_management_table;

#[cfg(feature = "mji-text")]
pub mod mji_text;

#[cfg(feature = "mji-village-appearance-sg")]
pub mod mji_village_appearance_sg;

#[cfg(feature = "mji-village-appearance-ui")]
pub mod mji_village_appearance_ui;

#[cfg(feature = "mji-village-development")]
pub mod mji_village_development;

#[cfg(feature = "mkdb-npc-data")]
pub mod mkdb_npc_data;

#[cfg(feature = "mkd-chain")]
pub mod mkd_chain;

#[cfg(feature = "mkd-data")]
pub mod mkd_data;

#[cfg(feature = "mkd-grow-data")]
pub mod mkd_grow_data;

#[cfg(feature = "mkd-grow-data-s-job")]
pub mod mkd_grow_data_s_job;

#[cfg(feature = "mkd-lore")]
pub mod mkd_lore;

#[cfg(feature = "mkd-relic-growth-2-category")]
pub mod mkd_relic_growth_2_category;

#[cfg(feature = "mkd-relic-growth-2-content-list")]
pub mod mkd_relic_growth_2_content_list;

#[cfg(feature = "mkd-relic-growth-2-monster")]
pub mod mkd_relic_growth_2_monster;

#[cfg(feature = "mkd-support-job")]
pub mod mkd_support_job;

#[cfg(feature = "mkd-trait")]
pub mod mkd_trait;

#[cfg(feature = "mob-hunt-order")]
pub mod mob_hunt_order;

#[cfg(feature = "mob-hunt-order-type")]
pub mod mob_hunt_order_type;

#[cfg(feature = "mob-hunt-reward")]
pub mod mob_hunt_reward;

#[cfg(feature = "mob-hunt-reward-cap")]
pub mod mob_hunt_reward_cap;

#[cfg(feature = "mob-hunt-target")]
pub mod mob_hunt_target;

#[cfg(feature = "model-attribute")]
pub mod model_attribute;

#[cfg(feature = "model-chara")]
pub mod model_chara;

#[cfg(feature = "model-scale")]
pub mod model_scale;

#[cfg(feature = "model-skeleton")]
pub mod model_skeleton;

#[cfg(feature = "model-state")]
pub mod model_state;

#[cfg(feature = "monster-note")]
pub mod monster_note;

#[cfg(feature = "monster-note-target")]
pub mod monster_note_target;

#[cfg(feature = "motion-timeline")]
pub mod motion_timeline;

#[cfg(feature = "motion-timeline-advance-blend")]
pub mod motion_timeline_advance_blend;

#[cfg(feature = "motion-timeline-blend-table")]
pub mod motion_timeline_blend_table;

#[cfg(feature = "mount")]
pub mod mount;

#[cfg(feature = "mount-action")]
pub mod mount_action;

#[cfg(feature = "mount-customize")]
pub mod mount_customize;

#[cfg(feature = "mount-flying-condition")]
pub mod mount_flying_condition;

#[cfg(feature = "mount-speed")]
pub mod mount_speed;

#[cfg(feature = "mount-transient")]
pub mod mount_transient;

#[cfg(feature = "move-control")]
pub mod move_control;

#[cfg(feature = "move-timeline")]
pub mod move_timeline;

#[cfg(feature = "move-vfx")]
pub mod move_vfx;

#[cfg(feature = "movie-staff-list")]
pub mod movie_staff_list;

#[cfg(feature = "movie-subtitle")]
pub mod movie_subtitle;

#[cfg(feature = "movie-subtitle-500")]
pub mod movie_subtitle_500;

#[cfg(feature = "movie-subtitle-voyage")]
pub mod movie_subtitle_voyage;

#[cfg(feature = "multiple-help")]
pub mod multiple_help;

#[cfg(feature = "multiple-help-page")]
pub mod multiple_help_page;

#[cfg(feature = "multiple-help-string")]
pub mod multiple_help_string;

#[cfg(feature = "myc-temporary-item")]
pub mod myc_temporary_item;

#[cfg(feature = "myc-temporary-item-ui-category")]
pub mod myc_temporary_item_ui_category;

#[cfg(feature = "myc-war-result-notebook")]
pub mod myc_war_result_notebook;

#[cfg(feature = "notebook-division")]
pub mod notebook_division;

#[cfg(feature = "notebook-division-category")]
pub mod notebook_division_category;

#[cfg(feature = "notebook-list")]
pub mod notebook_list;

#[cfg(feature = "notorious-monster")]
pub mod notorious_monster;

#[cfg(feature = "notorious-monster-territory")]
pub mod notorious_monster_territory;

#[cfg(feature = "npc-equip")]
pub mod npc_equip;

#[cfg(feature = "npc-yell")]
pub mod npc_yell;

#[cfg(feature = "omen")]
pub mod omen;

#[cfg(feature = "omikuji")]
pub mod omikuji;

#[cfg(feature = "omikuji-guidance")]
pub mod omikuji_guidance;

#[cfg(feature = "online-status")]
pub mod online_status;

#[cfg(feature = "open-content")]
pub mod open_content;

#[cfg(feature = "open-content-candidate-name")]
pub mod open_content_candidate_name;

#[cfg(feature = "opening")]
pub mod opening;

#[cfg(feature = "opening-system-define")]
pub mod opening_system_define;

#[cfg(feature = "open-lua-ui")]
pub mod open_lua_ui;

#[cfg(feature = "orchestrion")]
pub mod orchestrion;

#[cfg(feature = "orchestrion-category")]
pub mod orchestrion_category;

#[cfg(feature = "orchestrion-path")]
pub mod orchestrion_path;

#[cfg(feature = "orchestrion-uiparam")]
pub mod orchestrion_uiparam;

#[cfg(feature = "ornament")]
pub mod ornament;

#[cfg(feature = "ornament-action")]
pub mod ornament_action;

#[cfg(feature = "ornament-customize")]
pub mod ornament_customize;

#[cfg(feature = "ornament-customize-group")]
pub mod ornament_customize_group;

#[cfg(feature = "ornament-transient")]
pub mod ornament_transient;

#[cfg(feature = "param-grow")]
pub mod param_grow;

#[cfg(feature = "party-content")]
pub mod party_content;

#[cfg(feature = "party-content-cutscene")]
pub mod party_content_cutscene;

#[cfg(feature = "party-content-text-data")]
pub mod party_content_text_data;

#[cfg(feature = "party-content-transient")]
pub mod party_content_transient;

#[cfg(feature = "patch-mark")]
pub mod patch_mark;

#[cfg(feature = "perform")]
pub mod perform;

#[cfg(feature = "perform-group")]
pub mod perform_group;

#[cfg(feature = "perform-guide-score")]
pub mod perform_guide_score;

#[cfg(feature = "perform-transient")]
pub mod perform_transient;

#[cfg(feature = "permission")]
pub mod permission;

#[cfg(feature = "pet")]
pub mod pet;

#[cfg(feature = "pet-action")]
pub mod pet_action;

#[cfg(feature = "pet-mirage")]
pub mod pet_mirage;

#[cfg(feature = "physics-group")]
pub mod physics_group;

#[cfg(feature = "physics-off-group")]
pub mod physics_off_group;

#[cfg(feature = "physics-parameter")]
pub mod physics_parameter;

#[cfg(feature = "physics-wind")]
pub mod physics_wind;

#[cfg(feature = "picture")]
pub mod picture;

#[cfg(feature = "place-name")]
pub mod place_name;

#[cfg(feature = "place-name-replace")]
pub mod place_name_replace;

#[cfg(feature = "plant-pot-flower-seed")]
pub mod plant_pot_flower_seed;

#[cfg(feature = "platform")]
pub mod platform;

#[cfg(feature = "player-search-location")]
pub mod player_search_location;

#[cfg(feature = "player-search-sub-location")]
pub mod player_search_sub_location;

#[cfg(feature = "point-menu")]
pub mod point_menu;

#[cfg(feature = "point-menu-choice")]
pub mod point_menu_choice;

#[cfg(feature = "point-menu-string")]
pub mod point_menu_string;

#[cfg(feature = "pre-handler")]
pub mod pre_handler;

#[cfg(feature = "pre-handler-movement")]
pub mod pre_handler_movement;

#[cfg(feature = "preset-camera")]
pub mod preset_camera;

#[cfg(feature = "preset-camera-adjust")]
pub mod preset_camera_adjust;

#[cfg(feature = "previewable-items")]
pub mod previewable_items;

#[cfg(feature = "public-content")]
pub mod public_content;

#[cfg(feature = "public-content-cutscene")]
pub mod public_content_cutscene;

#[cfg(feature = "public-content-text-data")]
pub mod public_content_text_data;

#[cfg(feature = "public-content-type")]
pub mod public_content_type;

#[cfg(feature = "pv-p-action")]
pub mod pv_p_action;

#[cfg(feature = "pv-p-action-sort")]
pub mod pv_p_action_sort;

#[cfg(feature = "pv-p-base-param-value")]
pub mod pv_p_base_param_value;

#[cfg(feature = "pv-p-initial-select-action-trait")]
pub mod pv_p_initial_select_action_trait;

#[cfg(feature = "pv-p-rank")]
pub mod pv_p_rank;

#[cfg(feature = "pv-p-rank-transient")]
pub mod pv_p_rank_transient;

#[cfg(feature = "pv-p-select-action")]
pub mod pv_p_select_action;

#[cfg(feature = "pv-p-select-trait")]
pub mod pv_p_select_trait;

#[cfg(feature = "pv-p-select-trait-transient")]
pub mod pv_p_select_trait_transient;

#[cfg(feature = "pv-p-series")]
pub mod pv_p_series;

#[cfg(feature = "pv-p-series-level")]
pub mod pv_p_series_level;

#[cfg(feature = "pv-p-trait")]
pub mod pv_p_trait;

#[cfg(feature = "qte")]
pub mod qte;

#[cfg(feature = "quest")]
pub mod quest;

#[cfg(feature = "quest-accept-addition-condition")]
pub mod quest_accept_addition_condition;

#[cfg(feature = "quest-additional-tool-icon")]
pub mod quest_additional_tool_icon;

#[cfg(feature = "quest-around-player-hide")]
pub mod quest_around_player_hide;

#[cfg(feature = "quest-around-player-hide-ext")]
pub mod quest_around_player_hide_ext;

#[cfg(feature = "quest-battle")]
pub mod quest_battle;

#[cfg(feature = "quest-battle-resident")]
pub mod quest_battle_resident;

#[cfg(feature = "quest-battle-system-define")]
pub mod quest_battle_system_define;

#[cfg(feature = "quest-chapter")]
pub mod quest_chapter;

#[cfg(feature = "quest-class-job-reward")]
pub mod quest_class_job_reward;

#[cfg(feature = "quest-class-job-supply")]
pub mod quest_class_job_supply;

#[cfg(feature = "quest-custom-todo")]
pub mod quest_custom_todo;

#[cfg(feature = "quest-define-client")]
pub mod quest_define_client;

#[cfg(feature = "quest-derived-class")]
pub mod quest_derived_class;

#[cfg(feature = "quest-effect")]
pub mod quest_effect;

#[cfg(feature = "quest-effect-define")]
pub mod quest_effect_define;

#[cfg(feature = "quest-effect-type")]
pub mod quest_effect_type;

#[cfg(feature = "quest-equip-model")]
pub mod quest_equip_model;

#[cfg(feature = "quest-event-area-entrance-info")]
pub mod quest_event_area_entrance_info;

#[cfg(feature = "quest-hide-reward")]
pub mod quest_hide_reward;

#[cfg(feature = "quest-link-marker")]
pub mod quest_link_marker;

#[cfg(feature = "quest-link-marker-icon")]
pub mod quest_link_marker_icon;

#[cfg(feature = "quest-link-marker-set")]
pub mod quest_link_marker_set;

#[cfg(feature = "quest-recomplete")]
pub mod quest_recomplete;

#[cfg(feature = "quest-redo")]
pub mod quest_redo;

#[cfg(feature = "quest-redo-chapter")]
pub mod quest_redo_chapter;

#[cfg(feature = "quest-redo-chapter-ui")]
pub mod quest_redo_chapter_ui;

#[cfg(feature = "quest-redo-chapter-ui-category")]
pub mod quest_redo_chapter_ui_category;

#[cfg(feature = "quest-redo-chapter-ui-tab")]
pub mod quest_redo_chapter_ui_tab;

#[cfg(feature = "quest-redo-incomp-chapter")]
pub mod quest_redo_incomp_chapter;

#[cfg(feature = "quest-redo-valid-custom-talk")]
pub mod quest_redo_valid_custom_talk;

#[cfg(feature = "quest-repeat-flag")]
pub mod quest_repeat_flag;

#[cfg(feature = "quest-reward-other")]
pub mod quest_reward_other;

#[cfg(feature = "quest-scene-abort-condition")]
pub mod quest_scene_abort_condition;

#[cfg(feature = "quest-scene-abort-condition-flag")]
pub mod quest_scene_abort_condition_flag;

#[cfg(feature = "quest-scene-abort-condition-type")]
pub mod quest_scene_abort_condition_type;

#[cfg(feature = "quest-select-title")]
pub mod quest_select_title;

#[cfg(feature = "quest-set-define")]
pub mod quest_set_define;

#[cfg(feature = "quest-status-param")]
pub mod quest_status_param;

#[cfg(feature = "quest-sub-command")]
pub mod quest_sub_command;

#[cfg(feature = "quest-system-define")]
pub mod quest_system_define;

#[cfg(feature = "quick-chat")]
pub mod quick_chat;

#[cfg(feature = "quick-chat-transient")]
pub mod quick_chat_transient;

#[cfg(feature = "race")]
pub mod race;

#[cfg(feature = "racing-chocobo-grade")]
pub mod racing_chocobo_grade;

#[cfg(feature = "racing-chocobo-item")]
pub mod racing_chocobo_item;

#[cfg(feature = "racing-chocobo-name")]
pub mod racing_chocobo_name;

#[cfg(feature = "racing-chocobo-name-category")]
pub mod racing_chocobo_name_category;

#[cfg(feature = "racing-chocobo-name-info")]
pub mod racing_chocobo_name_info;

#[cfg(feature = "racing-chocobo-param")]
pub mod racing_chocobo_param;

#[cfg(feature = "raid-finder-param")]
pub mod raid_finder_param;

#[cfg(feature = "reaction-event-object")]
pub mod reaction_event_object;

#[cfg(feature = "reaction-event-object-info")]
pub mod reaction_event_object_info;

#[cfg(feature = "recast-navimesh")]
pub mod recast_navimesh;

#[cfg(feature = "recipe")]
pub mod recipe;

#[cfg(feature = "recipe-level-table")]
pub mod recipe_level_table;

#[cfg(feature = "recipe-lookup")]
pub mod recipe_lookup;

#[cfg(feature = "recipe-notebook-list")]
pub mod recipe_notebook_list;

#[cfg(feature = "recipe-sub-category")]
pub mod recipe_sub_category;

#[cfg(feature = "recommend-contents")]
pub mod recommend_contents;

#[cfg(feature = "relic")]
pub mod relic;

#[cfg(feature = "relic-3")]
pub mod relic_3;

#[cfg(feature = "relic-3-materia")]
pub mod relic_3_materia;

#[cfg(feature = "relic-3-rate")]
pub mod relic_3_rate;

#[cfg(feature = "relic-3-rate-pattern")]
pub mod relic_3_rate_pattern;

#[cfg(feature = "relic-6-magicite")]
pub mod relic_6_magicite;

#[cfg(feature = "relic-item")]
pub mod relic_item;

#[cfg(feature = "relic-materia")]
pub mod relic_materia;

#[cfg(feature = "relic-note")]
pub mod relic_note;

#[cfg(feature = "relic-note-category")]
pub mod relic_note_category;

#[cfg(feature = "replace-action")]
pub mod replace_action;

#[cfg(feature = "resident")]
pub mod resident;

#[cfg(feature = "resident-motion-type")]
pub mod resident_motion_type;

#[cfg(feature = "resistance-weapon-adjust")]
pub mod resistance_weapon_adjust;

#[cfg(feature = "retainer-fortune-reward-range")]
pub mod retainer_fortune_reward_range;

#[cfg(feature = "retainer-task")]
pub mod retainer_task;

#[cfg(feature = "retainer-task-lv-range")]
pub mod retainer_task_lv_range;

#[cfg(feature = "retainer-task-normal")]
pub mod retainer_task_normal;

#[cfg(feature = "retainer-task-parameter")]
pub mod retainer_task_parameter;

#[cfg(feature = "retainer-task-parameter-lv-diff")]
pub mod retainer_task_parameter_lv_diff;

#[cfg(feature = "retainer-task-random")]
pub mod retainer_task_random;

#[cfg(feature = "ride-shooting")]
pub mod ride_shooting;

#[cfg(feature = "ride-shooting-scheduler")]
pub mod ride_shooting_scheduler;

#[cfg(feature = "ride-shooting-target")]
pub mod ride_shooting_target;

#[cfg(feature = "ride-shooting-target-scheduler")]
pub mod ride_shooting_target_scheduler;

#[cfg(feature = "ride-shooting-target-type")]
pub mod ride_shooting_target_type;

#[cfg(feature = "ride-shooting-text-data")]
pub mod ride_shooting_text_data;

#[cfg(feature = "role")]
pub mod role;

#[cfg(feature = "rp-parameter")]
pub mod rp_parameter;

#[cfg(feature = "satisfaction-arbitration")]
pub mod satisfaction_arbitration;

#[cfg(feature = "satisfaction-bonus-guarantee")]
pub mod satisfaction_bonus_guarantee;

#[cfg(feature = "satisfaction-npc")]
pub mod satisfaction_npc;

#[cfg(feature = "satisfaction-supply")]
pub mod satisfaction_supply;

#[cfg(feature = "satisfaction-supply-reward")]
pub mod satisfaction_supply_reward;

#[cfg(feature = "satisfaction-supply-reward-exp")]
pub mod satisfaction_supply_reward_exp;

#[cfg(feature = "scenario-tree")]
pub mod scenario_tree;

#[cfg(feature = "scenario-tree-tips")]
pub mod scenario_tree_tips;

#[cfg(feature = "scenario-tree-tips-class-quest")]
pub mod scenario_tree_tips_class_quest;

#[cfg(feature = "scenario-type")]
pub mod scenario_type;

#[cfg(feature = "screen-image")]
pub mod screen_image;

#[cfg(feature = "se")]
pub mod se;

#[cfg(feature = "se-battle")]
pub mod se_battle;

#[cfg(feature = "secret-recipe-book")]
pub mod secret_recipe_book;

#[cfg(feature = "secret-recipe-book-group")]
pub mod secret_recipe_book_group;

#[cfg(feature = "sequential-event")]
pub mod sequential_event;

#[cfg(feature = "sequential-event-multiple-range")]
pub mod sequential_event_multiple_range;

#[cfg(feature = "sharlayan-craft-works")]
pub mod sharlayan_craft_works;

#[cfg(feature = "sharlayan-craft-works-supply")]
pub mod sharlayan_craft_works_supply;

#[cfg(feature = "shell-fixed-from-command")]
pub mod shell_fixed_from_command;

#[cfg(feature = "skirmish")]
pub mod skirmish;

#[cfg(feature = "sky-island")]
pub mod sky_island;

#[cfg(feature = "sky-island-2")]
pub mod sky_island_2;

#[cfg(feature = "sky-island-2-mission")]
pub mod sky_island_2_mission;

#[cfg(feature = "sky-island-2-mission-detail")]
pub mod sky_island_2_mission_detail;

#[cfg(feature = "sky-island-2-mission-type")]
pub mod sky_island_2_mission_type;

#[cfg(feature = "sky-island-2-range-type")]
pub mod sky_island_2_range_type;

#[cfg(feature = "sky-island-map-marker")]
pub mod sky_island_map_marker;

#[cfg(feature = "sky-island-subject")]
pub mod sky_island_subject;

#[cfg(feature = "snipe")]
pub mod snipe;

#[cfg(feature = "snipe-collision")]
pub mod snipe_collision;

#[cfg(feature = "snipe-element-id")]
pub mod snipe_element_id;

#[cfg(feature = "snipe-hit-event")]
pub mod snipe_hit_event;

#[cfg(feature = "snipe-performance-camera")]
pub mod snipe_performance_camera;

#[cfg(feature = "snipe-talk")]
pub mod snipe_talk;

#[cfg(feature = "snipe-talk-name")]
pub mod snipe_talk_name;

#[cfg(feature = "spearfishing-combo-target")]
pub mod spearfishing_combo_target;

#[cfg(feature = "spearfishing-ecology")]
pub mod spearfishing_ecology;

#[cfg(feature = "spearfishing-item")]
pub mod spearfishing_item;

#[cfg(feature = "spearfishing-item-reverse")]
pub mod spearfishing_item_reverse;

#[cfg(feature = "spearfishing-notebook")]
pub mod spearfishing_notebook;

#[cfg(feature = "spearfishing-record-page")]
pub mod spearfishing_record_page;

#[cfg(feature = "spearfishing-silhouette")]
pub mod spearfishing_silhouette;

#[cfg(feature = "special-shop")]
pub mod special_shop;

#[cfg(feature = "special-shop-item-category")]
pub mod special_shop_item_category;

#[cfg(feature = "spectator")]
pub mod spectator;

#[cfg(feature = "stain")]
pub mod stain;

#[cfg(feature = "stain-transient")]
pub mod stain_transient;

#[cfg(feature = "stance-change")]
pub mod stance_change;

#[cfg(feature = "status")]
pub mod status;

#[cfg(feature = "status-hit-effect")]
pub mod status_hit_effect;

#[cfg(feature = "status-loop-vfx")]
pub mod status_loop_vfx;

#[cfg(feature = "story")]
pub mod story;

#[cfg(feature = "story-system-define")]
pub mod story_system_define;

#[cfg(feature = "submarine-exploration")]
pub mod submarine_exploration;

#[cfg(feature = "submarine-exploration-log")]
pub mod submarine_exploration_log;

#[cfg(feature = "submarine-map")]
pub mod submarine_map;

#[cfg(feature = "submarine-part")]
pub mod submarine_part;

#[cfg(feature = "submarine-rank")]
pub mod submarine_rank;

#[cfg(feature = "submarine-spec-category")]
pub mod submarine_spec_category;

#[cfg(feature = "switch-talk")]
pub mod switch_talk;

#[cfg(feature = "switch-talk-variation")]
pub mod switch_talk_variation;

#[cfg(feature = "system-graphic-preset")]
pub mod system_graphic_preset;

#[cfg(feature = "telepo-relay")]
pub mod telepo_relay;

#[cfg(feature = "territory-aethernet")]
pub mod territory_aethernet;

#[cfg(feature = "territory-aetheryte-list")]
pub mod territory_aetheryte_list;

#[cfg(feature = "territory-candidates")]
pub mod territory_candidates;

#[cfg(feature = "territory-chat-rule")]
pub mod territory_chat_rule;

#[cfg(feature = "territory-intended-use")]
pub mod territory_intended_use;

#[cfg(feature = "territory-type")]
pub mod territory_type;

#[cfg(feature = "territory-type-telepo")]
pub mod territory_type_telepo;

#[cfg(feature = "territory-type-transient")]
pub mod territory_type_transient;

#[cfg(feature = "text-command")]
pub mod text_command;

#[cfg(feature = "text-command-param")]
pub mod text_command_param;

#[cfg(feature = "tilt-param")]
pub mod tilt_param;

#[cfg(feature = "title")]
pub mod title;

#[cfg(feature = "tofu-bg")]
pub mod tofu_bg;

#[cfg(feature = "tofu-edit-param")]
pub mod tofu_edit_param;

#[cfg(feature = "tofu-object")]
pub mod tofu_object;

#[cfg(feature = "tofu-object-category")]
pub mod tofu_object_category;

#[cfg(feature = "tofu-preset")]
pub mod tofu_preset;

#[cfg(feature = "tofu-preset-category")]
pub mod tofu_preset_category;

#[cfg(feature = "tofu-preset-object")]
pub mod tofu_preset_object;

#[cfg(feature = "tomestone-convert")]
pub mod tomestone_convert;

#[cfg(feature = "tomestones")]
pub mod tomestones;

#[cfg(feature = "tomestones-item")]
pub mod tomestones_item;

#[cfg(feature = "topic-select")]
pub mod topic_select;

#[cfg(feature = "town")]
pub mod town;

#[cfg(feature = "trade-screen-image")]
pub mod trade_screen_image;

#[cfg(feature = "trait_")]
pub mod trait_;

#[cfg(feature = "trait-recast")]
pub mod trait_recast;

#[cfg(feature = "trait-transient")]
pub mod trait_transient;

#[cfg(feature = "transformation")]
pub mod transformation;

#[cfg(feature = "treasure")]
pub mod treasure;

#[cfg(feature = "treasure-hunt-rank")]
pub mod treasure_hunt_rank;

#[cfg(feature = "treasure-hunt-texture")]
pub mod treasure_hunt_texture;

#[cfg(feature = "treasure-model")]
pub mod treasure_model;

#[cfg(feature = "treasure-spot")]
pub mod treasure_spot;

#[cfg(feature = "tribe")]
pub mod tribe;

#[cfg(feature = "trigger-effect")]
pub mod trigger_effect;

#[cfg(feature = "triple-triad")]
pub mod triple_triad;

#[cfg(feature = "triple-triad-card")]
pub mod triple_triad_card;

#[cfg(feature = "triple-triad-card-obtain")]
pub mod triple_triad_card_obtain;

#[cfg(feature = "triple-triad-card-rarity")]
pub mod triple_triad_card_rarity;

#[cfg(feature = "triple-triad-card-resident")]
pub mod triple_triad_card_resident;

#[cfg(feature = "triple-triad-card-type")]
pub mod triple_triad_card_type;

#[cfg(feature = "triple-triad-competition")]
pub mod triple_triad_competition;

#[cfg(feature = "triple-triad-define")]
pub mod triple_triad_define;

#[cfg(feature = "triple-triad-resident")]
pub mod triple_triad_resident;

#[cfg(feature = "triple-triad-rule")]
pub mod triple_triad_rule;

#[cfg(feature = "triple-triad-tournament")]
pub mod triple_triad_tournament;

#[cfg(feature = "tutorial")]
pub mod tutorial;

#[cfg(feature = "tutorial-dps")]
pub mod tutorial_dps;

#[cfg(feature = "tutorial-gimmick")]
pub mod tutorial_gimmick;

#[cfg(feature = "tutorial-healer")]
pub mod tutorial_healer;

#[cfg(feature = "tutorial-tank")]
pub mod tutorial_tank;

#[cfg(feature = "uds_event")]
pub mod uds_event;

#[cfg(feature = "uds_object")]
pub mod uds_object;

#[cfg(feature = "uds_property")]
pub mod uds_property;

#[cfg(feature = "uds_stats")]
pub mod uds_stats;

#[cfg(feature = "ui-color")]
pub mod ui_color;

#[cfg(feature = "ui-color-picker-table")]
pub mod ui_color_picker_table;

#[cfg(feature = "ui-const")]
pub mod ui_const;

#[cfg(feature = "ui-level-lookup")]
pub mod ui_level_lookup;

#[cfg(feature = "valention-sweets-material")]
pub mod valention_sweets_material;

#[cfg(feature = "valention-sweets-recipe")]
pub mod valention_sweets_recipe;

#[cfg(feature = "vase")]
pub mod vase;

#[cfg(feature = "vase-flower")]
pub mod vase_flower;

#[cfg(feature = "vfx")]
pub mod vfx;

#[cfg(feature = "vvd-data")]
pub mod vvd_data;

#[cfg(feature = "vvd-notebook-contents")]
pub mod vvd_notebook_contents;

#[cfg(feature = "vvd-notebook-series")]
pub mod vvd_notebook_series;

#[cfg(feature = "vvd-route-data")]
pub mod vvd_route_data;

#[cfg(feature = "vvd-variant-action")]
pub mod vvd_variant_action;

#[cfg(feature = "vvd-vote-route")]
pub mod vvd_vote_route;

#[cfg(feature = "vvd-vote-route-label")]
pub mod vvd_vote_route_label;

#[cfg(feature = "warp")]
pub mod warp;

#[cfg(feature = "warp-condition")]
pub mod warp_condition;

#[cfg(feature = "warp-logic")]
pub mod warp_logic;

#[cfg(feature = "weapon-timeline")]
pub mod weapon_timeline;

#[cfg(feature = "weather")]
pub mod weather;

#[cfg(feature = "weather-group")]
pub mod weather_group;

#[cfg(feature = "weather-rate")]
pub mod weather_rate;

#[cfg(feature = "weather-report-replace")]
pub mod weather_report_replace;

#[cfg(feature = "web-guidance")]
pub mod web_guidance;

#[cfg(feature = "web-url")]
pub mod web_url;

#[cfg(feature = "wedding-bgm")]
pub mod wedding_bgm;

#[cfg(feature = "wedding-flower-color")]
pub mod wedding_flower_color;

#[cfg(feature = "wedding-plan")]
pub mod wedding_plan;

#[cfg(feature = "weekly-bingo-multiple-order")]
pub mod weekly_bingo_multiple_order;

#[cfg(feature = "weekly-bingo-order-data")]
pub mod weekly_bingo_order_data;

#[cfg(feature = "weekly-bingo-reward-data")]
pub mod weekly_bingo_reward_data;

#[cfg(feature = "weekly-bingo-text")]
pub mod weekly_bingo_text;

#[cfg(feature = "weekly-lot-bonus")]
pub mod weekly_lot_bonus;

#[cfg(feature = "weekly-lot-bonus-threshold")]
pub mod weekly_lot_bonus_threshold;

#[cfg(feature = "wks-achievement")]
pub mod wks_achievement;

#[cfg(feature = "wks-achievement-daily-define")]
pub mod wks_achievement_daily_define;

#[cfg(feature = "wks-achievement-reward-item")]
pub mod wks_achievement_reward_item;

#[cfg(feature = "wks-aethernet")]
pub mod wks_aethernet;

#[cfg(feature = "wks-aetheryte")]
pub mod wks_aetheryte;

#[cfg(feature = "wks-aetheryte-list")]
pub mod wks_aetheryte_list;

#[cfg(feature = "wks-aetheryte-object-group")]
pub mod wks_aetheryte_object_group;

#[cfg(feature = "wks-cosmo-tool-class")]
pub mod wks_cosmo_tool_class;

#[cfg(feature = "wks-cosmo-tool-common-level")]
pub mod wks_cosmo_tool_common_level;

#[cfg(feature = "wks-cosmo-tool-data-amount")]
pub mod wks_cosmo_tool_data_amount;

#[cfg(feature = "wks-cosmo-tool-name")]
pub mod wks_cosmo_tool_name;

#[cfg(feature = "wks-cosmo-tool-passive-buff")]
pub mod wks_cosmo_tool_passive_buff;

#[cfg(feature = "wks-cosmo-tool-ui-random-msg")]
pub mod wks_cosmo_tool_ui_random_msg;

#[cfg(feature = "wks-dev-grade")]
pub mod wks_dev_grade;

#[cfg(feature = "wks-dev-grade-bg-set")]
pub mod wks_dev_grade_bg_set;

#[cfg(feature = "wks-emergency-info")]
pub mod wks_emergency_info;

#[cfg(feature = "wks-emergency-info-text")]
pub mod wks_emergency_info_text;

#[cfg(feature = "wks-emergency-mission")]
pub mod wks_emergency_mission;

#[cfg(feature = "wks-emergency-mission-group")]
pub mod wks_emergency_mission_group;

#[cfg(feature = "wks-emergency-problem")]
pub mod wks_emergency_problem;

#[cfg(feature = "wks-fate-control")]
pub mod wks_fate_control;

#[cfg(feature = "wks-fortune-pattern-ui-color-set")]
pub mod wks_fortune_pattern_ui_color_set;

#[cfg(feature = "wks-fortune-pattern-ui-place")]
pub mod wks_fortune_pattern_ui_place;

#[cfg(feature = "wks-fortune-prize-grade")]
pub mod wks_fortune_prize_grade;

#[cfg(feature = "wks-fortune-sp-pattern-ui-place")]
pub mod wks_fortune_sp_pattern_ui_place;

#[cfg(feature = "wks-function")]
pub mod wks_function;

#[cfg(feature = "wks-item-info")]
pub mod wks_item_info;

#[cfg(feature = "wks-item-sub-category")]
pub mod wks_item_sub_category;

#[cfg(feature = "wks-mecha-event-data")]
pub mod wks_mecha_event_data;

#[cfg(feature = "wks-mecha-event-object")]
pub mod wks_mecha_event_object;

#[cfg(feature = "wks-mecha-event-object-group")]
pub mod wks_mecha_event_object_group;

#[cfg(feature = "wks-mecha-event-reward-ui")]
pub mod wks_mecha_event_reward_ui;

#[cfg(feature = "wks-mecha-field-searcher")]
pub mod wks_mecha_field_searcher;

#[cfg(feature = "wks-mecha-lively-actor-group")]
pub mod wks_mecha_lively_actor_group;

#[cfg(feature = "wks-mission-info")]
pub mod wks_mission_info;

#[cfg(feature = "wks-mission-lottery-cond")]
pub mod wks_mission_lottery_cond;

#[cfg(feature = "wks-mission-lottery-special-cond")]
pub mod wks_mission_lottery_special_cond;

#[cfg(feature = "wks-mission-map-marker")]
pub mod wks_mission_map_marker;

#[cfg(feature = "wks-mission-promotion-condition")]
pub mod wks_mission_promotion_condition;

#[cfg(feature = "wks-mission-recipe")]
pub mod wks_mission_recipe;

#[cfg(feature = "wks-mission-reward")]
pub mod wks_mission_reward;

#[cfg(feature = "wks-mission-supply-item")]
pub mod wks_mission_supply_item;

#[cfg(feature = "wks-mission-text")]
pub mod wks_mission_text;

#[cfg(feature = "wks-mission-to-do")]
pub mod wks_mission_to_do;

#[cfg(feature = "wks-mission-to-do-evalution-item")]
pub mod wks_mission_to_do_evalution_item;

#[cfg(feature = "wks-mission-to-do-evalution-refin")]
pub mod wks_mission_to_do_evalution_refin;

#[cfg(feature = "wks-mission-to-do-success-type")]
pub mod wks_mission_to_do_success_type;

#[cfg(feature = "wks-mission-unit")]
pub mod wks_mission_unit;

#[cfg(feature = "wks-next-planet-guidance")]
pub mod wks_next_planet_guidance;

#[cfg(feature = "wks-param")]
pub mod wks_param;

#[cfg(feature = "wks-pioneering-trail")]
pub mod wks_pioneering_trail;

#[cfg(feature = "wks-pioneering-trail-string")]
pub mod wks_pioneering_trail_string;

#[cfg(feature = "wks-planet-select")]
pub mod wks_planet_select;

#[cfg(feature = "wks-praise-hologram")]
pub mod wks_praise_hologram;

#[cfg(feature = "wks-praise-ui")]
pub mod wks_praise_ui;

#[cfg(feature = "wks-score-list")]
pub mod wks_score_list;

#[cfg(feature = "wks-shared-group")]
pub mod wks_shared_group;

#[cfg(feature = "wks-territory-info")]
pub mod wks_territory_info;

#[cfg(feature = "wks-text")]
pub mod wks_text;

#[cfg(feature = "wks-treasure")]
pub mod wks_treasure;

#[cfg(feature = "wks-treasure-info")]
pub mod wks_treasure_info;

#[cfg(feature = "wks-warp")]
pub mod wks_warp;

#[cfg(feature = "wks-zone-floor-collision")]
pub mod wks_zone_floor_collision;

#[cfg(feature = "world")]
pub mod world;

#[cfg(feature = "world-dc-group-type")]
pub mod world_dc_group_type;

#[cfg(feature = "xpvp-group-activity")]
pub mod xpvp_group_activity;

#[cfg(feature = "yard-catalog-category")]
pub mod yard_catalog_category;

#[cfg(feature = "yard-catalog-item-list")]
pub mod yard_catalog_item_list;

#[cfg(feature = "ykw")]
pub mod ykw;

#[cfg(feature = "zone-shared-group")]
pub mod zone_shared_group;

#[cfg(feature = "zone-timeline")]
pub mod zone_timeline;

